### ISSUE TITLE
the value '00' is not correctly displayed

### ISSUE THREAD

**Issue by marionFlx** [Agranom/ngx-material-timepicker#100]
Hello :)
Thank you for this timePicker and your great work
When I used it with the particulary value '00' the input value is truncated with '0' (please see the screen below)

`      <ngx-material-timepicker #pickerHeureDebut
                                 [confirmBtnTmpl]="confirmBtn"
                                 [cancelBtnTmpl]="cancelBtn"
                                 [enableKeyboardInput]="true"
                                 (closed)="onChangeHeureDebut()"
                                 [minutesGap]="10">
`

when `[enableKeyboardInput]="false" `the bug is fixed

Thank you for your help

![capture d ecran 2019-01-16 a 11 46 03](https://user-images.githubusercontent.com/718076/51244296-05ca4e80-1985-11e9-8272-494f98e6779b.png)

**Comment by Agranom** [comment]
Hi @marionFlx, thanks for your reply.
`enableKeyboardInput=true` implemented for keyboard working with a timepicker. The time format emits on blur event. Because if format time immediately it will be impossible for user to change time with keyboard.
