### ISSUE TITLE
Add an option to save last selected time on close

### ISSUE THREAD

**Issue by sancaruso** [Agranom/ngx-material-timepicker#102]
Currently closing the time picker when clicking on the overlay is as clicking on "cancel": the last selected time is not saved.
It would be great to have an option so that "OK" is the default case, so that clicking on the overlay saves the selected time.

**Comment by Agranom** [comment]
It saves selected value. Open timepicker -> select time -> close picker -> and open again. You'll see that time is the same that had been before closing

**Comment by Agranom** [comment]
It cannot change formControl if you don’t apply chosen time. If I will change input value and form control after closing, why do I need “ok” button ?

**Comment by Agranom** [comment]
I get your point. However it's unnecessary logic for now and it's just first request for this option. Maybe in future I'll implement it.
