### ISSUE TITLE
Keyboard input doesn't work with minutesGap != 1

### ISSUE THREAD

**Issue by sancaruso** [Agranom/ngx-material-timepicker#103]
If minutesGap is != 1 then the keyboard input doesn't work: we only can tip 0.

**Comment by Agranom** [comment]
Updated the timepicker, so that you can change time by keyboard arrows including minutesGap. Hope it wiil help you

**Comment by sancaruso** [comment]
@Agranom would it be possible to display the message "* use arrows (⇅) to change the time" only when the time is focused? And is there an option to customize the message, typically for translation?

**Comment by Agranom** [comment]
> would it be possible to display the message "* use arrows (⇅) to change the time" only when the time is focused?

yes, it would. I'll include it in the next release

> And is there an option to customize the message, typically for translation?

Not for now. I have and idea to add locales, and maybe somehow ii can be combined
