### ISSUE TITLE
Can't bind to 'ngxTimepicker' since it isn't a known property of 'input'

### ISSUE THREAD

**Issue by kojilab** [Agranom/ngx-material-timepicker#105]
Hi,

I have added NgxMaterialTimepickerModule.forRoot() in my app.module.ts imports and yet I am getting the error.

Thanks

**Comment by Agranom** [comment]
Hi. Can you show me how you use timepicker in your template?

**Comment by kojilab** [comment]
> Hi. Can you show me how you use timepicker in your template?

```
<input [ngxTimepicker]="timepicker" />
<ngx-material-timepicker #timepicker></ngx-material-timepicker>

```

Sorry for the late reply. I moved to other things.

**Comment by Agranom** [comment]
Is this still not working?

**Comment by kojilab** [comment]
No. I've switched to a different library.

**Comment by sijabbour** [comment]
What other library did you switch to?

**Comment by ashish-ksolves** [comment]
Hi,
Add NgxMaterialTimepickerModule in any other module except app.module.ts(like shared module.ts).
It worked for me !

**Comment by thavus** [comment]
> Hi, Add NgxMaterialTimepickerModule in any other module except app.module.ts(like shared module.ts). It worked for me !

Doesn't work.

**Comment by thavus** [comment]
> Is this still not working?

3 years later, it still does not work. Can confirm.

**Comment by bababuyababa** [comment]
> 3 years later, it still does not work. Can confirm.

4 years later, it still does not work.

**Comment by AmielFabreguettes** [comment]
5 years later, it still does not work.

**Comment by Agranom** [comment]
@AmielFabreguettes Can you show me the example? You probably doing something wrong
