### ISSUE TITLE
Dead zone near 00

### ISSUE THREAD

**Issue by hblieb** [Agranom/ngx-material-timepicker#109]
In your demo (and our app) there is a dead zone in the area of the 00. If the minute hand is somewhere else (like 25 minutes), and I click on the left side of the second 00 near the "12 o'clock" position, the minute hand doesn't move at all. If I click around the 00 a little bit, I can find a live click target and the minute hand will move as expected.

Also, the demo page doesn't seem to work in IE11. Can this component be made to work in IE11?

**Comment by Agranom** [comment]
Hi. I’ll fix it in the next release. 
IE 11 is not preferable for demo page, sorry.

**Comment by Agranom** [comment]
fixed
