### ISSUE TITLE
elements display misplacement

### ISSUE THREAD

**Issue by gmareater** [Agranom/ngx-material-timepicker#110]
hi
at first, thanx for your beautiful component.
second, you can look at the picture, at first i thought it's related to rtl , but after removing rtl, yet problem exists
any idea?
![image](https://user-images.githubusercontent.com/6206777/52619839-11436380-2eb8-11e9-911f-78e724e0a524.png)

**Comment by Agranom** [comment]
Hi. Can you provide me with any steps to reproduce it, thanks.

**Comment by gmareater** [comment]
hi
no special step, just npm install and add to module and html,
it's a rtl project with some modification to default theme, but i checked (or tried) to find if changes are problem but found nothing

**Comment by Agranom** [comment]
Hi. I checked your issue. You can override direction for timepicker directly by setting `direction: ltr` for `.timepicker {}` class.

**Comment by benengi** [comment]
Hello,
I have the same situation even after overriding the direction for timepicker class
**steps :**
1- add a class timepicker to ngx-material-timepicker: <ngx-material-timepicker #picker class ='timepicker'></ngx-material-timepicker>
2- apply direction: ltr to timepicker

result : no changes ( misplacement )
