### ISSUE TITLE
On Open timepicker set current time (not on page load)

### ISSUE THREAD

**Issue by hopeinfo** [Agranom/ngx-material-timepicker#112]
Hey, Great day to you
 I am using angular and that's why page is not refresh or reload every time. 
timepicker is on top of my page, so only first time I can set default current time. so when user redirect to any page component I can not set default time every time.

I need to set current time on default time when user open timepicker popup. 

is there is Event onShow or onPopup or OnOpen ?

or How can I set Current time on open of popup ? (I am use Angular 7)
I use  "ngx-material-timepicker": "^2.12.0", 

Thanks

**Comment by Agranom** [comment]
Hi. There are not such events, but I’ll add it in the next release. Keep in touch

**Comment by hopeinfo** [comment]
> 
> 
> Hi. There are not such events, but I’ll add it in the next release. Keep in touch

Thank you for Reply. I am waiting for it.

**Comment by Agranom** [comment]
Done. Added `opened` event. You can find more details in README.md

**Comment by hopeinfo** [comment]
Thank you @Agranom
