### ISSUE TITLE
clicking area for 00 and 12 in 24 format

### ISSUE THREAD

**Issue by sevikk** [Agranom/ngx-material-timepicker#114]
In you timepicker there moved click area for choosing 00 or 12 hours  in format 24 hours
Please see the screen shot. There on your demo is also

![image](https://user-images.githubusercontent.com/17278237/52949328-a0eb8500-3384-11e9-8a31-d8c9ce1fac8f.png)

**Comment by FiveSigma5** [comment]
I've cheked in Chrome, and the clicking areas are something more like this, which is ok imho:
![image](https://user-images.githubusercontent.com/22745174/53007906-7fe46c00-3438-11e9-9072-547e63a54dd2.png)

**Comment by sevikk** [comment]
I see it. It happened when want to edit time. Please see the screen shoots

There i try to click on 00 hours
![image](https://user-images.githubusercontent.com/17278237/53084252-226c2000-3509-11e9-97cf-0aa5dfd7c011.png)

And then gets 12 hours 

![image](https://user-images.githubusercontent.com/17278237/53084344-55161880-3509-11e9-9bb0-2d73461873ae.png)

Thank you

**Comment by FiveSigma5** [comment]
Got it.

It happens when you try to click 00, because the clickable area of the "selection bar" seems to be widder than the blue line itself, so you activate the drag and drop selection and instantly select the 12.

If you try to drag the big blue dot marking the hour you shouldn't have any problem.

Maybe @Agranom wants to fix the little bar clickable area, but I see it as a very minor bug.

**Comment by anaaChacon** [comment]
This plugin not work un angular 5, is possible one solution for that this plugin work for me with format 24h? Exist one fork ?

**Comment by Agranom** [comment]
You can fork it and downgrade to angular 5

**Comment by anaaChacon** [comment]
How can I downgrade it to angular 5? Os easy?

**Comment by paultobey** [comment]
I think the actual problem may arise from clicking exactly at 0 degrees from vertical on the "00". One of our QA guys found this also. I tracked it here:

```
    @HostListener('click', ['$event'])
    @HostListener('touchmove', ['$event.changedTouches[0]'])
    @HostListener('touchend', ['$event.changedTouches[0]'])
    @HostListener('mousemove', ['$event'])
    selectTime(e: MouseEvent | Touch): void {

        if (!this.isStarted && (e instanceof MouseEvent && e.type !== 'click')) {
            return;
        }
        const clockFaceCords = this.clockFace.nativeElement.getBoundingClientRect();

        /* Get x0 and y0 of the circle */
        const centerX = clockFaceCords.left + clockFaceCords.width / 2;
        const centerY = clockFaceCords.top + clockFaceCords.height / 2;
        /* Counting the arctangent and convert it to from radian to deg */
        const arctangent = Math.atan(Math.abs(e.clientX - centerX) / Math.abs(e.clientY - centerY)) * 180 / Math.PI;
        /* Get angle according to quadrant */
        const circleAngle = countAngleByCords(centerX, centerY, e.clientX, e.clientY, arctangent);
        /* Check if selected time from the inner clock face (24 hours format only) */
        const isInnerClockChosen = this.format && this.isInnerClockFace(centerX, centerY, e.clientX, e.clientY);
        /* Round angle according to angle step */
		const angleStep = this.unit === TimeUnit.MINUTE ? (6 * (this.minutesGap || 1)) : 30;
		
		// Original:
        // const roundedAngle = isInnerClockChosen
        //     ? roundAngle(circleAngle, angleStep) + 360
        //     : roundAngle(circleAngle, angleStep);
        // const angle = roundedAngle === 0 ? 360 : roundedAngle;

		// Fixed code:
		// We need to handle the angle = 0 case *before* applying the isInnerClockChosen adjustment
		// or clicking at 0 degrees will always select the outer ring and you'll get 12 when you
		// wanted 00 hours.
        const roundedAngle = roundAngle(circleAngle, angleStep);
		const angle = (roundedAngle || 360) + (isInnerClockChosen ? 360 : 0);

        const selectedTime = this.faceTime.find(val => val.angle === angle);

        if (selectedTime && !selectedTime.disabled) {
            this.timeChange.next(selectedTime);

            /* To let know whether user ended interaction with clock face */
            if (!this.isStarted) {
                this.timeSelected.next(selectedTime.time);
            }
        }

    }
```

I've commented out the Original code and commented-in my suggested fix.

**Comment by Agranom** [comment]
@paultobey Thanks, I'll check it

**Comment by Agranom** [comment]
Works great, thank you. You can update the timepicker to the latest version
