### ISSUE TITLE
24  hour format time picker is not working when i use in toggle icon

### ISSUE THREAD

**Issue by vadempur** [Agranom/ngx-material-timepicker#115]
24 hour format
                    <div class="input-group mb-3 col-sm-8">
                      <input  formControlName="arrivalTime" #arritime  (blur)="validateTime($event,'arrivalTime')"  placeholder="HH:MM" class="form-control form-control-sm" >
                 
                      <div class="input-group-append">
                       <span class="input-group-text " id="basic-addon1"><input  *ngIf="arrivalBtn"  (change)="addcurrentTime()" type="checkbox" value="" >
                        <ngx-material-timepicker-toggle   [for]="arrivalTime"></ngx-material-timepicker-toggle>
                        <ngx-material-timepicker   (click)="onChanges(arrivalTime)"  #arrivalTime [format]="24" ></ngx-material-timepicker>
                      </span>
                      </div>
                    </div>

**Comment by Agranom** [comment]
@vadempur you just use [format]=24 in a wrong place. It should be placed with [ngxTimepicker] directive. Look at the doc.

**Comment by vadempur** [comment]
yes but I m trying to use it in without directive in input so I can enter my time input directly to a textbox  
needed both timepicker and input option also

**Comment by Agranom** [comment]
You can make input as hidden type and provide format
