### ISSUE TITLE
ngx-material-timepicker is remembering the time even if i delete the time from the input field

### ISSUE THREAD

**Issue by bbnhbb** [Agranom/ngx-material-timepicker#117]
Whenever I click on the input field opening time and set it some time say 9:00 am and then if I clear that input field and then again if I click on that input field I seeing it is storing its old time, this is hurting me badly whenever I explicitly make the text field empty(form value) when comparing the opening and closing time, if opening time is past closing time is true.

Is there any work around for this

Stackblitz link https://stackblitz.com/edit/seekonline

https://stackoverflow.com/questions/55067500/ngx-material-timepicker-is-remembering-the-time-even-if-i-delete-the-time-from-t

![image](https://user-images.githubusercontent.com/10373697/54042472-380f6400-41f0-11e9-81c7-e5bc7a038691.png)

**Comment by Agranom** [comment]
How do you clear input field?

**Comment by Agranom** [comment]
https://stackblitz.com/edit/seekonline  I try your example, but there are default time 12:00 am on each input field

**Comment by bbnhbb** [comment]
Steps to clear the input:
Step1: click on the first input field.
Step2: select the time.
Step3: Again press on the same input field time pop up will appear.
Step4:  click esc button.
Step5: Cntl + A and backspace.

I understand that manually nobody is going to do so, but I am implicitly clearing the input field from my code and so the above problem is appearing.

**Comment by Agranom** [comment]
How do you clear the input value ?

**Comment by bbnhbb** [comment]
Please check out the vedio
https://vimeo.com/324495690

**Comment by Agranom** [comment]
Could you just make the input as a readonly one ?

**Comment by Agranom** [comment]
Any updates ?

**Comment by gramn** [comment]
I would like to ask to reopen this issue as the problem exists even on Nov 2022.
