### ISSUE TITLE
Export 'NgxMaterialTimepickerComponent'

### ISSUE THREAD

**Issue by Enngage** [Agranom/ngx-material-timepicker#119]
Can you please export `NgxMaterialTimepickerComponent` as public API? I would like to access some properties in it directly. 

I got it working by importing `ɵb` from your `ngx-material-timepicker`, but I don't really understand why you use this alias instead of just exporting the component.

**Comment by Agranom** [comment]
It sets that alias by itself. I'll export `NgxMaterialTimepickerComponent` as public API

**Comment by Agranom** [comment]
Why do you need an access to the component? Maybe I can provide some outputs for you?

**Comment by Enngage** [comment]
Awesome, thanks :-) For example, I wanted to `open`  the timepicker from code behind.

**Comment by dima-gusyatiner** [comment]
This is also the easiest hack to allow the use of the time-picker inline, without the pop-up.
I could extend the component class, and remove the pop-up from the HTML.

**Comment by Agranom** [comment]
Done.
