### ISSUE TITLE
'selectedPeriod' contains incorrect values

### ISSUE THREAD

**Issue by Enngage** [Agranom/ngx-material-timepicker#120]
Hope you don't mind me posting some issues :)

If the `24` mode is enabled, the `selectedPeriod` contains string with number value, but its type only allows 'AM' or 'PM'.

**Comment by Agranom** [comment]
> Hope you don't mind me posting some issues :)
It's great you test it )

You're not suppose to have access to selectedPeriod ))

**Comment by Agranom** [comment]
Fixed it.
