### ISSUE TITLE
Timepicker issue when selecting 12:00 am/pm

### ISSUE THREAD

**Issue by DasCode94** [Agranom/ngx-material-timepicker#121]
I am trying to use ngx-material-timepicker with Ionic 4 and Angular 7.

First time I open the timepicker and set 12:00 am,
![Screen Shot 2019-03-18 at 3 45 32 PM](https://user-images.githubusercontent.com/39510538/54523197-eb1c5200-4994-11e9-92c2-3f6204576421.png)

Then I open it back again to see this
![Screen Shot 2019-03-18 at 3 45 43 PM](https://user-images.githubusercontent.com/39510538/54523198-ebb4e880-4994-11e9-9777-8ff39ed71294.png)

Getting the following error in console - 
```
ERROR TypeError: Cannot read property 'angle' of undefined
    at NgxMaterialTimepickerFaceComponent.push../node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js.NgxMaterialTimepickerFaceComponent.setClockHandPosition (ngx-material-timepicker.js:1662)
```

Any help would be appreciated.

Thanks!

**Comment by Agranom** [comment]
Hi. I'll fix it. It occurs after breaking changes. You can switch to the previous stable version 2.13.0 for now.

**Comment by DasCode94** [comment]
I'll have a look. Thank you for the quick response :).

**Comment by Agranom** [comment]
Already fixed this issue. Please update to the latest version
