### ISSUE TITLE
Timepicker selected value is always 00:00 both tapping 00 and 12

### ISSUE THREAD

**Issue by mattinove** [Agranom/ngx-material-timepicker#122]
Hi, when i try to select the **12:00** value in **24h format** the return value is always **00:00**.
The problem relates **only** to the value **returned** by the component as it is **displayed correctly** on the timepicker dialog.

Thanks

**Comment by Casimodo72** [comment]
Also when using the 24h format and using the arrow keys in the HTML input matInput type="time" (i.e. not the time-picker but the HTML 5 time input control) one can't select 12 hours; the value jumps to 00 in this case.

**Comment by Agranom** [comment]
Already fixed this issue. Please update to the latest version
