### ISSUE TITLE
Feature - Set multiple disabled time intervals.

### ISSUE THREAD

**Issue by primissus** [Agranom/ngx-material-timepicker#125]
You can already set `minTime` and `maxTime` to disable a complete time interval.
But we someTimes need to disable multiple time intervals where you shouldn't be able to select those intervals (just as `minTime` and `maxTime` but it might be not continuous). May be if you just could set an array like `[[minTime1, maxTime1], [minTime2, maxTime2]]`.

I am aware that it could be hard to implement, but i wonder if it is in your feature objectives.

Thanks in advance.

**Comment by Agranom** [comment]
I'll check the possibility
