### ISSUE TITLE
Use in MatFormField?

### ISSUE THREAD

**Issue by blissi** [Agranom/ngx-material-timepicker#126]
Hallo,
do you plan to make the timepicker work properly inside of a mat-form-field?
At the moment everyone would need to style it on their own.

**Comment by Agranom** [comment]
Hi. Could you provide a small example on https://stackblitz.com ?

**Comment by maxwellt** [comment]
I think I had a similar problem when I wanted to place the timepicker in a MatFormField, but I solved it by only placing the <input> element in the <mat-form-field> and placing the <ngx-material-timepicker> outside it. Then it works perfectly.

Small example:
```
  <mat-form-field appearance="outline">
    <mat-label>{{ 'TEndTime' | translate }}</mat-label>
    <input matInput [ngxTimepicker]="endTime" [format]="24" placeholder="{{ 'TEndTime' | translate }}" formControlName="endTime" required />
  </mat-form-field>
  <ngx-material-timepicker #endTime></ngx-material-timepicker>
```

**Comment by blissi** [comment]
Thanks, it works :-)

**Comment by Supratentorial** [comment]
Might be worth adding this to documentation or adding an example. I imagine quite a few people will be using angular material and using ngx-material-timepicker in a form with other material elements.

**Comment by Agranom** [comment]
@Supratentorial I guess it's already an outdated solution, because timepicker renders in the `body` now

**Comment by Gil-Epshtain** [comment]
I know that his is an old and closed issue. However I still got this problem in 2020. 

The problem in my case was solved by adding the `[format]="24"` to the input.

This is an optional attribute but for some odd reason, when the input in placed inside `mat-form-field`, the format attribute become mandatory.

**Comment by LuisOfCourse** [comment]
@Gil-Epshtain can you provide an example? Im still getting this issue.
`								<div class="col-md-5">
									<mat-form-field >
										<mat-label>From</mat-label>
										<input [ngxTimepicker]="pickerFrom" [format]="24" matInput formControlName="from" required />
									</mat-form-field>
									<ngx-material-timepicker
										#pickerFrom
										[enableKeyboardInput]="true"
									>
									</ngx-material-timepicker>
								</div>`
