### ISSUE TITLE
Min validation issue when using 24 format

### ISSUE THREAD

**Issue by angeor2** [Agranom/ngx-material-timepicker#127]
Great work on the component. 
However, I'm having problem using it with 24 format at the moment due to the following behavior.

Consider the following case:
Format: 24
min: 11:40 am
setting value 12:40 (not stating am/pm as this is 24format)
Expected behavior: set value without error
current behavior:  'Selected time doesn't match min or max value'

In my opinion this is what is going on
setting the value in ngx-timepicker.directive.ts:
` const time = TimeAdapter.formatTime(value, this._format);`
 `if (TimeAdapter.isTimeAvailable(time, <DateTime>this._min, <DateTime>this._max, 'minutes', this._timepicker.minutesGap)) {`

leads to time evaluating to '12:40'
and in the isTimeAvailable function:

` const convertedTime = this.convertTimeToDateTime(time);` 

The convertTimeToDateTime function is using format 12 by default.

`static convertTimeToDateTime(time: string, format = 12): DateTime {`
`        const timeMask = (format === 24) ? TimeFormat.TWENTY_FOUR_SHORT : TimeFormat.TWELVE_SHORT;`
`        return DateTime.fromFormat(this.parseTime(time, format), timeMask);
    }
`
which means that parseTime will be called with parameters '12:40', 12 
leading to isPM ending with the wrong value:
`const isPM = +h > 12;`
h is 12, m is 40, 12:40 is pm, however isPM will be false and parseTime will return '12:40 AM'
If I'm not mistaken luxon parses this as 00:40 AM.

00:40 AM is less than 11:40 so the timepicker is complaining.

**Comment by Agranom** [comment]
Hi. I'll check it out and fix

**Comment by Agranom** [comment]
I've just checked with the same settings and it works. Which version do you use ?

**Comment by angeor2** [comment]
It's the latest version 3.0.2. I'll try to create a minimal project to reproduce the issue and come back.

**Comment by angeor2** [comment]
hi again, please check this stackblitz: https://stackblitz.com/edit/angular-aipfv2

**Comment by Agranom** [comment]
I see. I'll fix it and let you know

**Comment by alfonso-eusebio** [comment]
Hi,

I'm having the same issue.
In case it helps, the problem is in TimeAdapter.isTimeAvailable(). The following call to convertTimeToDateTime() doens't include the `format` parameter, so it defaults to 12-hours.

`const convertedTime = this.convertTimeToDateTime(time);`

Regards,
Alfonso

**Comment by alfonso-eusebio** [comment]
Hi,

I have the same issue. My current solution is to explicitly set the format to 24, which seems to avoid the conversion issue.

`const convertedTime = this.convertTimeToDateTime(time, 24);`

In any case, I think the "proper" solution involves a review of the set of functions that deal with parsing and conversion in that class.

Regards,
Alfonso

**Comment by Agranom** [comment]
Fixed. Update to v3.0.3

**Comment by alfonso-eusebio** [comment]
v3.0.3 does the trick for me.

**Comment by Agranom** [comment]
Is it fixed ?

**Comment by angeor2** [comment]
Hi, I just had the time to check it and it works as expected.
Once again great work
