### ISSUE TITLE
Convert Input time to 24hrs in ts file 

### ISSUE THREAD

**Issue by Ram12393** [Agranom/ngx-material-timepicker#129]
Everything works fine till now. Here I have requirement(I want display only 12hrs calendar)
1) If a user select time as `10:30 am` then I need to send to my back-end as 10:30:00
2) As well as if user select time as `10:30 pm` then I need to send to my back-end as 22:30:00

I tried like below
`this.timer.replace(/ /g, '').replace('am', ':00').replace('pm', ':00')`. I there any option to do my requirement?

**Comment by Agranom** [comment]
If you use the latest version of timepicker, you have luxon library installed in you project and you can format it like so:
`DateTime.fromFormat('10:30 am', 'hh:mm a').toFormat('hh:mm')`

**Comment by Ram12393** [comment]
I will try this. thanks for your reply

**Comment by Agranom** [comment]
any updates ?

**Comment by Ram12393** [comment]
till now it's working fine. Thank you

**Comment by KK220794** [comment]
I tried using  DateTime.fromFormat('10:30 am', 'hh:mm a').toFormat('hh:mm') but instead of 22:30 its giving me 10:30.

**Comment by Agranom** [comment]
@KK220794 change `am` to `pm`.

**Comment by KK220794** [comment]
sorry. it was a typo. i gave pm only. 
` console.log(DateTime.fromFormat('10:30 pm', 'hh:mm a').toFormat('hh:mm'));`
on logging it in console, it gave 10:30

**Comment by Agranom** [comment]
@KK220794 change small `hh` to bigger ones `HH` in `toFormat()`

**Comment by KK220794** [comment]
@Agranom  Its now working fine.

**Comment by sinanasiriamirbande** [comment]
it has an error yet.
some date like 03:45 am from time picker is like 3:45 and luxon show invalid date.
do you have any solution ?
