### ISSUE TITLE
Min and max values

### ISSUE THREAD

**Issue by jamilalisgandarov** [Agranom/ngx-material-timepicker#13]
Is there a way to define min and max for timepicker?

**Comment by Agranom** [comment]
No, but you can tell me  a use case for those features and if it useful, I'll implement it.

**Comment by jamilalisgandarov** [comment]
In our project for example, we have to define start hour and end hour of lessons. So end hour is depend on start hour as min value.

**Comment by Agranom** [comment]
Okey, I see. I'll try to find some time this week to implement this feature

**Comment by Agranom** [comment]
Implemented min and max time (https://github.com/Agranom/ngx-material-timepicker/commit/e084e28f353420b9c74238a1b7e6688c61a7ee1b). Update to 2.3.0 and enjoy 😃
