### ISSUE TITLE
ngx-material-timepicker not display top of component

### ISSUE THREAD

**Issue by raashidalam** [Agranom/ngx-material-timepicker#131]
It not displaying proper way.

**Comment by Agranom** [comment]
It may occur because you place timepicker component inside some container with overflow: hidden. Try to move it outside of the container

**Comment by raashidalam** [comment]
We need time picker in a specific component. Is any style is there to display on top

**Comment by dody87** [comment]
same issue, i have the timepicker inside a bootstrap modal and i can't set style in order to change position (timepicker header is not visible).

**Comment by dody87** [comment]
> same issue, i have the timepicker inside a bootstrap modal and i can't set style in order to change position (timepicker header is not visible).

Finally i fixed it putting an id to component and then adding a css style auto for position on .timepicker-overlay class on styles.scss

`
#picker .timepicker-overlay {
  top: auto !important;
}
`
