### ISSUE TITLE
Dificult to click/touch on minutes

### ISSUE THREAD

**Issue by alfonso-eusebio** [Agranom/ngx-material-timepicker#132]
Hi,

I'm using your excellent timepicker but have noticed that selecting minutes is quite difficult, specially in touch devices.
As far as I can see, the problem is that the touch/click "target" area for each minute in the dial is just 6 degrees around the number on the screen. This makes sense when all 60 minutes are allowed, but not so much when you have a minutesGap.

The place where this is calculated seems to be in function _selectTime()_ in ngx-material-timepicker-face.component.ts.

`const angleStep = this.unit === TimeUnit.MINUTE ? 6 : 30;`

Maybe something like this would provide a bigger touch/click target when using minutesGap?

`const angleStep = this.unit === TimeUnit.MINUTE ? (this.faceTime.length <= 30 ? 12 : 6) : 30;`

I thought about making the angle proportional to the gap size (e.g. `360 / (60 / this.minutesGap)`), but I don't know if that would be intuitive to use.
In the meantime, any pointers to how I can change this behaviour in the current version?

Thanks & regards,
Alfonso

**Comment by alfonso-eusebio** [comment]
Actually, I didn't pay attention to the rounding calculations and assumed that `angleStep` was some kind of "margin" angle around each minute position, which is not.

I'm using this change below as a temporary solution for my project, just in case it helps.

`const angleStep = this.unit === TimeUnit.MINUTE ? Math.round(360 / this.faceTime.length) : 30;`

This creates a "target area" that goes half way between each minute position. It works for my 15 minute gaps, but I haven't tested it with other configurations.

Perhaps it might be better to change the approach to checking that the click/touch point angle is within certain margin of the actual minute position, and defining that margin to be roughly as wide as the minute circle whenever possible (e.g. when using minutesGap > 2)?
This will create a "target" area around each minute that's big enough to hit with the thumb; but not as big as my current solution.

Regards,
Alfonso

**Comment by Agranom** [comment]
Hi. Thank you for the reply. I'll try your soulution or find another one

**Comment by Agranom** [comment]
Check please v3.0.3
