### ISSUE TITLE
Change show up animation type

### ISSUE THREAD

**Issue by tomasznastaly** [Agranom/ngx-material-timepicker#134]
Actually the popup with timepicker slides down from the top, it is possible to disable this effect? Or set fade-in effect to make it more consistent with Angular Material Dialog?

**Comment by Agranom** [comment]
I can add flag for disabling animation at all

**Comment by tomasznastaly** [comment]
would be great, when you will be able to do that?

**Comment by Agranom** [comment]
During this week.

**Comment by Agranom** [comment]
Added `disableAnimation` flag. Please update to v3.1.0
