### ISSUE TITLE
Closed event when cancel button is clicked

### ISSUE THREAD

**Issue by mini1612** [Agranom/ngx-material-timepicker#135]
Hi,

Is there anyway to get whether closed event is trigger after clicking Ok or Cancel button. As currently on both button click, closed event is invoked and argument is of type null so no way to figure out which button triggered this event.

**Comment by Agranom** [comment]
Hi.
I will add some information to closed event, to let you know whether it is cancel or Ok button

**Comment by Agranom** [comment]
There is timeSet event that triggers after clicking Ok button, so you can listen to it
