### ISSUE TITLE
Min max not working as expected when minutes is not zero 00

### ISSUE THREAD

**Issue by mini1612** [Agranom/ngx-material-timepicker#137]
When min/max is set with min 00, it works correctly but if min is set with some  minute for ex 11:30 am then clock open default time as 11:00am and on click of Ok it could be set. I think default time should be set ti 11:30 am instead of 11: 00am , is there any way or am I missing something? If I click on minutes then time before 11:30 would be disabled but if I doesn't click on minutes and on hour tab then 11:00 is default.

**Comment by Agranom** [comment]
You couldn't set that time (11:00 am). Instead You get an warning message in your console
