### ISSUE TITLE
Invalid date time 

### ISSUE THREAD

**Issue by raymonschouwenaar** [Agranom/ngx-material-timepicker#139]
I'm currently using this awesome timepicker, but selecting time goes very good, but displaying the time in the input field not so much :-(

The red bordered input fields should display the time. The input fields below it are the values that goes into the timepicker. But I can't find any place in the documentation on what the value Input expect for value in order to show the correct value.
<img width="331" alt="Screenshot 2019-05-15 at 09 02 18" src="https://user-images.githubusercontent.com/6241164/57755192-852c1c80-76f0-11e9-9e12-c758b6f8a5fa.png">

Hopefully someone can point me in the right direction. Any help would be welcome 👍

**Comment by Agranom** [comment]
Hi,
You should set time like this `11:00 pm` or `23:00`. Sorry for not clear doc.

**Comment by raymonschouwenaar** [comment]
@Agranom thanks that worked ;-) ... Maybe a good idea to update that in the documentation, this will also help others. For the rest, great work on the timepicker 👍 👍
