### ISSUE TITLE
24 hour format

### ISSUE THREAD

**Issue by kubandae** [Agranom/ngx-material-timepicker#14]
Thank you for this nice time picker.
Is there a way to implement full 24 hour format ? 
- no AM/PM switches
- 24 hour labels for picking an hour

**Comment by Agranom** [comment]
There was already an issue about 24-hours clock face. Issue was closed because clock face looked terrible. But I see now that it's useful feature for someone, so I'll try to find the best way where 24-hours format looks well

**Comment by jbbergy** [comment]
I NEEEEEEED this feature too.  The actual option to do that doesn't work.

Thanks for your great job, with the 24hours options, this timepicker will be unavoidable

**Comment by celiacheff** [comment]
Need this one too. This is particularly needed for countries which don't use AM/PM format...
On Android, the 13 -> 00 hours are in a smaller inner circle.
![screenshot_2018-07-26](https://user-images.githubusercontent.com/4281516/43252830-bfd8209a-90c3-11e8-98c0-73479be7e04c.png)

**Comment by Agranom** [comment]
I added 24-hours clock face. Check it out on the demo page, or update timepicker to 2.5.0 version.

**Comment by jbbergy** [comment]
work great. thanks for your reactivity :)
