### ISSUE TITLE
Default Timepicker- setting value and min/max in 24hr, 12:00 not setting as expected

### ISSUE THREAD

**Issue by mini1612** [Agranom/ngx-material-timepicker#141]
when using default timepicker format and setting values and min max in 24 hr format, then anythig with 12hr and some min is being considered as AM and not as PM  should be pm but it is considering as am which is raising issue on Min Max validation.

For ex: In 24hr format
start Time :  8:00 [max]="endTime" 
End time : 12:30 [min]="startTime"
it results in error as **Selected time doesn't match min or max value**
Expected result: should be valid as its 8:00 am and 12:30 pm

**Comment by Agranom** [comment]
Could you provide pls example on https://stackblitz.com ?

**Comment by MatthieuKnittel** [comment]
I have the same problem.
          <input matInput [ngxTimepicker]="FromTime" [format]="24" [(ngModel)]="fromTime"
                      name="firstFrom" placeholder="De" [min]="12:00"  required>

This example doesn't work as "12:00" seems to be interpreted as midnigh instead of noon in 24hr format

**Comment by Agranom** [comment]
I've just set `[min]="'12:00'"` and it works as expected (hours from **00** to **11** are disabled)
