### ISSUE TITLE
Trigger open hook

### ISSUE THREAD

**Issue by AdditionAddict** [Agranom/ngx-material-timepicker#143]
Is there a way to trigger the popup dialog to open (dynamically)?

**My use case**: I have a date separately selected (date worked) and user is to input time using your wonderful ngx-material-timepicker but sometimes the time selected refers to the the date selected or the next day (long hours etc)
**My solution**: A modal dialog with a ngx-material-timepicker and 'next day' toggle, modal yields a datetime (moment). When I click input, my modal opens but user needs to click ngx-material-timepicker-toggle to trigger the time picker which is a bit clumsy.

**Alternatives**: is there a way to use time picker inline or add to modal popup?

**Comment by Agranom** [comment]
You can get access to the timepicker like this
 `<ngx-material-timepicker #picker></ngx-material-timepicker>`
and then you'll have possibility to call `open()` method

**Comment by AdditionAddict** [comment]
My bad, need to more of the basics (new to angular), got this working after reading up on ViewChild, Thank you for the quick response :)
