### ISSUE TITLE
ngx-material-timepicker - @output() timeSet: output time always in AM

### ISSUE THREAD

**Issue by Aidan-Chey** [Agranom/ngx-material-timepicker#145]
The ngx-material-timepicker component has an output attribute of "timeSet" that outputs whenever a time is picked via the timepicker.

The resulting time chosen that is output by this attribute is always in the morning (i.e. "04:45 am"), even if in the timepicker, the "PM" option was chosen.

I was attempting to use the timepicker in a way that is separated from an input field (does not have [ngxTimepicker] in the input), so that the input field could accept free-type and handle setting the input field value myself. However, this issue surfaced which made it unusable.

**Comment by Aidan-Chey** [comment]
I've discovered that this was mainly occuring because the timepicker wasn't directly associated with an input field by adding the [ngxTimePicker] attribute.

When it is added to one it behaves as expected and outputs what ever is added to the input's value.

I guess it would be best to wait for what you do for issue #55 as that may bypass my desire to separate the picker from an input field.

**Comment by Agranom** [comment]
Check #55
