### ISSUE TITLE
Build with --prod causes errors

### ISSUE THREAD

**Issue by jankowskirobert** [Agranom/ngx-material-timepicker#146]
So i'am using:
- "luxon": "1.15.0",
- "ngx-material-timepicker": "3.1.0",

Tried to build my project with --prod option. In the result i've got:

> ERROR in node_modules/ngx-material-timepicker/src/app/material-timepicker/services/ngx-material-timepicker.service.d.ts(15,50): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/services/ngx-material-timepicker.service.d.ts(15,65): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/ngx-material-timepicker.component.d.ts(42,32): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/ngx-material-timepicker.component.d.ts(43,32): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/directives/ngx-timepicker.directive.d.ts(9,19): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/directives/ngx-timepicker.directive.d.ts(11,19): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-hours-face/ngx-material-timepicker-hours-face.d.ts(6,14): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-hours-face/ngx-material-timepicker-hours-face.d.ts(7,14): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-dial/ngx-material-timepicker-dial.component.d.ts(17,14): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-dial/ngx-material-timepicker-dial.component.d.ts(18,14): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-minutes-face/ngx-material-timepicker-minutes-face.component.d.ts(12,14): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-minutes-face/ngx-material-timepicker-minutes-face.component.d.ts(13,14): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-period/ngx-material-timepicker-period.component.d.ts(14,14): error TS2709: Cannot use namespace 'DateTime' as a type.
> node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-period/ngx-material-timepicker-period.component.d.ts(15,14): error TS2709: Cannot use namespace 'DateTime' as a type.

Am i doing something wrong or there is a bug in lib? Also i am using:
-"@angular/core": "^7.2.13",
-"node": ">= 4.2.1"

**Comment by Agranom** [comment]
Hi,
Maybe you use some settings that affect your build, Ivy renderer on or something like that ?

**Comment by Agranom** [comment]
any updates ?
