### ISSUE TITLE
[Feature] Standalone clockface/dail

### ISSUE THREAD

**Issue by chancezeus** [Agranom/ngx-material-timepicker#151]
Hi,

I just saw the update you have pending (3.2.0) and made a local build for testing. The package is really nice but I have one question:
I have a project build on @angular/material and I'm in need of a nice time input similar to your clockface. However because of certain requirements I'd like to be able to embed the "plain" component (without the ngx-material-timepicker overlays/backdrop/open+close logic) into a custom modal. Would it be possible to also make the various underlying components that make up the current "ngx-material-timepicker" component as either a single standalone/inline component or as they are now (i.e. seperate components and it'll be up to the dev to combine them correctly)...

Keep up the good work!

**Comment by Agranom** [comment]
Hi,
So you just want plain html/css, am I right?

**Comment by chancezeus** [comment]
I'd want direct access to the underlying clock face(s) and input field without the "modal" wrapper, this could be a standalone component (only the modal "body") or simply export these components, that way I can use the dialog/modal feature of `@angular/material` (or any other framework) instead of your custom implementation...

**Comment by Lavoiect** [comment]
> I'd want direct access to the underlying clock face(s) and input field without the "modal" wrapper, this could be a standalone component (only the modal "body") or simply export these components, that way I can use the dialog/modal feature of `@angular/material` (or any other framework) instead of your custom implementation...

Do you ever figure this out?

**Comment by Agranom** [comment]
Done. Update to v5.3.0.
