### ISSUE TITLE
CRITICAL: Module resolution fails with 3.2.0

### ISSUE THREAD

**Issue by jpike88** [Agranom/ngx-material-timepicker#152]
@Agranom  ngx-material-timepicker@3.2.0 has broken module resolution... unable to use it.

https://stackblitz.com/edit/angular-basic-tutorial-uzvp8s

Switching back to ngx-material-timepicker@3.1.0 works

**Comment by jpike88** [comment]
Also wouldn't hurt if you could merge the angular 8.0 PR too

**Comment by Agranom** [comment]
@jpike88 Fixed. Update to v3.2.1
