### ISSUE TITLE
[Feature] internationalization - ngx-material-timepicker

### ISSUE THREAD

**Issue by rajaramtt** [Agranom/ngx-material-timepicker#154]
Please try to implement  Internationalization and localization for ngx-material-timepicker.

**Comment by Agranom** [comment]
Yes. This will be the next feature

**Comment by paultobey** [comment]
Any idea on the schedule for internationalization support?

**Comment by Agranom** [comment]
I'll try to implement it during next two weeks. But I am not promise )

**Comment by Agranom** [comment]
It seems like there are 4 types of displaying time: Persian, Arabic, Chinese and standart. Am I right ?

**Comment by paultobey** [comment]
For time display, Persian looks like US to me, 'hh:mm:ss tt'. Of course AM/PM would be localized.

The same appears to be the case for most Arabic speaking countries, although some use slightly different formats.

China seems to use 'tt hh:mm:ss' for Simplified, 24-hour format for Traditional.

The .NET/Windows list of culture-based time formats is my only direct experience!

https://www.basicdatepicker.com/samples/cultureinfo.aspx

**Comment by Agranom** [comment]
Guys, already implemented i18n, so you can test it on v5.0.0.

**Comment by paultobey** [comment]
I've grabbed the code but haven't had a chance to look at it yet. Is the intent that module.setLocale(loc) is the method of changing behavior? Is this dynamically adjustable (user changes her profile settings, for example, within the Angular app), without reloading?

**Comment by Agranom** [comment]
No, It's not dynamic. Is it better to make it dynamically ?

**Comment by enzoberger** [comment]
Hi, I have added autoFormat. If autoFormat is true, for the countries 'us|uk|ph|ca|au|nz|in|eg|sa|co|pk|my|sg|za' the timePicker will use 12h clock and 24h for the rest of the world. If you create the branch autoFormat and give me right to push, I will contribute to your work.

**Comment by paultobey** [comment]
For whatever reason, our customers expect to select the language and date/time settings "dynamically" (it makes QA easier, I think). That's **not** an indication that everyone's customers expect that, however. Just something for consideration.

**Comment by Agranom** [comment]
I'll leave it like static for now.
