### ISSUE TITLE
NgxTimepickerFieldComponent - inconsistent timepickerTime output

### ISSUE THREAD

**Issue by LintYourLife** [Agranom/ngx-material-timepicker#155]
Providing `14:52` as defaultTime timepickerTime value is `14:52`. But after period change it's `2:52 pm`.

Workaround
```typescript
    @ViewChild('timepicker') private timepicker: NgxTimepickerFieldComponent;

    public ngAfterViewInit(): void {
        this.timepicker.registerOnChange(async () => {
            const { hour: periodHour, minute } = this.timepicker;
            const period = await this.timepicker.period$.pipe(first()).toPromise();
            const hour = period === 'PM' ? periodHour + 12 : periodHour;

            this._value = DateTime.fromObject({ hour, minute }).toLocaleString(DateTime.TIME_24_SIMPLE);
        });
    }
```

**Comment by Agranom** [comment]
You are not suppose to change period with 24-hours format. Have you provided format `[format]="24"` ?

**Comment by LintYourLife** [comment]
I used none ("12" by default isn't it?)
Wouldn't be easier to use Input/Output in 24h (`13:37` instead of `1:37 pm`)?

**Comment by Agranom** [comment]
you should set format to 24 if you want output to be in 24-hours format

**Comment by LintYourLife** [comment]
I mean it will be easier to support both without conversions:
```html
<ngx-timepicker-field
    #timepicker
    [defaultTime]="defaultTime"
    [format]="format"
></ngx-timepicker-field>
```
```typescript
// Case 1 (12-hours)
defaultTime = '13:37'
format = 12
// displays: 1:37 pm
// timepickerTime = '13:37'
```
```typescript
// Case 2 (24-hours)
defaultTime = '13:37'
format = 12
// displays: 13:37
// timepickerTime = '13:37'
```

**Comment by Agranom** [comment]
I added `format` property to define format of timepicker. It's redundant to detect time format by value

**Comment by LintYourLife** [comment]
I agree but I'm talking about Input and Output value (not displayed text).

I will be easier to have it in single format (24-hours format). Value is for developer.

**Comment by OyvindWN** [comment]
It is **not redundant** to detect time format by value.
My project is to be used by clients from different countries, which differ in their use of the 12- and 24-hour format. I don't know which I need before my API has told me, so I need to bind the `format` property to a TBD value.

Or is there a different way to tell the `ngx-timepicker-field` what format to use?
