### ISSUE TITLE
Clock Hand looses touch in right to left otientation 

### ISSUE THREAD

**Issue by JaynsVerdammt** [Agranom/ngx-material-timepicker#157]
Hi,
A issue occured in my applicationbif I use right to left otientations. The Hand Center isnt in the Center of the clokcface anymore, but anywhere way left. Is there a way to avoid this issue? 

Best regards, 
Jens

**Comment by Agranom** [comment]
Hi,
look at the https://github.com/Agranom/ngx-material-timepicker/issues/110, is it the same issue?

**Comment by Agranom** [comment]
Any updates?
