### ISSUE TITLE
export 'ɵɵdefineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by gazinfine** [Agranom/ngx-material-timepicker#158]
Had no issues with time picker on our angular 6 appliction until this week. Now are seeing build issues 

WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 231:51-69
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

also saw errors related to Angular 7 being a pre-requisite for this plugin. 

Is angular 6 no longer supported?

**Comment by LintYourLife** [comment]
Same on `7.2.13`

**Comment by RaphaelMalth** [comment]
Same error here.

**Comment by thisiszoaib** [comment]
Same here with Angular 7. Just stopped working after the latest updates for Angular 8. I tried switching to previous versions but this seems to have affected them as well.

**Comment by jgonzalez4gcp** [comment]
Same here with Angulart 7. Rollback to version 3.0.3 and seems to work fine

**Comment by gazinfine** [comment]
i rolled back to 2.9 and made relevant change in app.module and it is working now. Would be good to get a fix in the next version so can ensure on the latest. thanks.

**Comment by BryanFrancotte** [comment]
Is there a work around that doesn't involve rolling back the version of angular ?
Because I'm using other component that are not supported anymore on old version of angular...
Thanks for the answer ;)

**Comment by LintYourLife** [comment]
@BryanFrancotte You don't have to downgrade angular. Just downgrade `ngx-material-timepicker` to `3.2.2`

**Comment by BryanFrancotte** [comment]
@LintYourLife okay thank you for the work around ;)

**Comment by Agranom** [comment]
Your app doesn't work with that warning? Because this issue relates to angular https://github.com/angular/angular/issues/30413

**Comment by nasiUduk** [comment]
I have the same issue running on Angular 7.2.13. Tried rolling back to 3.2.2 and 3.0.3 but still didnt solve the problem

**Comment by Agranom** [comment]
This is caused, because library were built with angular 8. I guess, I will downgrade it to 7 and rebuild package. This should fix that warning

**Comment by nasiUduk** [comment]
> This is caused, because library were built with angular 8. I guess, I will downgrade it to 7 and rebuild package. This should fix that warning

Update: I was able to work around it with @angular-devkit/build-angular version 0.6.5. For me it was only happening for --prod build with Angular 7, it's fine after downgrading the devkit

**Comment by Agranom** [comment]
Guys, I've recompiled lib with v7 and warning is gone. So v3.3.1 is fixed version for you. The next one v4.0.0 is for angular 8

**Comment by Judejvlr** [comment]
> Guys, I've recompiled lib with v7 and warning is gone. So v3.3.1 is fixed version for you. The next one v4.0.0 is for angular 8

ThxU!
