### ISSUE TITLE
Safari / Iphone rendered incorrectly in child component

### ISSUE THREAD

**Issue by dmbaker90** [Agranom/ngx-material-timepicker#159]
I created a StackBlitz to reproduce: https://stackblitz.com/edit/angular-rdzdxx

On Safari and Iphone, the UI is stuck inside the Angular child component.  On Android and PC it works correctly.  Any ideas why?

![iphone](https://user-images.githubusercontent.com/5949263/59525377-0232e900-8e8b-11e9-939e-5b7e64983892.jpg)

**Comment by Agranom** [comment]
I guess it is somehow related to `height: 300px` in the css file. Can you rid of that in your code?
