### ISSUE TITLE
Control time picker popup

### ISSUE THREAD

**Issue by somzJosf** [Agranom/ngx-material-timepicker#16]
Is there any way I can control the pop up of the time picker dialog. It gets pop up every time when I click the input box. I am planning to add an icon beside the input box to show/ hide the dialog. ( just like the basic angular material date picker. https://material.angular.io/components/datepicker/overview)
![image](https://user-images.githubusercontent.com/8610715/43171585-fc038a02-8ffe-11e8-99a3-cc1ac9a54975.png)

**Comment by Agranom** [comment]
@somzJosf The feature is implemented. Update to 2.4.0 . Check out the demo with examples how to use it

**Comment by somzJosf** [comment]
That's great. Thanks you!.
