### ISSUE TITLE
export 'ɵɵdefineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by hamidabdul1994** [Agranom/ngx-material-timepicker#161]
WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 231:51-69
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 290:56-74
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
i ｢wdm｣: Compiled with warnings.

**Comment by hamidabdul1994** [comment]
WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 231:51-69
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 290:56-74
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
i ｢wdm｣: Compiled with warnings.

**Comment by sargr86** [comment]
You can try to downgrade to version 3.0.0.

**Comment by Agranom** [comment]
closes, because of duplicated https://github.com/Agranom/ngx-material-timepicker/issues/158
