### ISSUE TITLE
WARNING in ./node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 

### ISSUE THREAD

**Issue by nicolaskobelt** [Agranom/ngx-material-timepicker#164]
Hi! I have a problem with your TimePicker, i didn't understand what's the error. You can help me?

`import { NgxMaterialTimepickerModule } from 'ngx-material-timepicker';`
`imports: [NgxMaterialTimepickerModule]`

<img width="658" alt="Screen Shot 2019-06-29 at 21 11 23" src="https://user-images.githubusercontent.com/17903423/60390687-78059a00-9ab2-11e9-9f30-311d1e97dd49.png">

**Comment by Agranom** [comment]
Hi. Look at this issue https://github.com/Agranom/ngx-material-timepicker/issues/158

**Comment by nicolaskobelt** [comment]
Works with downgrade, i'm angular 7 and 3.2.2 of time picker. Thanks!
