### ISSUE TITLE
Bug when add Output event for ngx-material-timepicker

### ISSUE THREAD

**Issue by harleyleung711** [Agranom/ngx-material-timepicker#165]
Thank you for this beautiful library.
I read the document and saw that ngx-material-timepicker has some Output event so I implement it which linked to my function
My code below:
![image](https://user-images.githubusercontent.com/52494675/60594941-3d607200-9dd0-11e9-9886-cc2be74fd2ee.png)

So the emitter works, I received what I want and log it to the console.
But the UI is buggy. The reproduce steps:
1. Click the input and choose a time
2. The time is auto filled to the input but then disappears right away

The video for the bug reproduction:

https://drive.google.com/file/d/1bqcYZnqlVAnQzeE-yWPcqHX2OIjJJZQG/view?usp=sharing

**Comment by Agranom** [comment]
I guess, for you case would be better to use timeSet output. Because it returns value. Have you tried?
