### ISSUE TITLE
Can't use ngx-timepicker-field in module

### ISSUE THREAD

**Issue by charleshtrenholm** [Agranom/ngx-material-timepicker#166]
Hello,

I'm trying to use your `<ngx-timepicker-field>` in my code but it is not getting recognized when I put it in my html. I have imported NgxMaterialTimepickerModule into my app.module.ts and have made sure that I have the most recent version of your app installed. Any Ideas? Thanks in advance!

Here is the error I get when I try to put ngx-timepicker-field into my component: 

![Screen Shot 2019-07-07 at 2 29 33 PM](https://user-images.githubusercontent.com/42216351/60774130-8ceeb880-a0c4-11e9-8215-6c6b63417132.png)

**Comment by leochen0818** [comment]
Hi @charleshtrenholm , did you import NgxMaterialTimepickerModule in your module?
