### ISSUE TITLE
Typos preventing NGX-Material-Timepicker from working properly

### ISSUE THREAD

**Issue by TheChrisRoss** [Agranom/ngx-material-timepicker#168]
Hi there,

Moments ago, I downloaded/installed your package for my Angular 7 project and noticed that it would not compile afterwards.  The error led me to a problem with importing and referencing defineInjectable from @angular/core.  

I spotted the typo 'ɵɵ' located in front of the import and various references in 3 files;

1. node_modules/ngx-material-timepicker/fesm2015/ngx-material-timepicker.js
2. node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js 
3. node_modules/ngx-material-timepicker/bundles/ngx-material-timepicker.umd.js

Upon removing the ɵɵ's everything was able to compile and work just fine.

Hope this helps.

Chris

**Comment by Agranom** [comment]
Hi @TheChrisRoss 

Which version have you installed?

**Comment by TheChrisRoss** [comment]
I installed version 4.0.0

**Comment by Agranom** [comment]
v4.0.0 is for angular 8+. You have to install the previous one. Look at the CHANGELOG.md
