### ISSUE TITLE
Bugs when dynamically change format with NgxTimepickerFieldComponent

### ISSUE THREAD

**Issue by leochen0818** [Agranom/ngx-material-timepicker#170]
I found a bug when dynamically change `format` with `NgxTimepickerFieldComponent`.

And I add a [PR](https://github.com/Agranom/ngx-material-timepicker/pull/167) to fix it.

**Comment by Agranom** [comment]
Thanks, I'll publish it soon

**Comment by Agranom** [comment]
Done
