### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by codeunifier** [Agranom/ngx-material-timepicker#173]
Hi! I'm getting the following error when trying to import module into my app:

Error:
Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at ngx-material-timepicker.js:231
    at Module../node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js (ngx-material-timepicker.js:238)
    at __webpack_require__ (bootstrap:83)
....

**Comment by Zozu** [comment]
Yeah, I got this too. Seems, like there is an issue in build. Module tries to import something strange from '@angular/core' ('ɵɵdefineInjectable').
![image](https://user-images.githubusercontent.com/8209198/61447749-3c941800-a95a-11e9-8246-ba02869bab9f.png)
I changed it to 'defineInjectable' and now it works.
It's need to fix this in the repo.

**Comment by Zozu** [comment]
Seems like this error related to the updates in Angular v8. '**defineInjectable**' is deprecated and changed to '**ɵɵdefineInjectable**'. This change breaks backward compatibility with lower versions of Angular.
Seems like you use (and me too) Angular version lower than 8.
Angular has closed issue for this case: https://github.com/angular/angular/issues/30413

**Comment by Zozu** [comment]
Just use version 3.3.1 of "ngx-material-timepicker" if you get this error.

**Comment by Agranom** [comment]
It might help https://github.com/Agranom/ngx-material-timepicker/issues/158
