### ISSUE TITLE
timepicker-field requests

### ISSUE THREAD

**Issue by jbthomps** [Agranom/ngx-material-timepicker#174]
1) I have not been able to find how to style the focus under the individual input fields.
![Screen Shot 2019-07-17 at 1 05 39 PM](https://user-images.githubusercontent.com/7220419/61399370-a4336000-a893-11e9-84d8-4c21fb82c112.png)

2) It seems that the input setup cannot have an empty default.  Any attempt to give it an empty default seems to default it to 12:00 (in the 24 hour clock).

3) When disabling the field, it does keep the user from interacting with it, but there's no visual cue that the field is disabled.

**Comment by Agranom** [comment]
I've got your points and will fix it soon

**Comment by Agranom** [comment]
1. You can set focus through /deep/ selector in your css
2.  Fixed in v4.0.2
3. Added css class `ngx-timepicker--disabled` in v4.0.2
