### ISSUE TITLE
wrong initial display with ngmodel in loop

### ISSUE THREAD

**Issue by caribou71** [Agranom/ngx-material-timepicker#18]
I have an ngfor to display different shecdule event in each day of the week, all the display has the last info inside but when I change one of them the value is save properly in the model.

so it is only at the initialization where the error occur..if I use value instead of ngmodel, the initial value is correct for all input others then the ngmodel one...but I need the 2way binding.

<ng-container class="location-list-item" *ngFor="let schedule of day.schedule">
	<div *ngIf="(schedule.time <= 1500)" class="location-list-item">
			<div class="24hr-example">
				<input placeholder="" aria-label="" name="time3" [value]="schedule.time2" [ngxTimepicker]="fullTime2" [format]="24"  readonly>
				<ngx-material-timepicker #fullTime2></ngx-material-timepicker>
				<input placeholder="" aria-label="" name="time2" #time2="ngModel" [(ngModel)]="schedule.time2" [ngxTimepicker]="fullTime" [format]="24"  readonly>
				<ngx-material-timepicker #fullTime></ngx-material-timepicker>
			</div>
	</div>
</ng-container>
   
i'm using angular 6.0.9

**Comment by caribou71** [comment]
I checked..i don't have value in the input with ngmodel.

my case is different because it is in a for loop...so the name of the input and timpepicker are the same for each..probably that's why initially they all have the same info in it

**Comment by Agranom** [comment]
have you tried to set an unique name for each timepicker in the loop ?

**Comment by caribou71** [comment]
i tried that [ngxTimepicker]="fullTime{{i}}" but it doesn't work..compilation error

cant name the timepicker like this either #fullTime{{i}}

**Comment by caribou71** [comment]
can you make an example with a loop and ngmodel associate with it that is working...i'm pretty sure you'll see the same behavior

**Comment by Agranom** [comment]
I created `tests = [{time: "11:15 am"}, {time: "10:10 am"}];` array

and this loop
`<div " *ngFor="let test of tests">
                        <input [ngxTimepicker]="default" [(ngModel)]="test.time">
                        <ngx-material-timepicker #default></ngx-material-timepicker>
</div>`

And I have different values in the input. And after changing the time, each input still have its own value

**Comment by Agranom** [comment]
Thanks for advice, I'll try it !
