### ISSUE TITLE
expose services

### ISSUE THREAD

**Issue by mackelito** [Agranom/ngx-material-timepicker#186]
I would like to be able to subscribe to when the time has been set and dialog closes.

Something like:
```
this.pickerService.closed().subscribe((pickedTime: string) => {
  //Do some magic
})
```

Would be really useful :)

**Comment by Agranom** [comment]
There is an output `timeSet` in `ngx-material-timepicker`. You can listen to is. Check the doc

**Comment by mackelito** [comment]
Yeah but there might be other scenarios where a subscription would be handy.. eg nesting subscriptions :)

**Comment by Agranom** [comment]
I am not sure it is neccessary )
