### ISSUE TITLE
export 'ɵɵdefineInjectable' was not found in '@angular/core' (angular6)

### ISSUE THREAD

**Issue by zhuhang-jasper** [Agranom/ngx-material-timepicker#187]
I know this problem is not new. Its because the library was build in v7.

So, how about users with Angular 6? :D

Which old version of this library was built in v6?

**Comment by Agranom** [comment]
you can use the previous version of the timepicker (v3.3.1)

**Comment by benwinding** [comment]
I'm getting this issue with angular 8, **ngx-material-timepicker@4.0.2**

But v3.3.1 works though :+1:

**Comment by Agranom** [comment]
I guess, it's duplicated by https://github.com/Agranom/ngx-material-timepicker/issues/158
