### ISSUE TITLE
[Feature] Date/Moment Integration

### ISSUE THREAD

**Issue by dancUB** [Agranom/ngx-material-timepicker#188]
Given that this component fills a major hole in the Angular Material library, it would be great if it could support taking and setting time on Date or Moment objects. 

For example, I would find it very helpful to be able to bind the value of a Material datepicker to this timepicker, abstracting away the need for [concatenation, setters or other strategies](https://github.com/moment/moment/issues/2221).

**Comment by Agranom** [comment]
This lib doesn't use Moment. It uses `luxon`. So you can set time as `string` or as `DateTime`
