### ISSUE TITLE
Option to modify component color

### ISSUE THREAD

**Issue by lwazevedo** [Agranom/ngx-material-timepicker#19]
please include the possibility of using all colors of angular material.

thank you.

**Comment by Agranom** [comment]
It's the separate component and I don't want it to be dependent of Angular Material. The only thing I can do with coloring the timepicker is to set colors by yourself

**Comment by Agranom** [comment]
@NTXAggie Hi. Stay tuned with this issue https://github.com/Agranom/ngx-material-timepicker/issues/71
