### ISSUE TITLE
how to initialize the value from the code

### ISSUE THREAD

**Issue by irnel** [Agranom/ngx-material-timepicker#191]
I have seen the examples in the official documentation and in the demos.
I have seen the examples in the official documentation and in the demos.
I would like to change the value of the input from ts code, something like
@ViewChild ('input', {static: false}) input: any;
input.setValue (value).

Right now I have it this way

             `<mat-form-field>
                  <input matInput placeholder="closing time" 
                      aria-label="default time"
                      [ngxTimepicker]="mondayClosingTime"
                      [value]="mondayCtValue"
                      formControlName="mondayCT" readonly>

                  <ngx-material-timepicker #mondayClosingTime></ngx-material-timepicker>
                </mat-form-field>`

This way works well, as long as it has a valid value. But it could be the case that there is no value.

![Sin título1](https://user-images.githubusercontent.com/13103773/64274053-95227300-cf10-11e9-979c-32f68b815cf4.png)

So I want that if there is no value, do not put undefined in the input, and the placeholder will be displayed. 

Maybe it can be solved via html or by code.

**Comment by Agranom** [comment]
Why do you use ViewChild for changing the value? You can change it via reactive forms, like this:
`this.form.get('mondayCT').patchValue(value)`

**Comment by mrthetkhine** [comment]
I also face the same situation, When I patch form value  eg 10:00 00, the control change to 10:00 am which is correct, but reactive form value is still 10:00 00, not 10:00 am.

**Comment by Agranom** [comment]
Timepicker is not a convertor. It returns appropriate time once you set it via the picker
