### ISSUE TITLE
Font styles get overriden by ngx-material-timepicker font styles

### ISSUE THREAD

**Issue by somzJosf** [Agranom/ngx-material-timepicker#20]
When I add ngx-material-timepicker to one of my component, it overrides my entire application font styles to a bolder font.  
And I could figure out it is someway related to `@import "~@angular/material/prebuilt-themes/indigo-pink.css";` which is a global setting in my styles.scss

**Comment by Agranom** [comment]
The timepicker couldn't override your styles, because of shadow dom. Your global styles are overrided by this `@import "~@angular/material/prebuilt-themes/indigo-pink.css";` . Try to set font explicitly in your styles.scss

**Comment by Agranom** [comment]
So you added mat-button to the timepicker as custom buttons?

**Comment by Agranom** [comment]
I use this timepicker with angular material theme and it doesn't override styles.

**Comment by somzJosf** [comment]
No, the mat-button I added was a separate independent control in the page.

**Comment by Agranom** [comment]
Can you look at dev tools and and figure out which styles make your buttons bolder?

**Comment by somzJosf** [comment]
I couldn't figure out what makes the styles overriding. But I have a workaround for that issue now, which is explicitly add font styles in the component which uses the timepicker. I am not particularly sure, if this is to do with ngx-timepicker. Hence closing the issue.

**Comment by dniadzelka** [comment]
I faced with the same issue. So, according to [material typography](https://material.angular.io/guide/typography) I'm using such font:
`<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">`

But ngx-material-timepicker use the same font Roboto, but different thickness:
`https://fonts.googleapis.com/css?family=Roboto:400,500,700`

So in this case it overrides material styles. Any ideas how to solve it?

**Comment by Agranom** [comment]
@dniadzelka try to override it in your global styles

**Comment by ZobbL** [comment]
Maybe it's a dumb question, but why download the font at all?
I don't want to make that request, if I don't use this font. 

Your style relies on Roboto, but has sans-serif as a fallback. In my opinion it's up to the user, to provide the correct font-settings in the global styles.
This makes it even easier to integrate the timepicker in the project-design, because the user does not have to worry about it

However: great work with the timepicker :)

**Comment by Agranom** [comment]
You are right. I'll include this option to theming #71
