### ISSUE TITLE
[bug] 12 hr format, fully disabled clockface displayed when minimum is around PM hours and no value selected yet.

### ISSUE THREAD

**Issue by igalklebanov** [Agranom/ngx-material-timepicker#202]
**Current situation:** selection modal just opens with a fully disabled hours clockface. User has to change to PM manually just to be able to select hour.

**Expected behavior:** open modal with PM hours clockface when min is around PM hours and there's no value selected already.

**Bug repro:**
min = 3:00 PM
value = undefined
-> open selection modal

**Comment by Agranom** [comment]
Done (v5.1.0)
