### ISSUE TITLE
[suggestion] default time should be set by default to min time (if present and there's not value set) instead of 12:00AM.

### ISSUE THREAD

**Issue by igalklebanov** [Agranom/ngx-material-timepicker#203]
**current behavior:** No value set yet, minimum time set to something after 12:00AM, i.e. 12:05AM. modal is opened with an enabled OK button.
user presses the button without selecting an hour / minute. component attempts to set an errorneous time and throws an error.

**expected behavior:** user opens the modal, and default value is minimum time (12:05AM), as 12:00AM isnt even selectable. even if he doesn't select hour / minute, and just presses OK, he doesn't get an error, and the time set is valid everytime.

**Comment by Agranom** [comment]
You've just read my thoughts )

**Comment by Agranom** [comment]
Done (v5.1.0)
