### ISSUE TITLE
[suggestion] editable dial's input font color should be customizable via datepicker theme.

### ISSUE THREAD

**Issue by igalklebanov** [Agranom/ngx-material-timepicker#204]
**current behavior:** dial input text is always light blue unless overriden via css, since theme object has no parameter for editable dial's input text color.

**expected behavior:** editable dial input font color should be customizable via datepicker theme object.

**repro:**
enableKeyboardInput = true
open modal

**Comment by Agranom** [comment]
Done (v5.1.0)
