### ISSUE TITLE
[Suggestion] Clear Button

### ISSUE THREAD

**Issue by Timelord-Victorious** [Agranom/ngx-material-timepicker#205]
It would be nice to have a (optional) button to be able to easily clear/reset the input value.

Something similar to the defaul htmlt timepicker:

![](https://i.stack.imgur.com/vnxdO.png)

I already searched the docs but couldn't find a way to to it.

**Comment by monstrege** [comment]
<input type="search" would help, but I can't find the way to handle the click event properly...

**Comment by Agranom** [comment]
You can implement it. Just add clear icon button with css and set time value to `null`. Like this:
HTML
`<button (click)="resetTime()">cler_icon</button>`
TS
`resetTime() { this.timepilerFieldValue = null }`
