### ISSUE TITLE
How to enable only Hour picker?

### ISSUE THREAD

**Issue by PirunSeng** [Agranom/ngx-material-timepicker#208]
Great work!

I wonder if we can enable only Hour picker. I have two different fields. One stores hour and minute which is fit for the library. While the other one stores only hour, meaning it'll be always something like 1:00, 2:00, or 3:00, etc, note the minute is always 00.

Some might say, why not just use select options if you only need to choose hour. But I just want to try to use the library so it's more consistent.

**Comment by PirunSeng** [comment]
Right, thanks, I can fire the hourSelected event. But I cannot find a way to close the modal in the docs. I can close it manually with JS. I just wonder if there is something already exists in the library to be used :)

**Comment by Agranom** [comment]
Yeah, It's not documented. However, you can do it manually. Like this:
`@ViewChild('timepicker') timepicker: NgxMaterialTimepickerComponent;

this.timepicker.close()
`

**Comment by PirunSeng** [comment]
It seems to have an issue assign the value to input after closing it, the value is not filled to the input. It's kind of clicking outside the model or cancel button.

```
<input [ngxTimepicker]="timepicker" matInput readonly>
<ngx-material-timepicker #timepicker (hourSelected)="hourSelected($event)"></ngx-material-timepicker>

@ViewChild('timepicker') timepicker: NgxMaterialTimepickerComponent;

hourSelected(value) {
  this.fromTimePicker.close();
}
```
Note: I tend to write template and component code together just to make it short and easy to read.

**Comment by Agranom** [comment]
Try another method `setTime()`

**Comment by PirunSeng** [comment]
I suppose you mean `timeSet()```. I've tried this, but the event only fires when user click OK button.

**Comment by Agranom** [comment]
No, I meant `setTime`. Because `timeSet()` is an event listener, but `setTime` is a method

**Comment by PirunSeng** [comment]
Many thanks, I can now close model and set the time after choosing hour. Yet, user can still first choose to set Minute before Hour. For current workaround, I can think of setting none pointer-events to the minute element.
However, it may be good to have more properties, in the library, like, hourOnly or minuteOnly, amOnly, pmOnly, etc.
Anyway, great work and nice support! Thanks :)

**Comment by Agranom** [comment]
I'm afraid that library becomes framework like ))

**Comment by PirunSeng** [comment]
Hi @Agranom, version 5.1.1 got this error:
```
Property 'setTime' does not exist on type 'NgxMaterialTimepickerComponent'
```
version 5.0.0 works fine.

**Comment by Agranom** [comment]
I see. Will fix it in the next release. Sorry for that

**Comment by PirunSeng** [comment]
Worry not! Waiting for it...

**Comment by Agranom** [comment]
I've added `hoursOnly` property, so you don't need to call `setTime` anymore )
