### ISSUE TITLE
[bug] modal doesn't disable body scrolling.

### ISSUE THREAD

**Issue by igalklebanov** [Agranom/ngx-material-timepicker#210]
**current behavior** - modal opens, and you can still scroll body.

**expected behavior** - act like @angular/material / CDK's dialogs, and not allow scrolling anywhere within the application, except for current modal.

**bug repro**
force body to overflow.
open component's modal.
scroll away.

**Comment by igalklebanov** [comment]
try to remove  :host { overflow: hidden } css rule in app.component.scss and wrap everything in app.component.html in a <div></div>.

afaik, @angular/cdk appends overlay containers to body. mat-datepicker in touchUi mode is opened just like a mat-dialog, and scrolling is disabled, regardless of your templates' structure or css.

**Comment by Agranom** [comment]
tried `mat-datepicker` in touchUi mode here https://material.angular.io/components/datepicker/overview and scrolling is enabled

**Comment by Agranom** [comment]
You can disable scrolling by yourself at least.
