### ISSUE TITLE
Time format issue with ngx-timepicker-field

### ISSUE THREAD

**Issue by Dona278** [Agranom/ngx-material-timepicker#211]
I have different issues with ngx-timepicker-field and 24 format:
- If I set a time like "07:25" the input shows "7:25":
![image](https://user-images.githubusercontent.com/10567243/64816762-a9b5d980-d5a8-11e9-8d1e-6e563957fa70.png)
then if I blur the input it shows correct value:
![image](https://user-images.githubusercontent.com/10567243/64817058-45474a00-d5a9-11e9-9863-f15ef441f5ad.png)
- If I set a time like "07:00" the input not shows "00":
![image](https://user-images.githubusercontent.com/10567243/64817310-df0ef700-d5a9-11e9-9add-6b37b9672b0f.png)

**Comment by Agranom** [comment]
I'll check

**Comment by Dona278** [comment]
Hi @Agranom! Have you news about this issue? Thanx

**Comment by Agranom** [comment]
Hi. Yes. I’m preparing a bunch of fixes. So it will be fixed in the nearest release (~in a week)

**Comment by Agranom** [comment]
I believe it's fixed. Update to v5.2.0

**Comment by Dona278** [comment]
Hi @Agranom, unfortunately the more serious issue isn't fixed. The format of the time with one digit (the first point of this issue) seems to be correct because even if I write / choose the time and then I blur the input the displayed value remain the same.
The second point of the issue still persist:
![display_value_error](https://user-images.githubusercontent.com/10567243/66293891-f78fda00-e8e7-11e9-90ca-39ff48d672f2.gif)

**Comment by Agranom** [comment]
I see. Will check it

**Comment by Agranom** [comment]
Fixed. Check it pls

**Comment by Dona278** [comment]
@Agranom perfect thank you! 
Now there is only one imperfection: it shows "12" and "0" correctly but minutes shows only 1 digit
![image](https://user-images.githubusercontent.com/10567243/66732967-354bb000-ee5e-11e9-9683-b311242b50f2.png)
If I blurred the input it shows "00"
![image](https://user-images.githubusercontent.com/10567243/66732984-4399cc00-ee5e-11e9-879b-e42aa4b093ed.png)
Would you like that I open a new issue?

**Comment by Agranom** [comment]
Yes, please. Create a new issue, I'll close this one
