### ISSUE TITLE
Not work angular 5 - format 24h

### ISSUE THREAD

**Issue by anaaChacon** [Agranom/ngx-material-timepicker#212]
Good I have an ionic 3 project with angular 5 version and the following happens to me, I have read in the issue that the latest version of this plugin is only compatible with angular 8 but I cannot update it to that version, the point is that I need this picker in 24h format compatible with angular 5, do you know of any other than the same result? I have also tried to download version 1.1.2 and it works correctly but not with the result I expect, which is the 24h format.

Thank you

**Comment by Agranom** [comment]
You can format you result to 24-hours format by `moment`. 
Something like this:
`moment(result, 'hh:mm a').format('HH:mm')`

**Comment by Agranom** [comment]
You can fork it and downgrade to angular 5

**Comment by anaaChacon** [comment]
Thanks! How can I downgrade it to angular 5? Os easy?

**Comment by Agranom** [comment]
I guess the best way is to move ngx-material-timepicker folder into your project and fix errors )

**Comment by Agranom** [comment]
Have you tried?
