### ISSUE TITLE
ngx-material-timepicker custom theme

### ISSUE THREAD

**Issue by mateusz-sawit** [Agranom/ngx-material-timepicker#218]
Setting custom theme via [ngxMaterialTimepickerTheme] directive on ngx-material-timepicker stopped working in version 5.1.1. 
Downgrading to 5.1.0 and it works fine.
You can find it on your templates site - https://agranom.github.io/ngx-material-timepicker/ - custom theme is nothing different than common theme and custom values are not applied.

**Comment by Agranom** [comment]
I see. Will fix it

**Comment by Enngage** [comment]
+ 1, encountered same issue

**Comment by Agranom** [comment]
Fixed.
