### ISSUE TITLE
No component factory found for NgxMaterialTimepickerContentComponent

### ISSUE THREAD

**Issue by steven274** [Agranom/ngx-material-timepicker#219]
Error when using with angular 8

![Screen Shot 2019-09-19 at 17 27 03](https://user-images.githubusercontent.com/7889676/65236429-c13e1680-db02-11e9-8fcc-3a638116f5b6.png)

**Comment by danielwojcik** [comment]
same here after upgrade from 4.0.2

**Comment by Astrofyziky** [comment]
Same here, with Angular 8 using timepicker version 5.1.1

![image](https://user-images.githubusercontent.com/14111071/65260083-6937ed80-dacb-11e9-8637-46f4a6c00b05.png)

I get a module not found error when adding NgxMaterialTimepickerContentComponent to entryComponents:
![image](https://user-images.githubusercontent.com/14111071/65259653-a18afc00-daca-11e9-969c-c018b393bc46.png)

Code in HTML:
![image](https://user-images.githubusercontent.com/14111071/65260217-a1d7c700-dacb-11e9-8746-189b84bbdf71.png)

**Comment by Agranom** [comment]
Try to use v5.1.0 till I fix that

**Comment by kevinjh07** [comment]
Same error with NgxMaterialTimepickerContentComponent here, Angular 8.
No problem using v5.0.0.

**Comment by Agranom** [comment]
Check please is there `ngx-material-timepicker-content.component.d.ts` in your `node_modules` path:
`ngx-material-timepicker/src/app/material-timepicker/components/ngx-material-timepicker-content.component` ?

**Comment by Astrofyziky** [comment]
Yes, that file does exist within that folder. This is with version 5.1.1, and 5.1.0 (which gives me the same error as 5.1.1).

![image](https://user-images.githubusercontent.com/14111071/65288948-68747b00-db0e-11e9-8bf9-a23dd9399182.png)

**Comment by Agranom** [comment]
could you provide an example ? Because I cannot reproduce it

**Comment by Agranom** [comment]
And try to remove and install again

**Comment by Astrofyziky** [comment]
I was able to figure it.  In my particular case it had to do with lazy loading.  It's not enough to add it to the imports of the components module, it also has to be added to the routing module

![image](https://user-images.githubusercontent.com/14111071/65338714-694df100-db90-11e9-95c9-e352a0a970af.png)

**Comment by tuoitrexuquang** [comment]
i got same issues with "ngx-material-timepicker": "5.1.1", "@angular/core": "8.0.0" version.

**Comment by Agranom** [comment]
I guess it's resolved. Otherwise it could be reopened.

**Comment by julienboulay** [comment]
This issue is not resolved and should be reopened. Same as @tuoitrexuquang , I need to add NgxMaterialTimepickerModule to the root module of my app.
This import in the root module should not be required and we should be able to import the module in a lazy module of the app.

**Comment by w0jcik** [comment]
same issue here - does not work in lazy module (ng8.2.9)

**Comment by Agranom** [comment]
Okey, I'll check it

**Comment by Agranom** [comment]
I've made some investigation and found out the similar issue on the angular repo.
https://github.com/angular/angular/issues/14324
In short, Entry components follow the same rules as providers in lazy loaded modules and they are only visible inside lazy loaded module. So you need to import module into `app.module`

**Comment by srukshan** [comment]
Check this Solution!
[Click Here](https://gist.github.com/srukshan/163b07d9913df281bd34f6cea8eb2334)

**Comment by samirthakare** [comment]
![image](https://user-images.githubusercontent.com/66155360/83320611-b9746b80-a266-11ea-95d8-cfbabab734c1.png)

get same error while using time picker with angular8.

**Comment by Agranom** [comment]
@samirthakare import module into your `AppModule`
