### ISSUE TITLE
[Feature] Custom buttons in ngx-timepicker-field

### ISSUE THREAD

**Issue by yl-endress** [Agranom/ngx-material-timepicker#220]
According to the samples of https://agranom.github.io/ngx-material-timepicker/ the ngx-material-timepicker supports custom buttons.

`          <ngx-material-timepicker #timepickerWithButtons [cancelBtnTmpl]="cancelBtn"
                                             [confirmBtnTmpl]="confirmBtn"></ngx-material-timepicker>
            <ng-template #cancelBtn>
                <button style="margin-right: 10px;">Cancel tmpl</button>
            </ng-template>
            <ng-template #confirmBtn>
                <button>Confirm tmpl</button>
            </ng-template>`

It would be nice if the ngx-timepicker-field could support the same functionality, especially the same button handling!

**Comment by Agranom** [comment]
Hi.

There is already implemented custom buttons for `ngx-timepicker-field`. Read the doc please

**Comment by yl-endress** [comment]
I am sorry, i am still using the old version 3.3.1. Looks like it does not support it. Anyway - thanks for your feedback!
