### ISSUE TITLE
IE 11 and Edge issue

### ISSUE THREAD

**Issue by shiningkiru** [Agranom/ngx-material-timepicker#222]
Time picker not working on IE11 and Edge. When we click on input box popup opens but when we select time then it shows invaid date message on input.

**Comment by AdditionAddict** [comment]
Per SO question https://stackoverflow.com/questions/58057134/ngx-material-timepicker-not-working-on-ie-and-edge

 > I downgraded the timepicker version to 4.0.2 now it work fine both in IE and Edge.

**Comment by Agranom** [comment]
I'll check it and try to fix

**Comment by aalmajanob** [comment]
Dear Agranom,

  First of all, thanks very much for this great component, we are using it in our PRoyect and it works great.

  Any ETA for this bug fix?


  Regards,

**Comment by Agranom** [comment]
Will try to check it on these weekends

**Comment by Sampath-Lokuge** [comment]
Hi @Agranom 
Any feedback on this issue? Thanks for the great component!

**Comment by Jithesh-Menon** [comment]
Hi @Agranom 
Can we expect fix for this issue in the upcoming release?

**Comment by Jithesh-Menon** [comment]
> Per SO question https://stackoverflow.com/questions/58057134/ngx-material-timepicker-not-working-on-ie-and-edge
> 
> > I downgraded the timepicker version to 4.0.2 now it work fine both in IE and Edge.

Hi @AdditionAddict,
I tried this one. But when we populating the time picker through code, if we are setting the default time as "5:00", the minute section renders as "MM".

**Comment by Jithesh-Menon** [comment]
Hi @Agranom,
Any comments on this issue?

Thank you.

**Comment by Agranom** [comment]
Hi guys. I'm trying to find PC with windows to debug it. Because I don't have edge and IE

**Comment by Sampath-Lokuge** [comment]
@Agranom I hope this will help you. It has free tier too. https://azure.microsoft.com/en-us/services/virtual-desktop/

**Comment by Agranom** [comment]
@Sampath-Lokuge thanks, I'll try

**Comment by Agranom** [comment]
Guys,
After debugging I've figured out that there is an issue with `luxon` library and IE supporting.
Timepicker works in Edge.
Here is the link that might help you to resolve your issue. https://moment.github.io/luxon/docs/manual/matrix.html

Please let me know whether you manage to handle or not.

**Comment by Agranom** [comment]
The issue is resolved. Update to the latest version (v.5.4.0).
