### ISSUE TITLE
[defaultTime]="'06:00 AM'" property returning null ngx-timepicker-field 

### ISSUE THREAD

**Issue by sreekanth47** [Agranom/ngx-material-timepicker#226]
I'm using ngx-timepicker-field  for picking time. In my application, I've start time and end time along with a submit button. when it  loaded , even though time picker is showing 6 am , when I click submit button , picker returns null for both start time and end time. The picker returns correct values if I change time values for both start time and end time.This happens when on load and I didn't change picker values and click on submit button.
below is my code
<ng-container matColumnDef="StartTime">
                          <th mat-header-cell *matHeaderCellDef> Start Time </th>                          
                            <td mat-cell *matCellDef="let element;let row=index">                                
                              <ngx-timepicker-field #default controlOnly=false   [(ngModel)]="element.startTime" name="starttime"
                              #starttime="ngModel" (ngModelChange)="onCheck(row)" required
                              [ngClass]="{'err': row==errorRow}" (keypress)="checkFormat($event, element.startTime)"
                              ></ngx-timepicker-field>
                          </td>                          
                        </ng-container>
I didn't get why it returns null instead of default time? if I change values picker returns correct values

**Comment by Agranom** [comment]
Hi. Sorry for the late answer. Do you get `null` right after initialization ?
