### ISSUE TITLE
why now is child of body? better when it was child of ngx-material-timepicker.

### ISSUE THREAD

**Issue by Jorge-Dacal** [Agranom/ngx-material-timepicker#227]
Hi,

In version 5.0.0 when you use it, it is created as a child of ngx-material-timepicker in the component that use it, then you can use different styles depending the component that use it.

![5 0 0 child of ngx-material-timepicker](https://user-images.githubusercontent.com/32701664/65829927-deb17400-e2aa-11e9-97b3-3c6d465c2fcf.jpg)

Now when is created, is a child of the body, not the component, then you cannot use different styles in different components, and also you loose any id or class that you add to it.

![5 1 1 child of body](https://user-images.githubusercontent.com/32701664/65829938-ea9d3600-e2aa-11e9-8b95-55c6e0c4fcd5.jpg)

As you can see in the image, now is a child of the body and it has broke my style. (Or at least I don't know how to do it to give my style to your timepicker with different style depending on the component that is using it).

Thanks for your component.

Best regards,
Jorge

**Comment by Agranom** [comment]
I've got your point. I'll add possibility to set a custom class name, so that you can customize it in your global styles.

**Comment by amoscatelli** [comment]
Please Agranom, consider reverting this behaviour to the previous one.
It's not only a matter of theming, it's a matter of cleaner code.

I am using SCSS rules and I want to theme ONLY timepickers opened in my custom angular component (for example):

:host ::ng-deep ngx-material-timepicker {
}

**Comment by Agranom** [comment]
Appending the component to the body resolves issues with `overflow:hidden` parent's element. I've provided directive for theming, why don't you use it?

**Comment by Jorge-Dacal** [comment]
> I've got your point. I'll add possibility to set a custom class name, so that you can customize it in your global styles.

It could be fine and for me this solve my issue.

**Comment by Jorge-Dacal** [comment]
> Appending the component to the body resolves issues with `overflow:hidden` parent's element. I've provided directive for theming, why don't you use it?

I'm not using it because you are using primary color for all pieces and I have 3 different colors in my component.

Also, i'm using custom buttons styles and I don't know if they are going to use correctly the styles that are defined in my component if is a child of the body. I know that this has a simply solution because I can add this styles to the body, dirty but it works.

As I said in the last message, I think that if you pass all the classes, we could solve all this issues adding our styles to the main styles in body and using the appropriate class.

**Comment by Agranom** [comment]
Added property `timepickerClass`
