### ISSUE TITLE
ngx-timepicker-field with form fields

### ISSUE THREAD

**Issue by Kat9876** [Agranom/ngx-material-timepicker#228]
Hi i wrote some code in angular 7 using ngx-timepicker-field (v3.3.1) and when the input fields for hours and minutes are empty , the form input does not change (I guess the luxon js file throws an error saying invalid numeric input and the form field is not set).
So if the value in the ngx-timepicker-field is 10:15 pm and i remove the value so it shows HH:MM pm the input form field is still 10:15 pm.
Is it possible to set the input form field to null if an error is thrown ?

**Comment by Agranom** [comment]
Hi. I guess it's already not possible for your version of the timepicker. I'd recommend you to update your project to angular 8 and use the latest stable timeoicker

**Comment by Kat9876** [comment]
Hello
thanks for the quick reply. 
Is there a way to keep track of the inputs to <ngx-timepicker-field >?
like log it in the console ?

**Comment by Agranom** [comment]
what exactly do you want log into console ?
