### ISSUE TITLE
0 added automatically on minutes

### ISSUE THREAD

**Issue by Mradmedamine** [Agranom/ngx-material-timepicker#229]
![image](https://user-images.githubusercontent.com/12666919/66139397-a4c0d480-e600-11e9-90d3-7c371a86af6c.png)
When I type any number for example '3' on the minutes it becomes 03. 
If I want to enter 30 I won't be able

![image](https://user-images.githubusercontent.com/12666919/66139537-e81b4300-e600-11e9-96fe-062e20e867f3.png)

**Comment by Dona278** [comment]
I have the same issue

**Comment by Agranom** [comment]
I know. I gonna fix it tomorrow

**Comment by Agranom** [comment]
Fixed in v5.2.0

**Comment by Mradmedamine** [comment]
@Agranom  That was solved for these type of inputs with arrows, In my case I have simple inputs like this to be able to copy paste time easily

![image](https://user-images.githubusercontent.com/12666919/66383006-82420900-e9bc-11e9-8f0c-9aba7b802af2.png)

same behaviour. It is not working properly !
I thought solving that will solve this but it figures out that it is not the case.

**Comment by Agranom** [comment]
How to reproduce it? I'm typing minutes and it works
