### ISSUE TITLE
time formatted automatically while typing

### ISSUE THREAD

**Issue by Mradmedamine** [Agranom/ngx-material-timepicker#233]
as described the issue of formatting while typing is still there 
I was typing 8:3 => it becomes 8:03 before I finish typing
![image](https://user-images.githubusercontent.com/12666919/66407129-f7c5cd80-e9ec-11e9-93da-f87d98da624d.png)

solution is in the ngxTimePicker Directive (input) = onInput should become (change)

**Comment by Agranom** [comment]
Do you see this bug on the demo page?

**Comment by Mradmedamine** [comment]
I made my input field editable. I want to be able to set up time manually or using the timepicker. 
There I have the problem. Although everything works fine the binding between the value and the timepicker the only issue is what I mentioned.

` <input matInput [ngxTimepicker]="pmEndTP" [format]="24" [disableClick]="true"
                                       formControlName="pmEndTime" min="11:00"/>
                                <ngx-material-timepicker-toggle matSuffix
                                                                [for]="pmEndTP"></ngx-material-timepicker-toggle>
                                <ngx-material-timepicker #pmEndTP></ngx-material-timepicker>`

**Comment by Agranom** [comment]
Fix is available in v5.2.1
