### ISSUE TITLE
[Feature] Times can be set with a Date object

### ISSUE THREAD

**Issue by davdaarn** [Agranom/ngx-material-timepicker#235]
I was wondering if something like below could be implemented?
```
writeValue(val: string | Date): void {
    if (val) {
        if (val instanceof Date) {
            val = moment(val).format('LT'); // Luxon equivalent
        }
        this.defaultTime = val;
    }
}
```
And I hate to ask, but if it's possible could this also be implemented in version `3.3.1`?

I'd be happy to try and impliment this myself and submit a pull request, but my angular is not that good and I'd be worried about poor implementation.

**Comment by Agranom** [comment]
Sorry, but I cannot update previous versions of the library. It's impossible

**Comment by davdaarn** [comment]
No worries, Thank you for the response.
