### ISSUE TITLE
[Feature] Set increments for TimePickerField

### ISSUE THREAD

**Issue by JoeyVinyard** [Agranom/ngx-material-timepicker#236]
What is the feasibility for setting increments for the TimePickerField.

i.e. if the increment were set to 30, then increasing the minute field would increase it by increments of 30.

Thanks

**Comment by Agranom** [comment]
I'll try to add some logic from `ngx-material-timepicker` to `ngx-timepicker-field`

**Comment by BL-SG** [comment]
Hey @Agranom,
I love the time picker and think it is very useful, I have taken a look at the docs (https://www.npmjs.com/package/ngx-material-timepicker) and I can see that time step ([minutesGap]="*") is still not a valid param is this still in the works? 

Thanks!

**Comment by Agranom** [comment]
Hi, @BL-SG ,
Haven't added yet, sorry

**Comment by Akpandita** [comment]
Hi @Agranom,
Loved this component, I wanted this increment feature in the field.
let me know if I can contribute to this project through this feature.

**Comment by Agranom** [comment]
Added `minutesGap` to `ngx-timepicker-field`. Pls update the lib to the latest version
