### ISSUE TITLE
12:00 always 12:00 PM even if AM button selected on ver: 5.2.0

### ISSUE THREAD

**Issue by felixunivers** [Agranom/ngx-material-timepicker#237]
On Angular 8 project, this code will always output 12:00 PM if time picker is at 12:00 regardless if AM or PM buttons are selected:

```
                                        // the event of new time / time change
  timeChange(newTimeE: string) {
    
    console.log(' --new time: ' + newTimeE);
    ...
  }
```
HTML template:
`
    <ngx-material-timepicker #timePicker (timeSet)="timeChange($event)"></ngx-material-timepicker>
`

Expected would be '12:00 AM' and '12:00 PM' respectively to the selected AM/PM options.

In fact, it appears now that the selection of the AM/PM options is not working properly even on other  selected time values. The timeChange() function does not receive the properly updated time in terms of the AM/PM values.

**Comment by Agranom** [comment]
could you provide the `input` setup as well

**Comment by felixunivers** [comment]
In my case I need to mix the time from the picker with other values, so I disabled the input:
```
        <!-- <input [ngxTimepicker]="timePicker"> -->
        <ngx-material-timepicker #timePicker (timeSet)="timeChange($event)"></ngx-material-timepicker>
```
and mix the values in the timeChange function. When I enable the input the am/pm selection works correctly. Without the input the am/pm is not properly recognized in the timeChange function. 

Perhaps the solution is just to enable the input and make it invisible? 
But still, it would be nice to have the output to the function correct even without the input tag.

**Comment by Agranom** [comment]
try to add `type=hidden` for the input

**Comment by felixunivers** [comment]
That works OK. Appreciated.
