### ISSUE TITLE
In 24h format, click on 12H give 00H

### ISSUE THREAD

**Issue by jbbergy** [Agranom/ngx-material-timepicker#24]
Hi,

When 'format' is set to 24 and we click on 12h, the value is 00h.

**Comment by Agranom** [comment]
Hi. I see, I'll fix it

**Comment by Agranom** [comment]
Closed https://github.com/Agranom/ngx-material-timepicker/commit/d5c916649856a915335db9e9677219e708cc9ee7

**Comment by caribou71** [comment]
did you build this one? I still can see the error in 2.5.1

**Comment by caribou71** [comment]
and click on 00 gives an invalid date...you want me to open another issue?
