### ISSUE TITLE
[ngx-timepicker-field] Displayed value has one digit

### ISSUE THREAD

**Issue by Dona278** [Agranom/ngx-material-timepicker#241]
With `ngx-timepicker-field` if I set a model with value like `08:00` (or set from timecpicker) the displayed value is `8` for hours and `0` for minutes:
![image](https://user-images.githubusercontent.com/10567243/66787527-535bf380-eee4-11e9-9ba4-83fd8bae730e.png)
But if I blur the input the displayed values became `8` for hours and `00` for minutes
![image](https://user-images.githubusercontent.com/10567243/66787609-9fa73380-eee4-11e9-8ede-ab9ae3f98296.png)

**Comment by Agranom** [comment]
It should be fixed. Update to v5.2.2 and check please

**Comment by Dona278** [comment]
@Agranom this issue is fixed! Thank you, but it seems to be opened an old issue: it's hard to set time with keyboard input into field. Maybe related to #243?
