### ISSUE TITLE
Theme input is unknown

### ISSUE THREAD

**Issue by tobias-brunner** [Agranom/ngx-material-timepicker#242]
<ngx-material-timepicker #timepicker [theme]="stzhTheme" (timeSet)="setTime($event)"></ngx-material-timepicker>

results in:
compiler.js:2175 Uncaught Error: Template parse errors:
Can't bind to 'theme' since it isn't a known property of 'ngx-material-timepicker'.

**Comment by Agranom** [comment]
Which version do you use?

**Comment by tobias-brunner** [comment]
5.1.1


Von: Vitalii <notifications@github.com>
Gesendet: Dienstag, 15. Oktober 2019 12:51
An: Agranom/ngx-material-timepicker <ngx-material-timepicker@noreply.github.com>
Cc: Brunner Tobias (GeoZ) <Tobias.Brunner@zuerich.ch>; Author <author@noreply.github.com>
Betreff: Re: [Agranom/ngx-material-timepicker] Theme input is unknown (#242)


Which version do you use?

**Comment by Agranom** [comment]
update to the latest one

**Comment by tobias-brunner** [comment]
Thanks! That was it!

Von: Vitalii <notifications@github.com>
Gesendet: Dienstag, 15. Oktober 2019 16:57
An: Agranom/ngx-material-timepicker <ngx-material-timepicker@noreply.github.com>
Cc: Brunner Tobias (GeoZ) <Tobias.Brunner@zuerich.ch>; Author <author@noreply.github.com>
Betreff: Re: [Agranom/ngx-material-timepicker] Theme input is unknown (#242)


update to the latest one
