### ISSUE TITLE
Value exchange between TS code and template

### ISSUE THREAD

**Issue by felixunivers** [Agranom/ngx-material-timepicker#245]

**Comment by felixunivers** [comment]
Would you please provide a few examples on how to best pass time values from the time picker to the TS code - including the TS code portions? 

Perhaps you could add these examples to your : 
https://agranom.github.io/ngx-material-timepicker/

I would especially be interested in knowing how I can get immediate value change in a function on change in time picker of this directive:

```
	<ngx-timepicker-field #tzTimePicker
			      [format]="24"
			      [defaultTime]="'08:00'"
			      (timeSet)="timeChange($event)">
	</ngx-timepicker-field>

```
in this case I see no event triggered on the timeChange($event).

Thank you.

**Comment by Agranom** [comment]
I guess, the best way is to use [(ngModel)] or reactive forms approach for now
