### ISSUE TITLE
v3.3.1 Examples and documentation are wrong regarding using ngxMaterialTimepickerTheme directive

### ISSUE THREAD

**Issue by LyuboslavLyubenov** [Agranom/ngx-material-timepicker#246]
Using version 3.3.1 i found that `<ngx-material-timepicker [theme]="darkTheme" #timePicker></ngx-material-timepicker>` does not actually sets the theme (as stated in the website and the documentation).

Correct way of using it is:
`
<ngx-material-timepicker [ngxMaterialTimepickerTheme]="darkTheme" (timeSet)="onTimeSet($event)" #timePicker></ngx-material-timepicker>
`

**Comment by Agranom** [comment]
Yeah, you're right. I forgot about supporting the previous versions. Will change it in the readme

**Comment by LyuboslavLyubenov** [comment]
do you want me to create PR with fixed readme?

**Comment by Agranom** [comment]
updated readme
