### ISSUE TITLE
Ivy support

### ISSUE THREAD

**Issue by kz-dos** [Agranom/ngx-material-timepicker#247]
Any chance for Ivy support?
Getting error:
"The pipe 'async' could not be found!"

Any help appreciated.

**Comment by Agranom** [comment]
Haven't tried yet. But will check

**Comment by Agranom** [comment]
How did you get this error? Are you sure it's related to the timepicker lib ?

**Comment by kz-dos** [comment]
I got it off initialization of the TimePicker following the normal implementation.

The error was for the pipe async. I can try it again, and maybe get an example if that would help. For the time being I resorted to using an alternative but would rather use this repo.

**Comment by Agranom** [comment]
I've got other error with TimeParserPipe. And some UI bugs. But none with async pipe

**Comment by Agranom** [comment]
Fixed issues with Ivy.

**Comment by Coooi** [comment]
I'm facing exactly the same issue.
**ngx-material-timepicker:** v5.2.3
**angular-core:** 8.2.14
Hopefully it will work on Angular 9 when released.

**Comment by derSoerrn95** [comment]
running into the same error :/

    "ngx-material-timepicker": "^5.2.3",
    "@angular/core": "^8.2.14",
