### ISSUE TITLE
Minutes Gap on ngx-timepicker-field

### ISSUE THREAD

**Issue by WillGeller** [Agranom/ngx-material-timepicker#248]
Is it possible to have the <ngx-timepicker-field> components respect 30min interval gaps on the minute input? Similar to how you can set minutes gap on the main timepicker modal

**Comment by Agranom** [comment]
Not for now. However, it will be possible soon

**Comment by WillGeller** [comment]
@Agranom Awesome! Thank you for the most excellent component, I look forward to using the newer versions.

**Comment by eugene-gv2** [comment]
@Agranom Can you tell, when this feature will be available?

**Comment by Agranom** [comment]
In a month, but I'm not sure.

**Comment by TaqueriaChavezDev** [comment]
Any updates on this? Sorry to ask.

**Comment by Agranom** [comment]
Not for now. Sorry. Maybe next months

**Comment by a30001735** [comment]
Any updates on this :)

**Comment by Agranom** [comment]
not yet :(

**Comment by CypressBytesource** [comment]
Any updates on this?

**Comment by jacqueline91** [comment]
Any updates? The function would be so practical! :)

**Comment by braga83** [comment]
Any update on this? Thanks

**Comment by hiroimono** [comment]
Any update?

**Comment by anuskazw** [comment]
any update? :S

**Comment by Agranom** [comment]
Going to start working on it
