### ISSUE TITLE
[question] Cannot Get defaultTime

### ISSUE THREAD

**Issue by flippy16** [Agranom/ngx-material-timepicker#249]
I am using two timepicker for OpenHour and Close Hour, and I wanna check it, if it same it'll shows something. idk why It shows undefined for the deafultTime on the console when I log it, but if I log the timepicker object it shows there is a value on defaultTime

HTML code
`
<input matInput placeholder="Choose Here" aria-label="24hr format" [ngxTimepicker]="openHour" [format]="24" readonly>
<ngx-material-timepicker #openHour (timeSet)="checkCustomHour(openHour)"></ngx-material-timepicker>`

Method
`
checkCustomHour(openH: any, closeH: any) {
    console.log(openH, closeH);
    console.log('Open Hour ' + openH.defaultTime, 'Close hour ' + closeH.defaultTime);
  }
`

here's the log
[Log](https://imgur.com/a/M0wGiY0)

anyone can help me ?

**Comment by Agranom** [comment]
`checkCustomHour` expect 2 args, but you provide only one.

**Comment by flippy16** [comment]
Sorry my bad, but this is the actual one but is still doesn't work
`
checkCustomHour(openH: any) { console.log(openH); console.log('Open Hour ' + openH.defaultTime); }
`

I still can't get the value, i just confused, why the result is different between the object log and the defaultTime log. The object shows there is a value on the 'defaultTime' but when it undefined when i log it directly

**Comment by Agranom** [comment]
Why do you need the default time? I didn't get your purpose. You have actual time after setting it, why do you need the default one?

**Comment by flippy16** [comment]
Sorry for making you confused, but I am new for this, maybe i just confuse how to use it. I just wanna get the actual time after i set it, i've tried hourSelected and closed properties to get the selected  time. but i don't know how to get it through those properties. Would you like to explain it ?

**Comment by Agranom** [comment]
HTML
`<input matInput placeholder="Choose Here" aria-label="24hr format" [ngxTimepicker]="openHour" [format]="24" readonly> <ngx-material-timepicker #openHour (timeSet)="checkCustomHour($event)"></ngx-material-timepicker>`

TS
`checkCustomHour(time) {
   console.log(`actual time is - ${time}`
}`

I guess that is what you need

**Comment by flippy16** [comment]
It's still not working, well maybe i'll try in another way

**Comment by Agranom** [comment]
what did you get in `checkCustomHour(time) { console.log(actual time is - ${time} }` ?

**Comment by flippy16** [comment]
it getting error, actually it can't compile on ng serve. then i've changed it to 
`checkCustomHour(time) { console.log('actual time is' + time);}` and it shows  "actual time is undefined"
currently i am using 2 timepicker, and i wanna compare both and showing an error message if both time are same.

**Comment by Agranom** [comment]
I've just checked this code `<input matInput placeholder="Choose Here" aria-label="24hr format" [ngxTimepicker]="openHour" [format]="24" readonly> <ngx-material-timepicker #openHour (timeSet)="checkCustomHour($event)"></ngx-material-timepicker>`
and it works. Cope and paste it to html. and this one `checkCustomHour(time) {console.log(time)}` to TS

**Comment by flippy16** [comment]
yeah I've tried it before Thanks, i just wanna now how to compare if there are more than 1 time, actually my app is trying to make a schedule, and it's from A time to B time. I wanna compare exactly after B dialog is set, that's why I'm using (timeSet) to get that time. Hope you guys understand what I mean. 
Now I'm using a button to trigger the comparing function so it's not immediately checked, but after this button is clicked.
Thanks for your help till now, I really appreciate it :)

**Comment by Agranom** [comment]
`<input matInput placeholder="Choose Here" aria-label="24hr format" [ngxTimepicker]="openHour" [format]="24" readonly> <ngx-material-timepicker #openHour (timeSet)="onOpenHourSet($event)"></ngx-material-timepicker>`
`<input matInput placeholder="Choose Here" aria-label="24hr format" [ngxTimepicker]="openHour" [format]="24" readonly> <ngx-material-timepicker #closeHour (timeSet)="onCloseHourSet($event)"></ngx-material-timepicker>`

TS

`onOpenHourSet(time) { this.openTime = time} `
`onCloseHourSet(time) { this.closeTime = time} `
`compareTime() { this.openTime === this.closeTime} `

Is that what you need?
