### ISSUE TITLE
Null model value not rendered

### ISSUE THREAD

**Issue by Dona278** [Agranom/ngx-material-timepicker#252]
If I set a time with timepicker-field component and then I set to null the bound model value, the value is `null` correctly but the field display the old time.

**Comment by Agranom** [comment]
I'll check

**Comment by Agranom** [comment]
Should be fixed in v5.2.3. Check pls

**Comment by Dona278** [comment]
Solved! Thank you

**Comment by Jithesh-Menon** [comment]
@Dona278 ,
I have raised one issue.
https://github.com/Agranom/ngx-material-timepicker/issues/264

Could you please check whether you were facing the same issue? I tried upgrading the package, but it didn't help.
