### ISSUE TITLE
keyboard entry on ngx-timepicker-field

### ISSUE THREAD

**Issue by ristiisa** [Agranom/ngx-material-timepicker#254]
When field contents for is 02 and the contents are selected, typing 2 and 1 results in 22 and back to 02. Same happens when contents are 21 and trying 02 results back to 21.

Tested on the demo page (https://agranom.github.io/ngx-material-timepicker/)

**Comment by Agranom** [comment]
This is known issue (related to #243 ).  Will be fixed in the next release.

**Comment by Agranom** [comment]
could you check it now?

**Comment by Agranom** [comment]
Shoud be fixed in v5.2.3
