### ISSUE TITLE
Stop propagation event click

### ISSUE THREAD

**Issue by patricia-martinez-imatia** [Agranom/ngx-material-timepicker#26]
I am integrating the component in my application.
I have added a button that opens the popup and I want that when clicking on the input it does not open the popup but it allows to add the hour with keyboard.

I have tried to stop the propagation of the click event but it does not work. Any suggestions?

![hour](https://user-images.githubusercontent.com/32088627/43880622-803f22d0-9ba9-11e8-9c35-f4d1c8460c02.png)

**Comment by Agranom** [comment]
Have you added disableClick props on the input?

**Comment by Agranom** [comment]
Please let me know if my answer helped you
