### ISSUE TITLE
How to bind a time value between a property/variable of TS code and the template/view for: ngx-timepicker-field

### ISSUE THREAD

**Issue by felixunivers** [Agranom/ngx-material-timepicker#260]
This piece of code for "ngx-timepicker-field" from the example [here](https://agranom.github.io/ngx-material-timepicker/):    

    <div class="ngx-timepicker-field-example">
        <ngx-timepicker-field [defaultTime]="'11:11 am'"></ngx-timepicker-field>
    </div>

is what I want to use to work with some time values in my code.

From the provided examples or the documentation, it is not clear how to bind a TS/Angular property of e.g. name:  _tsTimeA_  to the template that allows the following:

1. If user changes time using the up/down arrows or by typing the hour or minute - _tsTimeA_ gets updated in the code.

2. If user changes time using the clock interface - _tsTimeA_ gets updated in the code

3. And reversely, if prop. _tsTimeB_ changes in the TS code, the _ngx-timepicker-field_ also changes in the view.

Would you be so kind and provide some examples for these scenarios for:
 - one way binding, 
 - two way binding, 
- and for passing time values via a click / key press or time change events ?

**Comment by jorgeizquierdo** [comment]
I have the same problem.

The NgxTimepickerFieldComponent component implements ControlValueAccessor. In that case should be work with a normal two way binding '[(ngModel)]="myVar"'.

But, for me, it set the value but doesn't read the new one when I change it.

In other way, I try to take the element with ViewChild and set manually the registerOnChange function, and it works. The problem is that I genearate multiple timepicker-field's dinamically and this solution is not valid for me.

**Comment by oveiskabuli** [comment]
i have the same issue

**Comment by Agranom** [comment]
I see. Will check it

**Comment by Agranom** [comment]
It works with reactive forms and with template-driven forms. [(ngModel)] works as well with two way binding.

I'll add `@Output` event to emit time once it's changed. Watch that issue https://github.com/Agranom/ngx-material-timepicker/issues/207

**Comment by felixunivers** [comment]
Thanks for the @Output timeChanged event.  
When you find a bit of time, it would be very useful - especially for beginners - to add a few more samples on the usage of the bindings and events in your sample page at: 
https://agranom.github.io/ngx-material-timepicker/
We all much appreciate your support, updates and the entire project.
