### ISSUE TITLE
Picker dialog opens behind material dialog

### ISSUE THREAD

**Issue by mtinnes** [Agranom/ngx-material-timepicker#263]
When using the time picker from within a material dialog (mat-dialog), the picker is lower in the z-index, and obscured by the parent dialog.

**Comment by Maurice22** [comment]
+1 Having exactly the same issue

**Comment by Timelord-Victorious** [comment]
+1 Having exactly the same issue

**Comment by Agranom** [comment]
Try to change z-index of timepicker
