### ISSUE TITLE
[question] Reset time picker back to HH:MM

### ISSUE THREAD

**Issue by Jithesh-Menon** [Agranom/ngx-material-timepicker#264]
Hi @Agranom ,

Thanks for developing a useful time picker control and handling 95% of the validations as well.

Any option to reset the time picker control back to "HH: MM" through code?

I'm using ngx-timepicker-field control 
(version - "ngx-material-timepicker": "^5.0.0")
<ngx-timepicker-field [format]="24"  [controlOnly]="true" #pickTime></ngx-timepicker-field>

Thanks in advance.

**Comment by Agranom** [comment]
Try to set timepicker value to null

**Comment by Jithesh-Menon** [comment]
> Try to set timepicker value to null

Hi @Agranom ,

I tried that as well. It didn't work for me.

**Comment by Agranom** [comment]
Try to update lib to the latest version

**Comment by Jithesh-Menon** [comment]
> Try to set timepicker value to null

Hi Agranom,

You mean set defaultTime property of the time picker as null?

**Comment by Agranom** [comment]
Not defaultTime. You should set `value` to null. I'd recommend to use FormControl or ngModel for it.`
`<ngx-timepicker-field [format]="24" [(ngModel)]="time" [controlOnly]="true" #pickTime>`
TS
`resetTime() { this.time = null }`

**Comment by Jithesh-Menon** [comment]
Hi @Agranom ,
I have tried this approach along with the latest version, but I am getting the error stating "Cannot read property 'split' of null".

**Comment by Agranom** [comment]
Are you sure you're using the latest version (5.2.3)? Because I've just tried and it works

**Comment by Jithesh-Menon** [comment]
Yes @Agranom . I am using the same version. But I am getting this error in Chrome.

**Comment by Jithesh-Menon** [comment]
Hi @Agranom , I am facing the same issue with the newly released version (5.3.0). Could you please check this issue.?

**Comment by Jithesh-Menon** [comment]
Hi @Agranom , Did you get a chance to look at this..? 
Thank you.

**Comment by Agranom** [comment]
I still cannot reproduce this issue. Could you provide a repository with usage, so that I can check it?

**Comment by KasunGamage** [comment]
any update on this?

**Comment by Jithesh-Menon** [comment]
@KasunGamage ,

Nope. I am still having this issue in my application.
