### ISSUE TITLE
Problem with Angular7

### ISSUE THREAD

**Issue by templth** [Agranom/ngx-material-timepicker#265]
Hello,

I try to use the library (version 4.0.2) with Angular7 but got this error:

```
ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at ngx-material-timepicker.js:231
```

Which version should work with Angular7?

Thanks for your help!
Thierry

**Comment by Agranom** [comment]
Hello. You should use version less then 4

**Comment by templth** [comment]
Thanks for your answer!
