### ISSUE TITLE
Question: Internationalization 

### ISSUE THREAD

**Issue by DepickereSven** [Agranom/ngx-material-timepicker#267]
In #154 you add the internationalization, but you also made it static. Would you consider changing it to dynamically? So if the user change the language we can update the timepicker.

**Comment by Agranom** [comment]
Yes, but later

**Comment by DepickereSven** [comment]
Any idea on an estimated ETA for this future?

**Comment by Agranom** [comment]
I don't know. Maybe a month

**Comment by hallowatcher** [comment]
any update on this?

**Comment by Agranom** [comment]
Not yet. Sorry. I'm a bit run out of time now. Will try in the next few weeks

**Comment by Dschuli** [comment]
Is there a chance to have the ngx-timepicker i18n aligned (automatically) with the Angular LOCALE_ID?

**Comment by Agranom** [comment]
Not for now, sorry
