### ISSUE TITLE
Question: How do I use the timepicker on a static page?  I want to show the clock on the page when it loads, not in pop up modal.  

### ISSUE THREAD

**Issue by Lavoiect** [Agranom/ngx-material-timepicker#268]

**Comment by felixunivers** [comment]
Try using:  {{ myTimePicker.open() }}  (use proper name of your time-picker).
If that does not work for you, you may need to do a few extra steps.
See here: [https://stackoverflow.com/questions/38088996/adding-script-tags-in-angular-component-template](https://stackoverflow.com/questions/38088996/adding-script-tags-in-angular-component-template)

**Comment by Agranom** [comment]
I guess it's solved
