### ISSUE TITLE
Time picker error if used with Luxon and time zone settings are changed to 'utc'.

### ISSUE THREAD

**Issue by felixunivers** [Agranom/ngx-material-timepicker#269]
I am using time-picker and Luxon API. If I configure Luxon settings to:

`Settings.defaultZoneName = 'utc;`

on 1st call time picker works normally. On subsequent calls, the time picker fails with this error:

> NgxMaterialTimepickerFaceComponent.ngfactory.js? [sm]:1 ERROR TypeError: Cannot read property 'time' of undefined
    at Object.eval [as updateDirectives] (NgxMaterialTimepickerFaceComponent.html:3)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:45258)
    at checkAndUpdateView (core.js:44270)
    at callViewAction (core.js:44636)
    at execEmbeddedViewsAction (core.js:44593)
    at checkAndUpdateView (core.js:44271)
    at callViewAction (core.js:44636)
    at execEmbeddedViewsAction (core.js:44593)
    at checkAndUpdateView (core.js:44271)
    at callViewAction (core.js:44636)

**Comment by Agranom** [comment]
Do you provide time in string or  in luxon format?

**Comment by felixunivers** [comment]
I am not providing time to the time picker in any way. Just using it as a GUI for user to select/enter time. Here is my template part:

```
<input [ngxTimepicker]="timePicker1" [disableClick]="true" type="hidden" readonly >
<ngx-material-timepicker #timePicker1 (timeSet)="timeChange($event)"></ngx-material-timepicker>
```

In my function:  ` timeChange(event) ` I read the time (comes as string) and convert it to milliseconds (ms). Further, I use these ms for various calculations and conversions using Luxon, plus other math, which has nothing to do with the time-picker.


The error gets generated when I click the button to open time-picker.
```
       <button mat-icon-button id="btnTimePicker1"
           matTooltip="Set time using a time-picker"
           (click)="timePicker1.open()"
       >
```

**Comment by Agranom** [comment]
I've just copied your code, but did'n see the error. I've set `Settings.defaultZoneName = 'utc';` in `AppComponent`

**Comment by felixunivers** [comment]
Thank you for double-checking. My project is quite intertwined with other components and I do not have time right now to try to isolate the issue. I just disabled the 'utc' changes on my project for now. So lets close the issue here for now and I'll be in touch once I get time to get to the bottom of it.
