### ISSUE TITLE
Option to disable selection of minutes

### ISSUE THREAD

**Issue by LoganDupont** [Agranom/ngx-material-timepicker#281]
I was wondering if there is an option where I can prevent users from switching to minutes modal. I tried to set `hoursOnly="true"` but this doesn't prevent the user from changing the minutes in the dial-container (header). I'm still able to navigate to the minutes modal by clicking on the minutes input field or by using my keyboard controls.

**Comment by Agranom** [comment]
Hi @LoganDupont ,
I will improve `hoursOnly` functionality and avoid switching to minutes

**Comment by satrent** [comment]
I'm using this as a work-around for now....

<ngx-material-timepicker (opened)="disableMinutes()" hoursOnly="true"></ngx-material-timepicker>

    public disableMinutes() {
        setTimeout(() => {
            let minutesControl  = document.getElementsByClassName('timepicker-dial__control')[1];
    
            if (minutesControl){
                minutesControl.setAttribute('disabled', 'true');
            }
        });
    }

**Comment by Agranom** [comment]
The issue is resolved. Update to the latest version (v.5.4.0).
