### ISSUE TITLE
How to change the buttons

### ISSUE THREAD

**Issue by Hiteple** [Agranom/ngx-material-timepicker#282]
Hi people, I didn't understand how to change the buttons on the timepicker template... even after finding it in the docs. Can someone provide an example for me please?
The docs specify this: 

cancelBtnTmpl: TemplateRef | Set if you want to change cancel button to your custom one.

So what do I have to pass in there?

**Comment by Agranom** [comment]
Hi @Hiteple ,
Please look at the demo page with an example https://agranom.github.io/ngx-material-timepicker/

**Comment by Hiteple** [comment]
Thank you man, I could do it after seeing that example

**Comment by imptingdesign** [comment]
Hey, 
I have a question regarding the buttons. 
I created a custom cancel button template. It closes the popup but with kind of a lag, slower than the original "cancel" button.
Any ideas? Thanks :)
This is my template:
`<ngx-material-timepicker [ngxMaterialTimepickerTheme]="darkTheme"
                                    [cancelBtnTmpl]="cancelBtn"
                                    (timeSet)="timeChanged($event)" #defaultValue>
                                    </ngx-material-timepicker>
                                    <ng-template #cancelBtn>    
                                        <button class="impting-timepicker-button">ABBRECHEN</button>
                                    </ng-template>`
