### ISSUE TITLE
[Feature] enable keyboard numbers instead of arrows or having to click the modal

### ISSUE THREAD

**Issue by pablolok** [Agranom/ngx-material-timepicker#283]
as like in the title, our clients ask to be able to type the numbers instead of having to use the mouse, i couldn't find any way to do it with the current implementation.

**Comment by Agranom** [comment]
Have you triend `ngx-material-timepicker-field` component?

**Comment by AdditionAddict** [comment]
> 
> 
> Have you triend `ngx-material-timepicker-field` component?

Is there a way to improve the keyboard functionality of the `ngx-material-timepicker-field` component?
If I tab into the field, say the hour field and type '11' instead '01' shows.
If I shift-tab and tab back into the field again typing '11' results in the expected '11'
