### ISSUE TITLE
[question] White boxes where time display should be

### ISSUE THREAD

**Issue by icemoon4** [Agranom/ngx-material-timepicker#284]
<img width="301" alt="Screen Shot 2020-02-05 at 3 02 40 PM" src="https://user-images.githubusercontent.com/14224020/73878570-c4733e00-4828-11ea-96d1-146df516e538.png">

See attached image. I'm not sure why it is showing the white boxes at the top instead of the selected time. Here is my HTML:
`<input [(ngModel)]="parameter.value.value" (ngModelChange)="parameter.value.value = $event" [ngModelOptions]="{standalone: true}"
                            placeholder = "Choose a time" [ngxTimepicker]="fullTime" [format]="24" aria-label="24hr format" readonly>
                            <ngx-material-timepicker #fullTime [enableKeyboardInput]="true"></ngx-material-timepicker>`

Not certain if this is a bug or if I have configured something incorrectly.
I am using version 3.3.1 because I am using Angular 7.

**Comment by Agranom** [comment]
Do you see any errors in the console?

**Comment by icemoon4** [comment]
> Do you see any errors in the console?

I do not

**Comment by icemoon4** [comment]
It has to be some CSS that's not loading correctly but I don't know what. When I change the font size from 50px to 20px, I can see the numbers, however they still have a white background and black text (unlike the examples). If there is a workaround that does not involve changing the timepicker component itself I would like to do that.

**Comment by Agranom** [comment]
I guess you override timepicker's styles. Could you check in dev tools what color is set to timepicker?

**Comment by icemoon4** [comment]
I ended up copying the timepicker-dial CSS to our semantic.css file and marked the elements as important. It seemed that our .ui.form input CSS was overriding the timepicker's styles. Thanks for the suggestion!
