### ISSUE TITLE
Can not limit time in range 09h00 pm - 06h00 am 

### ISSUE THREAD

**Issue by notHaiLuu** [Agranom/ngx-material-timepicker#286]
Hi everyone, 

**Requirement** limit the time in range 09h00 pm - 06h00 am. 

So as I expected, I set min value is 09h00 pm and set max value is 06h00 am. But it does not work correctly.

=> It's only support limit range from am - pm **not pm - am**

Help me please!!!

**Comment by Agranom** [comment]
Hi @notHaiLuu 
It's bug. I'll check it and fix

**Comment by Agranom** [comment]
This is not a bug. Your min time is `09:00 pm` which means time range from `1 am` to `9 pm` and your max time is `06:00 am` which is included in that time range

**Comment by LyuboslavLyubenov** [comment]
@Agranom Well its not a bug, because hours between 9h00 pm and 6h00 am are: 10pm 11pm ... 2am 3am ...
