### ISSUE TITLE
enableKeyboardInput not functioning 100%

### ISSUE THREAD

**Issue by Kerk1990** [Agranom/ngx-material-timepicker#287]
It works as expected and I can give the time from my keyboard but if I want to set the hours again after setting minutes and click on hours field than it disables for keyboard. If i want to select hours field  I have to use Tab to go on hours field to work again. So somehow a mouse click crashes the keyboard function.

**Comment by Agranom** [comment]
I'll check it

**Comment by Agranom** [comment]
Can you update to the latest version and check again pls

**Comment by pallaviShriya96** [comment]
Hi , I'm not being able to switch to hours tab back from the keyboard after coming to minutes field. Please help.
