### ISSUE TITLE
IE11: "Invalid Date" (ready solution)

### ISSUE THREAD

**Issue by patrykdawid** [Agranom/ngx-material-timepicker#288]
From version 5.0.0 the control does not work in IE11: "Invalid Date" is displayed in input.

After a long search, I was able to locate the problem.
A detailed description is here: https://www.csgpro.com/blog/2016/08/a-bad-date-with-internet-explorer-11-trouble-with-new-unicode-characters-in-javascript-date-strings/

You can also easily compare the operation on IE11 versus another browser (e.g. Chrome): http://jsbin.com/mehowehase/1/edit?html,js,console

It seems to me that the solution to the problem is to add `.replace(/\u200E/g,"")` to the end of the **formatTime()** method in **time-adapter.ts**. For security reasons, you can also add the same to the end of the **toLocaleTimeString()** method.

The solution is not invasive in any way, and allows you to use ngx-material-timepicker also on IE11 :)

BTW
Of course, we can also downgrade to version 4.0.2 (as they suggest here: https://stackoverflow.com/a/58057225), but I think nobody wants it? :)

**Comment by Agranom** [comment]
@patrykdawid thank you so much, it helped
