### ISSUE TITLE
hours:min display on left side, not enough room for the clock on right side

### ISSUE THREAD

**Issue by caribou71** [Agranom/ngx-material-timepicker#29]
im trying the timepicker on my mobile and the width of the timepicker is larger then the parent div.

parent div 358, timepicker 376...so the result is the clock is not completely displayed.

id prefer to have the hour:time on top of the clock like it is when I tried on desktop.

![timepicker_mobile_output](https://user-images.githubusercontent.com/41701447/44347458-de1e9b00-a465-11e8-85ef-eb5ea57238dc.PNG)

**Comment by Agranom** [comment]
What mobile device do you use? Did you try to open timepicker on another mobile? Because timepicker depends on a device orientation (landscape or portrait)

**Comment by Agranom** [comment]
It doesn't fit even with landscape orientation on your phone?

**Comment by caribou71** [comment]
it does fit in landscape...but not in portrait...users wont turn the phone just for that..the timepicker cant be larger then the screen...especially when you have another view with the hour:minute on top

**Comment by Agranom** [comment]
Yes, I know. I'm just trying to figure out what's the problem with your mobile. Because There some @media queries that should detect orientation and turn the timepicker accordingly to it

**Comment by Agranom** [comment]
Buy the way, do you have the same problem on my demo page ?

**Comment by caribou71** [comment]
I tried the demo on your phone...the first 3-4 on top and it was fine... the hour:minute display on top

**Comment by Agranom** [comment]
do you have this meta tag on you site/project ?
`<meta name="viewport" content="width=device-width">`

**Comment by caribou71** [comment]
no!..i just add it and ill see the next time we push the code on the server...I let you know

**Comment by Agranom** [comment]
So, did it help ?
