### ISSUE TITLE
mat-input should allow only numbers to enter

### ISSUE THREAD

**Issue by rnandakishan** [Agranom/ngx-material-timepicker#291]
hi,
mat-input should allow only number for the user to enter not characters.

And also form validation is not happening.
Please can anyone help me....???

**Comment by rnandakishan** [comment]
> 
> 
> hi,
> mat-input should allow only number for the user to enter not characters.
> 
> And also form validation is not happening.
> Please can anyone help me....???

**Comment by Agranom** [comment]
Hi
Can you provide your code snippet ?

**Comment by rnandakishan** [comment]
> 
> 
> Hi
> Can you provide your code snippet ?

please find the below code:
**<mat-list-item>
        <mat-form-field appearance="outline" class="timepickerClass full-width">
          <input [hidden]="true" [ngxTimepicker]="picker_name"  matInput [(ngModel)]="selectedTime"
            formControlName="time">
          <mat-icon class="addTime_icon" matPrefix></mat-icon>
          <ngx-timepicker-field aria-label="select time" tabindex="-1" id="time" [buttonAlign]="'right'" [(ngModel)]="selectedTime" formControlName="time">
          </ngx-timepicker-field>
          <ngx-material-timepicker aria-label="Time picker" #picker_name></ngx-material-timepicker>
          <mat-error *ngIf="form.get('time').hasError('required')">
            Time Required
          </mat-error>
          <mat-error *ngIf="!form.get('time').hasError('required') && form.get('time').hasError">
            Wrong Time format
          </mat-error>
        </mat-form-field>
      </mat-list-item>**

**Comment by Agranom** [comment]
Why do you use `[(ngModel)]` and reactive forms together?

**Comment by rnandakishan** [comment]
sorry....i need to remove that "ng-model"....
now,**type="number"** is not working...????

**Comment by Agranom** [comment]
try to apply https://www.npmjs.com/package/@uiowa/digit-only this directive to `input`

**Comment by rnandakishan** [comment]
> 
> 
> try to apply https://www.npmjs.com/package/@uiowa/digit-only this directive to `input`

no it is not working:
 <input [hidden]="true" [ngxTimepicker]="picker_name" inputmode="numeric"
          pattern="[0-9]*" digitOnly matInput 
            formControlName="time">

still it is taking default library "input".

**Comment by Agranom** [comment]
Input applyes string, so you cannot set it to `number`.
