### ISSUE TITLE
Cannot read property 'minutesGap' of undefined

### ISSUE THREAD

**Issue by vvision** [Agranom/ngx-material-timepicker#296]
Hello,

I'm having the following issue after upgrading to ``Angular 9`` and ``v5.4.0`` of ngx-material-timepicker.
``` 
core.js:3866 ERROR TypeError: Cannot read property 'minutesGap' of undefined
    at TimepickerDirective.set [as value] (ngx-material-timepicker.js:1350)
    at Object.ngOnChangesSetInput [as setInput] (core.js:19023)
    at setInputsForProperty (core.js:8846)
    at elementPropertyInternal (core.js:7933)
    at Module.ɵɵproperty (core.js:14184)
    at DatetimePickerRangeComponent_Template (datetime-picker-range.component.html:51)
    at executeTemplate (core.js:7562)
    at refreshView (core.js:7439)
    at refreshComponent (core.js:8569)
    at refreshChildComponents (core.js:7242)
    at refreshView (core.js:7485)
    at refreshDynamicEmbeddedViews (core.js:8505)
    at refreshView (core.js:7459)
    at refreshDynamicEmbeddedViews (core.js:8505)
    at refreshView (core.js:7459)
    at refreshComponent (core.js:8569)
```

Timepicker is used as follow.
```html
<input
  matInput
  placeholder="start time"
  aria-label="start time"
  [ngxTimepicker]="startTime"
  [format]="24"
  [value]="startTimeValue"
/>
<ngx-material-timepicker-toggle
  class="svg-color"
  [for]="startTime"
></ngx-material-timepicker-toggle>
<ngx-material-timepicker
  #startTime
  [defaultTime]="startTimeValue"
  [minutesGap]="5"
  (timeSet)="onChangeHourStartTime($event)"
></ngx-material-timepicker>
```
But ``[minutesGap]`` is defined on ``<ngx-material-timepicker>``. Am I missing something ?

**Comment by Agranom** [comment]
I haven't updated to ng9 yet. I have to check

**Comment by dkruchok** [comment]
The same issue "Cannot read property 'minutesGap' of undefined"
Angular 9.0.5
 ngx-material-timepicker  5.4.2

**Comment by Agranom** [comment]
Check pls whether `luxon` is installed or not

**Comment by vvision** [comment]
``luxon`` is installed in ``node_modules``.

**Comment by Agranom** [comment]
Updated to ng9 and it's still working. You can check on the demo page

**Comment by vvision** [comment]
OK. Thanks.
Might have something to do with the way we initialize the input.
We'll stay with ng8 until we figure out what's wrong.

**Comment by heorhii-zolotariuk** [comment]
> OK. Thanks.
> Might have something to do with the way we initialize the input.
> We'll stay with ng8 until we figure out what's wrong.

Hey, have you fix this issue ? Because i got the same error after update to ng 9.

**Comment by vvision** [comment]
> Hey, have you fix this issue ? Because i got the same error after update to ng 9.
Sadly we have not solved it. We have kept ng 8 since ng 9 would be a "nice have", but is not a top priority at the moment.

**Comment by Agranom** [comment]
@vvision try to use the latest version (v5.5.2)

**Comment by ti4luciano** [comment]
I have the same problem with angular9.
It is something related to [value].
When it is set it happens.
In my case the error is triggered here:
ngx-material-timepicker.js: 1102

**Comment by Agranom** [comment]
Try to bind `[value]` after `[ngxTimepicker]`. It seems that order is matter.

**Comment by ti4luciano** [comment]
The error does not happen after changing the order, however the value is not appearing in the field (I am putting the harded code value). I'll see if it's something in my code

**Comment by ti4luciano** [comment]
`    <input type="text" formControlName="chosenText" [format]="24" placeholder="{{placeholder}}" [ngxTimepicker]="picker" [value]="'23:11'" class="form-control" required>

    <ngx-material-timepicker (timeSet)="choose($event)" #picker></ngx-material-timepicker>`

**Comment by heorhii-zolotariuk** [comment]
> Try to bind `[value]` after `[ngxTimepicker]`. It seems that order is matter.

You are a lifesaver, that works for me.

**Comment by ti4luciano** [comment]
> > Try to bind `[value]` after `[ngxTimepicker]`. It seems that order is matter.
> 
> You are the lifesaver, change order works for me.

Can you put your order up?

**Comment by heorhii-zolotariuk** [comment]
<input matInput
                        #timePickerInput
                        readonly
                        placeholder="Choose a time"
                        [ngxTimepicker]="timeInput"
                        [value]="time"
                />

**Comment by ti4luciano** [comment]
It was the order, my problem now is the FormControl, without it the value works as standard. Thank you.

**Comment by Agranom** [comment]
@ti4luciano you don't need to bind [value] if you use angular forms

**Comment by ti4luciano** [comment]
> @ti4luciano you don't need to bind [value] if you use angular forms

Sorry, I'm not sure how to do this, could you exemplify me

**Comment by ti4luciano** [comment]
Thank you very much, it worked here. I put the value directly on the form and it worked.
Thanks again for everyone's help.
