### ISSUE TITLE
Angular 8/9

### ISSUE THREAD

**Issue by GlauberF** [Agranom/ngx-material-timepicker#298]
has support for Angular 8 and Angular 9

**Comment by Agranom** [comment]
Actually it’s supported by angular 8

**Comment by GlauberF** [comment]
angular 9 no?

**Comment by Agranom** [comment]
haven't checked yet

**Comment by Agranom** [comment]
@GlauberF have you tried it with angular 9?

**Comment by ikourfaln** [comment]
I have the same question 😉 ... waiting for confirmation with the support of Angular 9

**Comment by dark0ni** [comment]
seems to work in angular 9, no problems so far

**Comment by Agranom** [comment]
@dark0ni have you tried with Ivy as well?
