### ISSUE TITLE
Cannot read property 'meridiems' of undefined

### ISSUE THREAD

**Issue by GlauberF** [Agranom/ngx-material-timepicker#299]
Stackblitz: https://stackblitz.com/edit/angular-ngx-material-timepicker?file=src/app/app.component.html

**Comment by Agranom** [comment]
Requested page cannot be found

**Comment by GlauberF** [comment]
https://stackblitz.com/edit/angular-8-ngx-material-timepicker

**Comment by Agranom** [comment]
Have you tried on your own env? Because it doesn't work well on stackblits

**Comment by Agranom** [comment]
Not sure. I'll update to 9 angular this week and check

**Comment by atefbenbelgacem** [comment]
I have the same issue mentioned here and I've tried everything but it doesn't seem to be working !! I'm using the time-picker inside a MatDialog for editing and adding data to a  MatTable.
can you please help
