### ISSUE TITLE
Problem with import timepicker to shared.module.ts

### ISSUE THREAD

**Issue by maciejniedzielski** [Agranom/ngx-material-timepicker#3]
When I try to include timepicker to shared.module.ts I get this error:

![errortimepicker](https://user-images.githubusercontent.com/32812848/40358650-3f1d0726-5dc0-11e8-91f8-5a904671fd41.png)

`compiler.js:485 Uncaught Error: Unexpected value '[object Object]' exported by the module 'SharedModule'
    at syntaxError (compiler.js:485)
    at eval (compiler.js:15247)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15245)
    at CompileMetadataResolver.getNgModuleSummary (compiler.js:15132)
    at eval (compiler.js:15230)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15208)
    at JitCompiler._loadModules (compiler.js:34404)
    at JitCompiler._compileModuleAndComponents (compiler.js:34365)`

There is no problem when I import it to app.module and use in app.component, but this error occurs every time I try to "share" it. Could you please tell me what I'm doing wrong or fix it?

**Comment by Agranom** [comment]
It ocurres when you try to import Timepicker module to SharedModule ?

**Comment by maciejniedzielski** [comment]
It mean that I just want to put this module to SharedModule and use Timepicker in different module than app.module.ts

**Comment by Agranom** [comment]
Can you download you app to github and show me? Or just show me the way you use it please

**Comment by maciejniedzielski** [comment]
Unfortunately I can't upload app code anywhere, so I will try to explain it.

Important app dir structure:
-src
	-app
	 app.module.ts (root app module)
	         -shared
	          shared.module.ts (external libraries modules)

shared.module.ts has array named EXTERNAL_LIBRARIES_MODULES which includes modules of external libraries and this array is passed to shared.module.ts @NgModule imports array.

![zrzut ekranu deepin_wybierz-obszar_20180524125419](https://user-images.githubusercontent.com/32812848/40481687-73789a10-5f52-11e8-9d8a-3ac3646fb3bf.png)
![zrzut ekranu deepin_wybierz-obszar_20180524125330](https://user-images.githubusercontent.com/32812848/40481711-7d97c71e-5f52-11e8-8869-d1c6725281a6.png)

and this shared.module.ts is imported in app.module.ts
![zrzut ekranu deepin_wybierz-obszar_20180524125652](https://user-images.githubusercontent.com/32812848/40481771-b3b283c0-5f52-11e8-82c1-c1aba2b2424d.png)

If it is't clear and understandable enough let me know.

**Comment by Agranom** [comment]
Yes, it's clear enough. Which version of angular do you use?

**Comment by maciejniedzielski** [comment]
@angular/core 5.2.4 and @angular-cli 1.6.8

**Comment by Agranom** [comment]
Ok, i'll try to reproduce it by my own

**Comment by Agranom** [comment]
I found out the problem. That's because you try to export NgxMaterialTimepickerModule.**forRoot()**
forRoot() function returns ModuleWithProviders, but you need to export NgModule. So add NgxMaterialTimepickerModule.forRoot() to imports and NgxMaterialTimepickerModule to exports in SharedModule and it should work.

**Comment by maciejniedzielski** [comment]
I did like you said but now this error has occured:
![zrzut ekranu deepin_wybierz-obszar_20180524154742](https://user-images.githubusercontent.com/32812848/40489762-2a6b8b1c-5f6a-11e8-9da9-a9279cfdde13.png)
BUT, I forgot to mention (I think) very important fact: Modules are lazy loaded.
I also forgot to mention about one module in app tree

-src
&nbsp;&nbsp; -- app
&nbsp;&nbsp; app.module.ts
&nbsp;&nbsp; -- shared
&nbsp;&nbsp; shared.module.ts
&nbsp;&nbsp; -- user-management
&nbsp;&nbsp; user-management.module.ts

and in user.management.module.ts i've got these imports
![zrzut ekranu deepin_wybierz-obszar_20180524154805](https://user-images.githubusercontent.com/32812848/40490057-ea8db212-5f6a-11e8-8d5c-eec32cc96510.png)
Ultimately, I want to use timepicker in user-management.module.ts

Sorry for mistakes. Hope you will have some time to help me again :slightly_smiling_face:

**Comment by Agranom** [comment]
I guess I found the problem. I updated library to 1.1.2 try it now and tell me

**Comment by maciejniedzielski** [comment]
It works! Thank you so much for help! :smiley:
