### ISSUE TITLE
In 24 hour mode, Form values are inconsistent

### ISSUE THREAD

**Issue by davisb10** [Agranom/ngx-material-timepicker#30]
See : https://stackblitz.com/edit/angular-nhjmvd

When using Reactive Forms for the inputs:
1. If you manually set the form value and make a change, the value ends in ' 00'. Example '18:00 00'
2. If you start with a blank input and make a change, the value ends in 'AM' even in 24 hour mode. Example '6:30 AM', '22:30 AM', ...
3. In 24 hour mode, if the value is less than '10:00' it is not padded with a leading '0'. This makes it difficult to parse this input. '6:00' => 6 AM, '18:00' => 6 PM

**Comment by Agranom** [comment]
Okey, I'll check it

**Comment by Agranom** [comment]
> In 24 hour mode, if the value is less than '10:00' it is not padded with a leading '0'. This makes it difficult to parse this input. '6:00' => 6 AM, '18:00' => 6 PM

Why is it difficult? Can't you use just moment or something like that to parse it?

**Comment by Agranom** [comment]
Fixed. Update to the last version and try.

**Comment by davisb10** [comment]
Works great now! Thanks so much!

**Comment by davisb10** [comment]
When using the @Output() timeSet EventEmitter, the values are having the same issue. I have updated the stackblitz to test this.

**Comment by Agranom** [comment]
Okey, I'll fix it

**Comment by Agranom** [comment]
Fixed. Check please.

**Comment by davisb10** [comment]
Both ways now seem to be working as expected. Thanks again!
