### ISSUE TITLE
value from 00:00 to 00:59 ignores 24h format

### ISSUE THREAD

**Issue by Nephyron** [Agranom/ngx-material-timepicker#301]
I'm using version 5.4.1 and even if the timepicker is set to format=24 any time with 00 is replaced by 12

00:25 -> 12:25

**Comment by dark0ni** [comment]
can reproduce error in angular 9

**Comment by Agranom** [comment]
It's fixed. Update to v5.4.2

**Comment by soulshockers** [comment]
> It's fixed. Update to v5.4.2

Now it returns 24:xx instead of 00:xx

**Comment by Agranom** [comment]
@soulshockers you should set a proper locale

**Comment by RJesusTVD** [comment]
> > It's fixed. Update to v5.4.2
> 
> Now it returns 24:xx instead of 00:xx
Hello, 

Does it make sense? What if i want 00:30? It will change to 24:30? That time does not exist... only if it is a time span. 

Since it is a time picker, shouldn't we only be available to pick values from 00:00 to 23:59?

Thanks,

Ricardo Jesus
