### ISSUE TITLE
It's impossible to select 00:00 in 24 hours format since it returns 12:00 whe hour == 0

### ISSUE THREAD

**Issue by soulshockers** [Agranom/ngx-material-timepicker#302]
https://github.com/Agranom/ngx-material-timepicker/blob/bd8e29553890e25f54a0bc64b84f7094e5edfc7e/src/app/material-timepicker/services/ngx-material-timepicker.service.ts#L69

**Comment by dark0ni** [comment]
Duplicate from [301](https://github.com/Agranom/ngx-material-timepicker/issues/301) . It is part of same problem
