### ISSUE TITLE
When [enableKeyboardInput] is set true. The input accepts letters in version 5.4.1

### ISSUE THREAD

**Issue by mynameisx666** [Agranom/ngx-material-timepicker#305]
![image](https://user-images.githubusercontent.com/62140714/76622314-42cfa800-656c-11ea-89a6-bc9a6a773e12.png)

![image](https://user-images.githubusercontent.com/62140714/76622282-2b90ba80-656c-11ea-944d-3d277e6954d6.png)

**Comment by Agranom** [comment]
fixed in v5.4.3
