### ISSUE TITLE
24 hr format - showing 24:00 instead of 00:00

### ISSUE THREAD

**Issue by xubalachandran** [Agranom/ngx-material-timepicker#308]
Can I know how to fix this when ngx-material-timepicker is used

<input placeholder="24hr format" aria-label="24hr format" [ngxTimepicker]="fullTime" [format]="24"  readonly>
            <ngx-material-timepicker #fullTime></ngx-material-timepicker>

I think ngx-material-timepicker-field doesn't have issue

**Comment by xubalachandran** [comment]
version is 5.3.0

**Comment by xubalachandran** [comment]
We have issue in MS edge also

**Comment by RJesusTVD** [comment]
Hi,

Also having the same issue.

Since this is a time picker and not a time range picker, shouldn't we only be allowed to use values from 00:00 to 23:59 (in 24 format and not counting seconds for sake of simplicity)

Thanks

**Comment by RJesusTVD** [comment]
I have solved it using the proper locale.

example:
`
@NgModule({
	imports: [
            NgxMaterialTimepickerModule.setLocale("pt-PT")
        ],
	declarations: [],
	providers: [],
	exports: []
})
export class MyModule {}
`

**Comment by Agranom** [comment]
That's right. Proper locale will solve your issue.

**Comment by sglvladi** [comment]
Is there a reason that a local needs to be set for this to work? It used to worked fine in 3.3.1.

**Comment by Agranom** [comment]
And it works on linux as well. It started formatting in different way in windows OS after chrome and `luxon` last updates
