### ISSUE TITLE
enable keyboard input should select the input content upon focus and it should clear the content to enter first number

### ISSUE THREAD

**Issue by mynameisx666** [Agranom/ngx-material-timepicker#310]
enable keyboard input should select the input content upon focus and it should clear the content to enter first number
![image](https://user-images.githubusercontent.com/62140714/77229152-1bf61f00-6bc7-11ea-8566-d500790d7320.png)
When I type on the minutes/hour the highlighted should change

**Comment by Agranom** [comment]
Done
