### ISSUE TITLE
[FeatureRequest] Support nullable times

### ISSUE THREAD

**Issue by Nephyron** [Agranom/ngx-material-timepicker#311]
When setting the timepicker value to null/undefined, instead of having the portion of code:

return parsedTime.toISOTime({
            includeOffset: false,
            suppressMilliseconds: true,
            suppressSeconds: true
        }).replace(/\u200E/g, '');

throw because cannot call .replace of "null" it would be nice to have the timepicker field reset to the placeholde "hh":"mm"

**Comment by DaanTul** [comment]
Running into the exact same issue when cancelling the picker without selecting a time. Will see if I find the time to try and fix this

**Comment by DaanTul** [comment]
This seems to be an issue with the 24h format only.

When closing the picker with 24 format enabled it throws this error. With the 12h format this does not seem to be a problem. Maybe it is a difference in the implementation of `.toLocaleString` vs `.toISOTime` ?

**Comment by DaanTul** [comment]
I traced the problem to setting the default time when closing the picker when the format is 24h. I am however not sure why this occurs only for the 24h format.

**Comment by DaanTul** [comment]
This bug is also present on the demo page

**Comment by Agranom** [comment]
@Nephyron which version do you use?

**Comment by Silureth** [comment]
Hey! I have the same issue, with the new version 5.4.3.
On my office computer it still has 5.3.0 and with that it works.

**Comment by Agranom** [comment]
Fixed in v5.5.0

**Comment by Borizzio** [comment]
Hello,
The problem persist in v5.5.1

**Comment by vignesh-balaguru** [comment]
Hi,
I have installed ngx-material-timepicker v5.5.0. While I run "ng build --watch" command, I'm getting this kind of error is shown below.

ERROR in ../node_modules/ngx-material-timepicker/src/app/material-timepicker/components/ngx-material-timepicker-container/ngx-material-timepicker-container.component.d.ts:45:9 - error TS1086: An accessor cannot be declared in an ambient context.

45     set defaultTime(time: string);
           ~~~~~~~~~~~
../node_modules/ngx-material-timepicker/src/app/material-timepicker/components/ngx-material-timepicker-container/ngx-material-timepicker-container.component.d.ts:46:9 - error TS1086: An accessor cannot be declared in an ambient context.

46     get defaultTime(): string;
           ~~~~~~~~~~~
../node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-dial-control/ngx-material-timepicker-dial-control.component.d.ts:20:17 - error TS1086: An accessor cannot be declared in an ambient context.

20     private get selectedTime();
                   ~~~~~~~~~~~~
../node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-field/ngx-timepicker-field.component.d.ts:31:9 - error TS1086: An accessor cannot be declared in an ambient context.

31     set format(value: number);
           ~~~~~~
../node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-field/ngx-timepicker-field.component.d.ts:32:9 - error TS1086: An accessor cannot be declared in an ambient context.

32     get format(): number;
           ~~~~~~
../node_modules/ngx-material-timepicker/src/app/material-timepicker/components/timepicker-field/ngx-timepicker-field.component.d.ts:33:9 - error TS1086: An accessor cannot be declared in an ambient context.

33     set min(value: string | DateTime);

How can I proceed further? Please let me know if you have any solution for this.

**Comment by Agranom** [comment]
@vignesh-balaguru use the latest version of the timepicker

**Comment by vignesh-balaguru** [comment]
Hi Agranom, 
           While i am using the latest version of ngx-timepicker v5.5.2. I am getting error in this console is:

![75625280-55f78500-5c08-11ea-934b-4c514e10ac89](https://user-images.githubusercontent.com/30838676/82119074-2254e180-9799-11ea-88d8-c53cb5f6027a.png)

**Comment by vignesh-balaguru** [comment]
Hi Agranom,
While i am using the latest version of ngx-timepicker v5.5.2. I am getting error in this console is:

![image](https://user-images.githubusercontent.com/30838676/82119094-503a2600-9799-11ea-8bdc-f3f7dae145bc.png)

**Comment by jbarros35** [comment]
Do you guys know some workaround?
