### ISSUE TITLE
Not working in Angular 5

### ISSUE THREAD

**Issue by vineethma** [Agranom/ngx-material-timepicker#318]
...timepicker/src/app/material-timepicker/directives/append-to-input.directive.d.ts, line: 8 
Type 'ElementRef' is not generic.
 L7:  private readonly element;
typescript: ...erial-timepicker/src/app/material-timepicker/ngx-material-timepicker.module.d.ts, line: 3 
L8:  constructor(elementRef: ElementRef<HTMLElement>, renderer: Renderer2);
L9:  private readonly inputCords;

**Comment by Agranom** [comment]
Which version of the picker do you use?

**Comment by airasyaqub** [comment]
same here. @Agranom can you please provide the version compatible with angular 5 and its npm link.

**Comment by Agranom** [comment]
`npm i ngx-material-timepicker@1.1.2` The latest compatible version with angular 5

**Comment by airasyaqub** [comment]
Well I have installed the version u suggested, still getting bugs

error: 
![cartBug](https://user-images.githubusercontent.com/30695220/78576512-33c7d700-7846-11ea-9d53-9c8d57fa3193.PNG)

way I am using it:

![catBug2](https://user-images.githubusercontent.com/30695220/78576552-43dfb680-7846-11ea-813f-60af2925ddeb.PNG)

importing it in root module

![cartBug3](https://user-images.githubusercontent.com/30695220/78576601-52c66900-7846-11ea-9fd7-6fb4fa315e5f.PNG)


package version :
![cartBug4](https://user-images.githubusercontent.com/30695220/78576619-5a860d80-7846-11ea-8fed-43f1715b2801.PNG)

Please look into it and suggest if your package is compatible with angular 5.

**Comment by airasyaqub** [comment]
Here is my angular versions:
![angular5](https://user-images.githubusercontent.com/30695220/78576858-b0f34c00-7846-11ea-8b6d-80e9f3a2aeef.PNG)

**Comment by Agranom** [comment]
Import module into AppModule like this

`imports: [NgxMaterialTimepickerModule.forRoot()]`

**Comment by Agranom** [comment]
Any updates?
