### ISSUE TITLE
24h format not taking into account the first time! (Ang9)

### ISSUE THREAD

**Issue by laminr** [Agranom/ngx-material-timepicker#320]
Following the upgrade (Ang9 then new ngx version) I had the problem that the 24h format was not taken into account on the first date, as soon as I gave a second date it was Ok.

For example:
- giving 07:00 as the value --> became 07:00 AM
- then giving 08:00 (or whatever) --> became 08:00 (as wishes)

```
    <input #time
           [ngxTimepicker]="picker"
           [value]="getDate(when) | date :'HH:mm'"
           [format]="24"
    >
   [...]
```

I finally found out that the problem was that the [format] was placed under the [value] one :'(
And then it worked

```
    <input #time
           [ngxTimepicker]="picker"
           [format]="24"
           [value]="getDate(when) | date :'HH:mm'"
    >
   [...]
```

Please update so as the position of the [format] input does not matter!

**Comment by Agranom** [comment]
I see. Thank you for mentioning it, I'll fix it

**Comment by Agranom** [comment]
Fixed
