### ISSUE TITLE
Issue with Hour hand starts with 00 on Latest versions of Chrome (> 80.0)

### ISSUE THREAD

**Issue by Jithesh-Menon** [Agranom/ngx-material-timepicker#321]
@Agranom ,

I am using the time picker version 5.4.3. It works fine with Chrome versions 78.0 or lesser, but having issues with versions 80.0 or higher.
Selecting the time as 00:02 renders in UI as 24:02. This only happens when the user selects an hour hand as "00".
Please check.

**Comment by Agranom** [comment]
It's related to this one https://github.com/Agranom/ngx-material-timepicker/issues/308

**Comment by giuseeFG** [comment]
I follow
