### ISSUE TITLE
Minutes gap with keyboard input

### ISSUE THREAD

**Issue by KirillTovpinets** [Agranom/ngx-material-timepicker#323]
Hi.

Now, if I set minutes gap in 15m, the clock circle will only contain 00, 15, 30 and 45 minutes, but if I have editable  diaI can't even type '1' in order to fill the input with 15.

Is there any way to overcome this restriction?

**Comment by Agranom** [comment]
Hi. I'll check a possibility to fix it

**Comment by fabbemannen** [comment]
Hi!

Any updates on this issue?

Some more info, if you for example got it set to '5' you can only use 5 or 0 (so 00, 05, 50, 55 are the only valid results). Put it to '1' and same thing, 00, 01, 10, 11.

I assumed it would use modulo for checking validity or something similar, but apparently not.
