### ISSUE TITLE
How to handle incorrect custom user input

### ISSUE THREAD

**Issue by KirillTovpinets** [Agranom/ngx-material-timepicker#325]
Hi!

Is there any possibility to handle user input to the input field in order to validate incorrect symbols and prevent errors in the console from onInput() method?

https://monosnap.com/file/3swD9FnW16xzaSS92Fvztw85vUSPzH

Thank you in advance!

**Comment by Agranom** [comment]
set `readonly` for your input to prevent typing, or use `keydown` event to validate input value

**Comment by KirillTovpinets** [comment]
@Agranom, thanks!
