### ISSUE TITLE
Issue with Min and Max

### ISSUE THREAD

**Issue by sumit8640** [Agranom/ngx-material-timepicker#326]
Hi Team,
I have used below code for the date picker with min and max values, its works perfectly fine when clicked the first time and defaults to PM, but if you move out , click any where else and go back to the field, it defaults to AM whereas it should default to PM even though it does not let user select AM values still from user experience it is incorrect. Have used min as 12:00 pm and max as 11:59 pm. Please suggest.

          <mat-form-field class="col-md-6 col-xs-12">
            <mat-label>Time of Reading</mat-label>
            <input
              matInput
              placeholder="Time of Reading (PM)"
              required
              readonly
              [ngxTimepicker]="pmTimePicker"
              min="12:00 pm"
              max="11:59 pm"
              formControlName="time_of_reading"            
            />
            <ngx-material-timepicker #pmTimePicker [appendToInput]="true" 
            ></ngx-material-timepicker>
            <mat-error *ngIf="hasError('pm_recording.time_of_reading', 'required')">
              Time of Reading is required
            </mat-error>
          </mat-form-field>

**Comment by Agranom** [comment]
I see. Will fix it
