### ISSUE TITLE
Is there a way to hide the header? So one could select duration instead of time. 

### ISSUE THREAD

**Issue by saffabook** [Agranom/ngx-material-timepicker#328]
I would like to use the timepicker to select duration.

Is there a way to use the time picker to select one hour, and 23 minutes for example?

Best regards

**Comment by Agranom** [comment]
Sorry, I didn't get your question. Can you explaine pls ?

**Comment by saffabook** [comment]
Hi there. Apologies for being unclear. 
I seems you already have what I was requesting. What I meant is, if you look at this page. https://agranom.github.io/ngx-material-timepicker/
And scroll down to the **Simple examples** the second example is what I was asking for. That way you not only set a time but a duration. IE I ran for 1hr and 20secs. BTW amazing stuff you have created. Very useful.
