### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by raj2033** [Agranom/ngx-material-timepicker#329]
I need this in a form-component to select a time.
Added the module and the html code as suggested and did `ng serve`: 

```html
<div class="toggle-example">
  <input
    [ngxTimepicker]="toggleTimepicker"
    [disableClick]="true"
    readonly
  />
  <ngx-material-timepicker-toggle
    [for]="toggleTimepicker"
  ></ngx-material-timepicker-toggle>
  <ngx-material-timepicker
    #toggleTimepicker
  ></ngx-material-timepicker>
</div>
```

I got following **error in console** when I clicked on the button to open the form-component. The form does not even load now.
![image](https://user-images.githubusercontent.com/27882128/80136099-df9b5180-85be-11ea-96af-eba6d032b635.png)

This is the warning in the terminal while compiling:
![image](https://user-images.githubusercontent.com/27882128/80136207-06f21e80-85bf-11ea-9f67-e9a86022e953.png)

What am i missing?

**Comment by Agranom** [comment]
Here is the solution https://github.com/Agranom/ngx-material-timepicker/issues/173
