### ISSUE TITLE
Not compatible with angular 9

### ISSUE THREAD

**Issue by Ahmadtawfik-10** [Agranom/ngx-material-timepicker#330]
I had an issue while using it with angular 9, here is the error:

ERROR in node_modules/ngx-material-timepicker/src/app/material-timepicker/ngx-material-timepicker.module.d.ts:2:22 - error NG6003: Appears in the NgModule.exports of MaterialComponentsModule, but could not be resolved to an 
NgModule, Component, Directive, or Pipe class.
    
    This likely means that the library (ngx-material-timepicker) which declares NgxMaterialTimepickerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    2 export declare class NgxMaterialTimepickerModule {
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/app/material-components/material-components.module.ts:28:14 - error 
NG6002: Appears in the NgModule.imports of AppModule, but itself has errors 
    
    28 export class MaterialComponentsModule { }

**Comment by Agranom** [comment]
How do you use it? Can you provide a code snippet pls

**Comment by Ahmadtawfik-10** [comment]
> How do you use it? Can you provide a code snippet pls

I just imported it to the module and it gives me this error!

**Comment by micdemarco** [comment]
hi, I just upgraded my project from Angular 8 to 9, and am also having issues with ngx-material-timepicker

my code
```
<button mat-stroked-button [value]="time" [ngxTimepicker]="picker">{{ time }}<mat-icon>access_time</mat-icon></button>
<ngx-material-timepicker [value]="time" #picker (timeSet)="onTimeSet($event)"
></ngx-material-timepicker>

```
error in console:
```
TypeError: this._timepicker is undefined
ngx-material-timepicker.js:1338
```

I'm using version 5.5.1.  Is the library compatible with Angular 9?

**Comment by micdemarco** [comment]
I solved my problem by moving the [value] attribute to be after the [ngxTimepicker] directive.  Seems like things were getting done in the wrong order and the _timepicker was not initialised.  

new button code:
```
<button mat-stroked-button [ngxTimepicker]="picker" [value]="time">{{ time }}<mat-icon>access_time</mat-icon></button>
```

@Ahmadtawfik-10 I can confirm the library is working for me with Angular 9.1.0 and Angular Material 9.2.0

Importing it as follows:

```
@NgModule({
  imports: [
    NgxMaterialTimepickerModule,
    ...
```

**Comment by Ahmadtawfik-10** [comment]
> I solved my problem by moving the [value] attribute to be after the [ngxTimepicker] directive. Seems like things were getting done in the wrong order and the _timepicker was not initialised.
> 
> new button code:
> 
> ```
> <button mat-stroked-button [ngxTimepicker]="picker" [value]="time">{{ time }}<mat-icon>access_time</mat-icon></button>
> ```
> 
> @Ahmadtawfik-10 I can confirm the library is working for me with Angular 9.1.0 and Angular Material 9.2.0
> 
> Importing it as follows:
> 
> ```
> @NgModule({
>   imports: [
>     NgxMaterialTimepickerModule,
>     ...
> ```

Thank you, i will try and let u know💪

**Comment by Agranom** [comment]
any updates?

**Comment by CoderTonyB** [comment]
I had this exact problem as the first post:
MaterialComponentsModule, but could not be resolved to an
NgModule, Component, Directive, or Pipe class.

I stopped the ng serve window and restarted it, and the error went away.  I don't think I've ever had to restart the angular server before when adding a module, but it worked for me.

**Comment by Cubelaster** [comment]
The issue comes from the fact that the package is not updated for Ivy compiler. 
It will work after restarting the IDE but it should really be upgraded.
