### ISSUE TITLE
Not working with Angular 8.1.2

### ISSUE THREAD

**Issue by stanciupaul** [Agranom/ngx-material-timepicker#332]
The package works fine with `ng serve`, but it throws the following error when a production build is started:

`ERROR in ./node_modules/ngx-material-timepicker/fesm2015/ngx-material-timepicker.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined`

**Comment by Agranom** [comment]
which version of `@angular-devkit/build-angular` do you use?

**Comment by stanciupaul** [comment]
This version: `"@angular-devkit/build-angular": "~0.801.2"`

I've somehow managed to build the app by installing version 5.5.1, then downgrading to 5.5.0 and then to 5.4.3. Installing directly 5.4.3 or any of the above versions has thrown the previously mentioned error.

**Comment by elmartino** [comment]
I've got the same problem when trying to do a production build
`"@angular-devkit/build-angular": "~0.802.2",`

**Comment by elmartino** [comment]
I fixed it by upgrading to `"@angular-devkit/build-angular": "^0.803.23",`

**Comment by Agranom** [comment]
@stanciupaul try to update it to `0.803.23` as well

**Comment by stanciupaul** [comment]
@Agranom this seems to fix the issue. Thanks

**Comment by amedriveroperez1984** [comment]
Hi, I'm having same issue:
"@angular-devkit/build-angular": "~0.803.3"
"ngx-material-timepicker": "^5.5.3"
