### ISSUE TITLE
Dynamic min and max

### ISSUE THREAD

**Issue by Spiff77** [Agranom/ngx-material-timepicker#333]
Hello,

I have a page that will not be refreshed for a while and I am trying to have "min" input equal of the time of when user click on the field.

I did something like this:

```html
<input matInput placeholder="Min time 03:15 am"
          [ngxTimepicker]="appointmentTime" 
          [min]="timeString" [format]="12"
          [value]="timeString" readonly>
<ngx-material-timepicker #appointmentTime  
           [minutesGap]="5" 
           [defaultTime]="timeString"  
           (opened)="getCurrentTime()"></ngx-material-timepicker>
```

```typescript
  getCurrentTime() {
    this.timeString = this.currentDateTime.plus({minutes: ( 5 - this.currentDateTime.minute % 5)}).toFormat('h:mm a');
  }
```

But only have the result of when the component init. Is there a way to do that?

Thanks !

**Comment by Agranom** [comment]
you can use `timeSet` 
`<ngx-material-timepicker (timeSet)="getCurrentTime()"></ngx-material-timepicker>`
