### ISSUE TITLE
Problem with ngx-material-timepicker when i go to Angular 9

### ISSUE THREAD

**Issue by astrO1** [Agranom/ngx-material-timepicker#334]
I have an application that uses your component when I enter and click on the icon I have this

**NullInjectorError: R3InjectorError(AppModule)[InjectionToken TimeLocale -> InjectionToken TimeLocale -> InjectionToken TimeLocale]: 
  NullInjectorError: No provider for InjectionToken TimeLocale!**

**Comment by Agranom** [comment]
Can you show me a code snippet how you use it pls

**Comment by Agranom** [comment]
Duplicated #259

**Comment by astrO1** [comment]
It worked with the solution you provided but I invoke this component in a modal and now the clock is behind the modal.

I put this style in Chrome but how I can put a custom CSS class in this component?

![image](https://user-images.githubusercontent.com/4139900/80536782-492dae00-8979-11ea-976b-9e1ed0c3a95c.png)

**Comment by Agranom** [comment]
Have you tried `timepickerClass` input ?
