### ISSUE TITLE
Not Working in Angular 9

### ISSUE THREAD

**Issue by GabrielSouza28** [Agranom/ngx-material-timepicker#338]
Execute all the steps but it still doesn't work. When clicks in the input it doesn't open anything, it is like a normal input.

npm install --save ngx-material-timepicker
Next import the timepicker module into your app's module:

import {NgModule} from '@angular/core';
import {NgxMaterialTimepickerModule} from 'ngx-material-timepicker';
 
@NgModule({
  imports: [NgxMaterialTimepickerModule]
})
export class MyModule {}
Finally connect the timepicker to an input via a template property:

<input [ngxTimepicker]="picker">
<ngx-material-timepicker #picker></ngx-material-timepicker>
The timepicker opens once you click on the input

**Comment by Agranom** [comment]
Try to import module into app.module

**Comment by GabrielSouza28** [comment]
Thanks for answering. In this way:

import {NgxMaterialTimepickerModule} from 'ngx-material-timepicker';

@NgModule({
imports: [NgxMaterialTimepickerModule]
})

I've done that, but somehow it doesn't work.
