### ISSUE TITLE
TimePicker Overlay cannot leave the content container

### ISSUE THREAD

**Issue by dlahmad** [Agranom/ngx-material-timepicker#34]
I'm not sure wether this is a bug or what to do about it.
![grafik](https://user-images.githubusercontent.com/21985067/45000677-3fe31700-afc7-11e8-917d-7d66885659bc.png)

As you can see the complete menu side is not part of the overlayed section as i would wish it to be.
I use the Angular Material Design "\<mat-sidenav>", "\<mat-sidenav-content>" and etc. The overlay seems to be limited by the "\<mat-sidenav-content>" container. 

How can this be fixed?
Thank you very much!

**Comment by Vedaevolution** [comment]
@Agranom Thank you very much! This worked!

 Is there something you could change in the picker to prevent something like that from happening?

**Comment by Agranom** [comment]
There's exist touchsupport. Doesn't it work with you?

**Comment by Agranom** [comment]
> Is there something you could change in the picker to prevent something like that from happening?
I'll check some ways which can fix that

**Comment by Vedaevolution** [comment]
Sorry that was me writing before really testing it. Yes it works withtouch as well. Eve though it's usage was counterintuitive to me at the first try. Dragging the handworks quite well. What i tried first was to simply "choose" or "tap" the number like it's done with the mouse. This should work as well!

Still very very good work! Thanks alot!

**Comment by Agranom** [comment]
Thanks! Glad to hear that!
