### ISSUE TITLE
24hr format, invalid dateTime - Issuse #285 appeared again

### ISSUE THREAD

**Issue by darkovuj** [Agranom/ngx-material-timepicker#342]
this issue appeared again

https://github.com/Agranom/ngx-material-timepicker/issues/285

I'm using version 5.5.2 - downloaded few hours ago.

**Comment by Agranom** [comment]
Can you reproduce on the demo page? https://agranom.github.io/ngx-material-timepicker/

**Comment by darkovuj** [comment]
Yes, demo page has this problem too

![image](https://user-images.githubusercontent.com/22934657/82912988-0823bc00-9f6e-11ea-8d29-993185820d36.png)

**Comment by Agranom** [comment]
Just provide a proper locale which supports 24h format

**Comment by darkovuj** [comment]
Any hint how to do that? I already have
` providers: [{ provide: LOCALE_ID, useValue: 'en-US' }],`
in app.module.ts and it's working fine for the rest of the application. I think that 'en-US' supports 24h format

**Comment by antoinedelaplace** [comment]
Hello! I have the same issue with 24h format. On the demo page we have the same problem. When we select 00:00 we have 24:00 in the input value. And our locale supports 24hr format

**Comment by Agranom** [comment]
@darkovuj you don't need to override provider. `NgxMaterialTimepickerModule.setLocale('uk-UA')` will help.

Otherwise I'll try to convert from 24:00 to 00:00 by default when 24h format is selected

**Comment by darkovuj** [comment]
Yes, this works.

Thanks.

**Comment by Agranom** [comment]
Fixed it. Now you'll get '00:xx' time with default locale. Update to the latest version
