### ISSUE TITLE
[value] before [ngxTimepicker] throws error

### ISSUE THREAD

**Issue by darkovuj** [Agranom/ngx-material-timepicker#344]
If you put **[value]** before **[ngxTimepicker**] like

<input matInput  **[value]="someValue" [ngxTimepicker]="endpicker"** [format]="24">
<ngx-material-timepicker #endpicker></ngx-material-timepicker>

you will get exception 

> TypeError: Cannot read property 'minutesGap' of undefined
>at TimepickerDirective.set value [as value] (ngx-material-timepicker.js:1099)

Workaround is to change places of this two fields
<input matInput  **[ngxTimepicker]="startPicker"  [value]="someValue"** [format]="24">
<ngx-material-timepicker #startPicker></ngx-material-timepicker>

Also if you set [format] after [value] it will not be applied to control.

**Comment by Agranom** [comment]
I see. Will fix it.
