### ISSUE TITLE
Validation MIN not working for HOURS ngx-timepicker-field 

### ISSUE THREAD

**Issue by DenSmolonski** [Agranom/ngx-material-timepicker#346]
Hi, validation MIN not working for HOURS ngx-timepicker-field. I set validation in MIN '10:30'. When i put arrow down in ngx-timepicker-field for hour i get error and can change hour. I change hour from 10 to 09.
![image](https://user-images.githubusercontent.com/26486382/84385325-102f5d00-abf8-11ea-83f5-e9f8fffe0d34.png) 
![image](https://user-images.githubusercontent.com/26486382/84385365-1e7d7900-abf8-11ea-93bd-c397c975bda7.png)

For minutes work all correctly, i can not change to invalid minute. Example from 30 to 29.
How can i fix it?

**Comment by DenSmolonski** [comment]
Add info. MIN not work for 24 format.

**Comment by Agranom** [comment]
I will check

**Comment by DenSmolonski** [comment]
Do you fix a problem? I can help and fix it and you check my pull request.

**Comment by Agranom** [comment]
@DenSmolonski It would appritiate you help, cause I'm a bit run out of time

**Comment by iluminoguru** [comment]
@Agranom @DenSmolonski is this fixed?

**Comment by CSoetaert** [comment]
Hi, I have the same problem with the min. And also, I cannot edit the minutes with keyboard entries when there is a min specified in the field.

**Comment by enzoberger** [comment]
same problem with min and max in 24h format

**Comment by enzoberger** [comment]
OK, i guess I found the bug. It in the file "ngx-timepicker-field.component.ts" line 147. Your calling the isChangePeriodDisabled only for 12 hour format. You just need to delete the "if" in line 147 and it will work fine for 24 hour format.
That should also solve issue https://github.com/Agranom/ngx-material-timepicker/issues/369
Would be great if you could fix that asap. Thanks!
![image](https://user-images.githubusercontent.com/7658045/127294936-3cfa1f95-b4de-45f1-be5b-88cfcc637ac3.png)

**Comment by Agranom** [comment]
The issue is fixed. Pls update to the latest version
