### ISSUE TITLE
Min Max Disabled

### ISSUE THREAD

**Issue by GabrielSouza28** [Agranom/ngx-material-timepicker#347]
Hello, thanks for the great work. 
I am in a situation where I need Min and Max to be disabled initially, because I am using them dinamically. Is there any possibility to disable them? something like [min} = "disabled"

**Comment by Agranom** [comment]
Hello. Min adn Max, aren't dinamic, so there is no way you can change them. They could be changed after reopening the timepicker

**Comment by GabrielSouza28** [comment]
Let me explain better. I am trying to limit the hour in field 1 by other hour values put by the user in other fields. Until then it works fine, but when the user leaves these other fields in blank I would like it to disable the min/max field, but it seems that once is declared I have always to put a value in it.
