### ISSUE TITLE
Bug when editing after Canceling

### ISSUE THREAD

**Issue by rainbird17** [Agranom/ngx-material-timepicker#35]
We found a bug that occurs after you edit a Time, and click Cancel, then Re-Edit the same time again.  This is also reproducible on your Demo site.

Steps:

1. Edit/Create a new Time at 3:15 pm
2. Edit the time and the Time Picker (correctly) displays 3:15 pm
3. Change the Value in the Time Picker to 8:00 am (or any value other than 3:15 pm) but do NOT click OK.
4. Click Cancel
5. The display Time on the webpage is still 3:15 pm (good, because we clicked cancel)
6. Now Edit it again.
7. The Time Picker incorrectly displays 8:00 am (The value we set in step 3). It is expected to display 3:15 pm (the actual value being edited is still 3:15 pm).

**Comment by Agranom** [comment]
I see. I'll fix it and let you know

**Comment by Agranom** [comment]
Done. Update to the newest version (2.6.0)

**Comment by rainbird17** [comment]
This has fixed the problem!  Thank you so much for your help, we appreciate it.
