### ISSUE TITLE
v3.3.1: Selecting 00 hours with mouse in 24 hour format does not update the displayed hour value in timepicker header

### ISSUE THREAD

**Issue by SumitB06** [Agranom/ngx-material-timepicker#350]
I am using v3.3.1 as my project uses angular 7. Selecting 00 hours with mouse in 24 hour format does not update the displayed hour value in timepicker header. For example, if selected hours was 13, and I use mouse to select 00, the control switches to minute picker, but the hour displayed in the header is still 13. After pressing Ok, the input shows the correct time with 00:mm, and opening the timepicker after that also selects and shows 00 in header.

**Comment by Agranom** [comment]
Hello. I believe it's already fixed in newer versions of the timepicker
