### ISSUE TITLE
ngx-timpicker-field not being able to switch back to hours from minutes.

### ISSUE THREAD

**Issue by pallaviShriya96** [Agranom/ngx-material-timepicker#354]
Hi ,

Once I go to minutes field , I'm not being able to switch to hours. Please check as it's urgent for me. Sharing my code. <ngx-timepicker-field class='attendance-timepicker' formControlName="InTime" (click)="sendIndex(i)"
                    [format]="24"  [controlOnly]="true"></ngx-timepicker-field>

**Comment by Agranom** [comment]
Hi. What is `sendIndex(i)` for? Maybe something wrong with it

**Comment by pallaviShriya96** [comment]
it is just sending the value of the index , as I'm using reactive form. Even in the demo I was unable to switch from minutes back to hours.Please help

**Comment by Agranom** [comment]
Unable to reproduce
