### ISSUE TITLE
Use peer dependency for Luxon

### ISSUE THREAD

**Issue by Enngage** [Agranom/ngx-material-timepicker#355]
Hey there! 

Could you please make `Luxon`  a `Peer dependency`? Since you have it listed as dependency it is shipped with your library and if the project is also using Luxon, it will result in code duplication and +60KB because multiple Luxon libraries can be included.

Using Peer dependencies will mitigate this problem completely.

**Comment by Agranom** [comment]
Hey

I had issue to make it as dependency. I'm afraid if I change it back there will be more issues )

**Comment by Enngage** [comment]
Thanks for a quick reply :-) I'm pretty sure there wouldn't be any issues (I've been using it for some time for several of my packages :)). It would be the same thing as Angular itself does with rxjs. What you would do is:

- Specify Luxon (ideally with minor relaxed versioning) as a dependency (e.g. `"luxon": "^1.24.0"`)
- Move Luxon to `devDependencies` in this repo as it is needed to build & run your code (moving it to devDependencies bascially means it will install for you, but not for people using your library which is what you want to prevent your users from having duplicate Luxon libraries). There is pretty much no different for you if you install packages in your dependencies or devDependencies so it wouldn't break anything. It really affects what code is distributed alongside your code.
- Update your docs to include Luxon installation notes:

```
npm i --save ngx-material-timepicker
npm i --save luxon
```

Npm will tell people automatically to install peer dependencies when running `npm i`, but its good practice to include it in docs.

**Comment by Enngage** [comment]
![luxon](https://user-images.githubusercontent.com/7137351/86330186-97944d00-bc47-11ea-9554-5c811f89dba8.png)

Adding a bundle report for reference.

**Comment by Agranom** [comment]
@Enngage Thanks for explanation. Definitely will do it soon.

**Comment by Enngage** [comment]
Any chance you can look at this? It should be really easy to implement - just move it to `peerDependencies` and it would save a lot of people at least 60KB from their bundles ;)

**Comment by Enngage** [comment]
Still nothing?

**Comment by maxstee** [comment]
I'm also quite bothered by this.
![immagine](https://user-images.githubusercontent.com/18459512/107746184-b1395f00-6d15-11eb-9981-391876d24e0e.png)
I'm considering using date-fns to avoid that.

**Comment by Enngage** [comment]
There is probably no point in waiting anymore, we are moving away from this library and instead creating our own time picker. Gl anyways.

**Comment by edemircan** [comment]
Would be great. Could shrink my app with a few kb.

**Comment by Agranom** [comment]
Done. Pls update to the latest version. Sorry for being so long
