### ISSUE TITLE
Color for ngx-timepicker

### ISSUE THREAD

**Issue by kibria06cse** [Agranom/ngx-material-timepicker#360]
I want to change the color from black to Green. I need to do on the header, on button, on clock everywhere where default blue color is used. 

How can I do it?

**Comment by Agranom** [comment]
You can provide a custom theme. Check the demo or doc https://agranom.github.io/ngx-material-timepicker/

**Comment by kibria06cse** [comment]
Where to put the ngxTheme globally? I have put it on style.css. But it is not working. Also angular is throwing an error that theme is not a known element.

**Comment by Agranom** [comment]
Which version do you use?

**Comment by kibria06cse** [comment]
I am using the latest version 5.5.3

**Comment by Agranom** [comment]
`<div class="custom-theme-example">
            <input placeholder="Custom theme" aria-label="Custom theme"
                [ngxTimepicker]="darkPicker" readonly>
            <ngx-material-timepicker #darkPicker [theme]="darkTheme"></ngx-material-timepicker>
         </div>`
