### ISSUE TITLE
IE 11 ignore format and theme color

### ISSUE THREAD

**Issue by jaffbeto** [Agranom/ngx-material-timepicker#362]
Format ignore on IE 11
![image](https://user-images.githubusercontent.com/17092218/89643594-63e7bb00-d8b6-11ea-84af-37032505c3a9.png)

Theme ignore on IE 11
![image](https://user-images.githubusercontent.com/17092218/89643394-efad1780-d8b5-11ea-926d-863a2758b267.png)

```
"@angular/core": "10.0.1"
"@angular/material": "10.0.0"
"ngx-material-timepicker": "5.5.3"
```
my configuration is as follows:

```
myTheme: NgxMaterialTimepickerTheme = {
    container: {
      bodyBackgroundColor: '#ffff',
      buttonColor: '#37393B'
    },
    dial: {
      dialBackgroundColor: '#CC3333',
    },
    clockFace: {
      clockFaceBackgroundColor: '#37393B',
      clockHandColor: '#CC3333',
      clockFaceTimeInactiveColor: '#fff'
    }
  };
```

```
  <mat-form-field class="w-50 float-left pr-2 text-right" *ngIf="data.allTime === timeOff">
      <input matInput [attr.data-selenium]="'input-policy-time-start'" type="time" [ngxTimepicker]="pickerStart" [(ngModel)]="data.startTime" [ngModelOptions]="{standalone: true}" (ngModelChange)="onChangeTime($event, 'start')" #fromTime [required]="data.allTime === timeOff" min="00:00" [max]="data.endTime || '23:59'" [format]="24" readonly>
      <ngx-material-timepicker [attr.data-selenium]="'timepicker-policy-time-start'" #pickerStart [theme]="myTheme" [cancelBtnTmpl]="cancelBtn" [confirmBtnTmpl]="confirmBtn" preventOverlayClick="true"></ngx-material-timepicker>
      <span class="d-inline-block mb-5px mr-2" matPrefix>{{'POLICIES.TABS.PRIVATE.LABELS.FROM' | translate}} </span>
      <mat-icon [for]="pickerStart" matSuffix>timer</mat-icon>
  </mat-form-field>

  <mat-form-field class="w-50 float-left pl-2 text-right" *ngIf="data.allTime === timeOff">
      <input matInput [attr.data-selenium]="'input-policy-time-end'" type="time" [ngxTimepicker]="pickerEnd" [(ngModel)]="data.endTime" [ngModelOptions]="{standalone: true}" (ngModelChange)="onChangeTime($event, 'end')" #toTime [required]="data.allTime === timeOff" [min]="data.startTime || '00:00'" max="23:59" [format]="24" readonly>
      <ngx-material-timepicker [attr.data-selenium]="'timepicker-policy-time-end'" #pickerEnd [theme]="myTheme" [cancelBtnTmpl]="cancelBtn" [confirmBtnTmpl]="confirmBtn" preventOverlayClick="true"></ngx-material-timepicker>
      <span class="d-inline-block mb-5px mr-2" matPrefix>{{'POLICIES.TABS.PRIVATE.LABELS.TO' | translate}} </span>
      <mat-icon [for]="pickerEnd" matSuffix>timer</mat-icon>
  </mat-form-field>
```

**Comment by szingg** [comment]
Works in version 4.0.2. Consider downgrading...

**Comment by szingg** [comment]
to be more clear: format works in version 4.0.2.
to override the styles in version 4.0.2 use following css
    /* IE11 TIMEPICKER STYLES */
    @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {  
        header.timepicker__header {
            background-color: #00838f !important; // A500
        }
    
        div.clock-face {
            background-color: #4da8b1 !important; // A300
        }
    
        .clock-face__number > span.active {
            background-color: #005360 !important; // A900
            color: #fff !important;
        }
    
        .clock-face__clock-hand {
            background-color: #005360 !important; // A900
        }
    
        .clock-face__clock-hand_minute:before {
            border: 4px solid #005360 !important; // A900
        }
    
        .clock-face__number--outer > span {
            color: #fff !important;
        }
    
        .clock-face__number--inner > span {
            color: rgba(255,255,255,0.5) !important;
        }
    }

**Comment by nadhir-falta** [comment]
Thank you for the great component, we really appreciate your hard work on this.
Any update on this issue ? as the comment above said it's working on previous version.
Thank you!

**Comment by Agranom** [comment]
I don't support IE 11 in the newer versions. Sorry
