### ISSUE TITLE
Time Picker Value always returning as 12:(selected minutes ) when I am only selecting minutes, 

### ISSUE THREAD

**Issue by ajaykonda981** [Agranom/ngx-material-timepicker#367]
Note : I am in this case using following code in html
 <ngx-timepicker-field formControlName="timePickerControl" [defaultTime]="'00:00'" [format]="24">
    </ngx-timepicker-field>
   
Hello Team, 
  Time picker control always returning time 12:(select
![time picker issue](https://user-images.githubusercontent.com/57897162/93774877-5d7f8980-fc3f-11ea-98e7-4099f3924fcf.png)
ed minutes)
eg: If I selected only minutes say (selected 01 minutes) and didn't touched HH dropdown , I am experiencing value as 12:01.
I am facing this issue when I am using reactive forms in angular .

**Comment by Agranom** [comment]
The issue is fixed. Pls consider to update the lib.
