### ISSUE TITLE
ngx-timepicker-field disabled status with reactive forms

### ISSUE THREAD

**Issue by ErikAlbert** [Agranom/ngx-material-timepicker#381]
Component not refreshing after adding or removing disabled status to its form control. If I add disabled input it works but angular show warnings about not to use these type of atributtes with reactive forms.

I tried to use a viewChild and call the method setDisabledState on the picker. It shows how picker has correctly disabled and enabled but it seems component is not detecting the current disabled state so HTML is not refreshed.

Example code:

@ViewChild('pickerField')
  pickerField: NgxTimepickerFieldComponent;

this.props.formControl.statusChanges.subscribe(status => {
        if (this.pickerField) {
          this.pickerField.setDisabledState(
            status === 'DISABLED' ? true : false
          );
          this.changeDetectorRef.markForCheck(); // DOES NOTHING
          this.changeDetectorRef.detectChanges(); // DOES NOTHING
          this.applicationRef.tick(); // DOES NOTHING
          console.log(status, this.pickerField.disabled);
        }
      })

**Comment by Agranom** [comment]
Fixed
