### ISSUE TITLE
Unable to keyin Hours - enableKeyboardInput is not working properly if I set Min Time

### ISSUE THREAD

**Issue by sundharesan** [Agranom/ngx-material-timepicker#386]
I am using Angular 10.0 and ngx-material-timepicker 5.5.3

Steps to reproduce
1. Set Min Time to '10.20 am' or '10.20' in their respective 12 or 24 hour format.
2. Set enableKeyboardInput to true.
3. Open the Time Picker and clearout the hours field.
4. Now try to type using keyboard in hour input.
5. Unable to type the Hour.

**Comment by Agranom** [comment]
Issue is not exists in newer versions. Pls update
