### ISSUE TITLE
Label on ngx-timepicker-field

### ISSUE THREAD

**Issue by scottboyd-ai** [Agranom/ngx-material-timepicker#394]
Adding a label to a timepicker-field does not produce the expected output.

With this setup:
```
<mat-form-field class="form-element">
        <mat-label>Start Time</mat-label>
        <ngx-timepicker-field formControlName="startTime" defaultTime="startTime"></ngx-timepicker-field>
        <input matInput [hidden]="true" formControlName="startTime">
      </mat-form-field>
```

We see this in the browser:
![image](https://user-images.githubusercontent.com/10579185/139940550-4cc545bd-a756-47d5-b3ab-8e80fa6dac7c.png)

The label is located on top of the input fields.

When a value is supplied to the input, the label looks correct:
![image](https://user-images.githubusercontent.com/10579185/139940936-19e3917b-7e61-4806-8484-0cc980e9bf1a.png)

With this setup:

```
 <mat-form-field class="form-element">
        <ngx-timepicker-field label="Start Time" formControlName="startTime" defaultTime="startTime"></ngx-timepicker-field>
        <input matInput [hidden]="true" formControlName="startTime">
      </mat-form-field>
```

We see this in browser:
![image](https://user-images.githubusercontent.com/10579185/139940730-b2722e92-6265-4265-a206-f0d3ec272aea.png)

The label does not appear.

**Comment by giuliohome** [comment]
I use the following html view and it's rendered fine for me


```html
    <mat-form-field appearance="fill">
      <mat-label for="row-refTime">reference time</mat-label>
      <input id="row-refTime"  matInput [ngxTimepicker]="timepicker" [(ngModel)]="row.refTime">
      <ngx-material-timepicker #timepicker></ngx-material-timepicker>
    </mat-form-field>
```

**Comment by scottboyd-ai** [comment]
That is for the ngx-material-timepicker, not the ngx-timepicker-field.

**Comment by giuliohome** [comment]
Sorry for my confusion!

Btw, have you already considered [this solution](https://stackoverflow.com/a/64313356)  for the label?

**Comment by scottboyd-ai** [comment]
I had not! Let me give that a shot and I'll come back with my results.

**Comment by giuliohome** [comment]
It's react. We need angular equivalent though. But the design should be the same

**Comment by giuliohome** [comment]
It should be `floatLabel="always"` in `<mat-form-field` tag
