### ISSUE TITLE
How to add seconds to the time picker format instead of just HH:MM i want HH:MM:SS

### ISSUE THREAD

**Issue by Lourguioui** [Agranom/ngx-material-timepicker#396]
Here the code i'm using the format i'm getting is HH:MM and i want to get the seconds to, so the desired format is HH:MM:SS
`<nz-input-group [nzSuffix]="suffixIconClock">
                            <input type="text"
                                   [ngxTimepicker]="repeatPerDayEndTimePicker"
                                   [(ngModel)]="repeatPerDay.endTime"
                                   [ngModelOptions]="{standalone: true}"
                                   nz-input placeholder="Select Time"
                                   [format]="24"/>
                            <ngx-material-timepicker #repeatPerDayEndTimePicker
                                                     [theme]="clockTheme"></ngx-material-timepicker>
  </nz-input-group>`

**Comment by Agranom** [comment]
Seconds are not supported
