### ISSUE TITLE
On Angular 6 there are some troubles

### ISSUE THREAD

**Issue by filosssof** [Agranom/ngx-material-timepicker#4]
`ERROR in node_modules/ngx-material-timepicker/src/app/material-timepicker/ngx-material-timepicker.component.d.ts(4,10): error TS2305: Module '"%mypath%/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ngx-material-timepicker/src/app/material-timepicker/services/ngx-material-timepicker-event.service.d.ts(1,10): error TS2305: Module '"%mypath%node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/ngx-material-timepicker/src/app/material-timepicker/services/ngx-material-timepicker-event.service.d.ts(2,10): error TS2305: Module '"%mypath%/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ngx-material-timepicker/src/app/material-timepicker/services/ngx-material-timepicker.service.d.ts(2,10): error TS2305: Module '"%mypath%node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
`
After installing I got this error.

**Comment by Agranom** [comment]
I haven't done migration yet. I'll try to do it this week

**Comment by Agranom** [comment]
updated to angular 6
