### ISSUE TITLE
Publish an Ivy distribution

### ISSUE THREAD

**Issue by nunoarruda** [Agranom/ngx-material-timepicker#401]
When running `ng serve` I get this:
```
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- @ionic-native/core [module/esm5] (https://github.com/ionic-team/ionic-native.git)
- @ionic-native/onesignal [module/esm5] (https://github.com/ionic-team/ionic-native.git)
- ngx-sortablejs [es2015/esm2015] (https://github.com/sortablejs/ngx-sortablejs)
- ngx-material-timepicker [es2015/esm2015] (https://github.com/Agranom/ngx-material-timepicker.git)
- @ionic-native/ble [module/esm5] (https://github.com/ionic-team/ionic-native.git)
- @fullcalendar/angular [es2015/esm2015] (https://github.com/fullcalendar/fullcalendar-angular.git)
Encourage the library authors to publish an Ivy distribution.
```
My general understanding is that "View Engine" is deprecated and will eventually be removed and "Ivy" is the new next-level Angular compiler/packager. So I'm opening this issue to encourage you folks to publish an Ivy distribution of `ngx-material-timepicker` 🙂

More info:
https://angular.io/guide/creating-libraries
https://blog.angular.io/upcoming-improvements-to-angular-library-distribution-76c02f782aa4
https://dev.to/this-is-angular/the-angular-ivy-guide-for-library-authors-9md

**Comment by tonysamperi** [comment]
Have you considered using [ngx-mat-timepicker](https://github.com/tonysamperi/ngx-mat-timepicker)?
I'm about to publish v14...

**Comment by nunoarruda** [comment]
@tonysamperi thanks for the heads up. I will definitely give it a try since `ngx-material-timepicker` looks to be unmaintained/abandoned.

**Comment by Agranom** [comment]
The package is updated. It supports Ivy from v12.
