### ISSUE TITLE
Best way to change style

### ISSUE THREAD

**Issue by dpadula** [Agranom/ngx-material-timepicker#41]
What would be the best way to change de styles, colors, etc. of the component?

I've tried to redefine 

.timepicker__header {
    background-color: #212529 !important;
}
without success.

Any clues?
Thanks

**Comment by Agranom** [comment]
Hi. You can use this https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep (but it's already deprecated). Or you can add your new  styles to your global style.css

**Comment by dpadula** [comment]
Thanks for the quick answer! Indeed, I've tried

:host /deep/ .timepicker__header {
    background-color: #212529 !important;
}

:host /deep/ .clock-face__number > span.active {
    background-color: #212529 !important;
}
And it works, but I'cant change the needle clock color yet.

**Comment by Agranom** [comment]
you just have to apply the right css selector )

**Comment by dpadula** [comment]
Yes! Thanks, I'll try this.

**Comment by kbjerring** [comment]
For reference, the needle (and minute hand) can be colored this way

.clock-face__clock-hand
    background-color: $primary !important
    &:after
      background-color: $primary !important

.clock-face__clock-hand_minute:before
    border: 4px solid $primary !important
