### ISSUE TITLE
Keyboard input forces you to delete the old value first, instead of just letting you override the value with new input.

### ISSUE THREAD

**Issue by NikolaKrstic94** [Agranom/ngx-material-timepicker#417]
Steps to reproduce: 
1.Go to https://agranom.github.io/ngx-material-timepicker/ and check the section "Editable dial" with the property [enableKeyboardInput]="true":
2. Open the timepicker and try inputting any number.
3. It will not let you override the current hours by just typing, you have to delete the old value first, which is not user friendly at all and non-tech people will think it's just not working.

![ngx material timepicker](https://user-images.githubusercontent.com/25144458/207874631-02fb2665-092a-499e-b936-000171a23535.gif)

Another issue would be that it doesn't automatically switch to minutes after inputting the correct format for "hours" tab.

**Comment by Agranom** [comment]
Done
