### ISSUE TITLE
Invalid DateTime

### ISSUE THREAD

**Issue by durga0702** [Agranom/ngx-material-timepicker#427]
I am using ngx-material-timepicker v 5.5.3. time changed event emits an invalid date time for 12hrs format.

<div>
  <input matInput type="text" name="time" [ngxTimepicker]="timepicker" [format]="12" placeholder="Time" readonly>
  <ngx-material-timepicker-toggle matSuffix [for]="timepicker"></ngx-material-timepicker-toggle>
  <ngx-material-timepicker (timeChanged)="onTimeChanged($event)" #timepicker></ngx-material-timepicker>
</div>

**Comment by pranavpandey86** [comment]
Yes we are facing same issue, I think they already fixed it but PR still not merged.

**Comment by moon-web75** [comment]
#423 Please check this  and now working fine

**Comment by Agranom** [comment]
PR was merged. Pls update the library to the latest version
