### ISSUE TITLE
Support angular 16

### ISSUE THREAD

**Issue by stefanbildl** [Agranom/ngx-material-timepicker#429]
Hi,

This module is not working after angular 15. 
Can you please update the dependencies? 

Thank you

**Comment by InnVardhan** [comment]
+1. Please add support to ng v16

**Comment by simmeix** [comment]
+1. Would be very nice! Or do you guys know any other good TimePicker?

**Comment by Agranom** [comment]
Hi. I'll try to take a look at this soon.

**Comment by SergioZhydecky** [comment]
Would be super nice! :)

**Comment by Agranom** [comment]
Done. Pls update to the latest version
