### ISSUE TITLE
Time range selection (min, max) not working correctly

### ISSUE THREAD

**Issue by Zaheer211** [Agranom/ngx-material-timepicker#43]
We're using ngx-material-timepicker in our project and came across an issue in range time selection.
Here is input element for time-picker.

`<input matInput type="text" [ngClass]="{'time myInput': true, smallFont: popupView}"
        formControlName="time" [ngxTimepicker]="picker" placeholder="Add time" min="09:00 am" max="03:00 pm" readonly>`

`<ngx-material-timepicker [ngClass]="{'timePicker': true}" (timeSet)="onTimeSet($event)" #picker></ngx-material-timepicker>`

Expected:
It should allow to select anytime between 09:00 am to 03:00 pm.

Problem:
12:00 pm to 12:59 pm can't be selected. Event though it lies within the above range.

Two screenshots are attached to support above argument.

![screenshot from 2018-09-25 09-38-44](https://user-images.githubusercontent.com/26340878/45993200-22293f00-c0a7-11e8-89fa-7db3b92921a6.png)

![screenshot from 2018-09-25 09-39-12](https://user-images.githubusercontent.com/26340878/45993202-26edf300-c0a7-11e8-92b3-c4d853a43aab.png)

Thanks in advance for any help!

**Comment by Agranom** [comment]
I see. I'll check it

**Comment by Agranom** [comment]
Fixed, sorry for so long. Update to the latest version and try

**Comment by Zaheer211** [comment]
I have update to latest version 2.6.2 and now within the range (11:00 am to 03:00 pm) minutes are not select-able for 1 pm, 2 pm and 3 pm. Which is very strange as it was working well in earlier version. 
Attaching screenshots to support my argument.
![screenshot from 2018-10-07 17-43-26](https://user-images.githubusercontent.com/26340878/46582370-ed31ca80-ca5e-11e8-85bd-3fb031aa4d85.png)
![screenshot from 2018-10-07 18-30-15](https://user-images.githubusercontent.com/26340878/46582384-25d1a400-ca5f-11e8-8395-fd27c358ba7b.png)
![screenshot from 2018-10-07 18-30-38](https://user-images.githubusercontent.com/26340878/46582385-2ec27580-ca5f-11e8-9efb-e25a76281369.png)

**Comment by Agranom** [comment]
I see, I guess it’s because of refactoring. I’ll figure out what the problem is and fix ASAP

**Comment by Agranom** [comment]
Update to 2.6.3 and try it out please

**Comment by Zaheer211** [comment]
Hi Agranom!
Thanks for your efforts but now the previous issue is somewhat back again where time between 12:00 pm to 12:59 pm was not select-able in allowed range of 11:00 am to 03:00 pm. 
Although one improvement is that now 12 can be selected from hours which previously was not working. 
But minutes are not select-able when 12 is selected.
Let me share a screen shot for this situation

![screenshot from 2018-10-08 21-00-25](https://user-images.githubusercontent.com/26340878/46620093-35271f00-cb3d-11e8-8d64-4c20cc4ec4a0.png)

**Comment by Agranom** [comment]
Oh, sorry. I've aready found the problem and fix it in the next release with other bugfixes

**Comment by Zaheer211** [comment]
Sorry but in the above screenshot I'm using version 2.6.3 and I can't see more updated version than that.

**Comment by Agranom** [comment]
I haven't publish yet )

**Comment by Nik1990** [comment]
Hi, i've the following problem of @Zaheer211 . It's solved?
Thanks

**Comment by Zaheer211** [comment]
Not solved yet. Waiting for the fixed version.

**Comment by Agranom** [comment]
Have you tried yet?

**Comment by Zaheer211** [comment]
I tried it just now and now hours out of range are correctly disabled. But minutes out of range are not getting disabled.
Here are the screenshots for case 11:15 am to 03:25 pm.
![screenshot from 2018-10-12 19-09-47](https://user-images.githubusercontent.com/26340878/46874388-7cb9ed80-ce52-11e8-9724-f6d3b7d66909.png)
![screenshot from 2018-10-12 19-11-11](https://user-images.githubusercontent.com/26340878/46874431-99eebc00-ce52-11e8-9fb6-cf497a830774.png)

**Comment by Agranom** [comment]
Sorry, my fault. Already fixed it. Update to 2.6.5 pls

**Comment by Zaheer211** [comment]
Thanks - I'll check and let you know.

**Comment by Agranom** [comment]
Have you checked?

**Comment by Zaheer211** [comment]
Hey Agranom! This issue seems resolved in version 2.8.0. Thanks for your great support, I'm closing it.
