### ISSUE TITLE
Issue with 24 hr format

### ISSUE THREAD

**Issue by payyavularajasekharholcim** [Agranom/ngx-material-timepicker#451]
Though [format]="24" is used it doesn't work

**Comment by Agranom** [comment]
Can you provide more details?

**Comment by payyavularajasekharholcim** [comment]
@Agranom  The same UI is rendered though [format]="24" is used 

<img width="218" alt="image" src="https://github.com/Agranom/ngx-material-timepicker/assets/120568509/a860a990-8a0e-456e-aa76-99a63bf67661">

**Comment by Agranom** [comment]
@payyavularajasekharholcim can you provide me with your HTML please (how you initialized timepicker)

**Comment by payyavularajasekharholcim** [comment]
@Agranom here is the html used

<input
              class="ct-date-input"
              formControlName="start_time"
              placeholder="{{ 'SelectTime' | translate }}"
              [ngxMatTimepicker]="picker"
              readonly
            />
            <ngx-mat-timepicker #picker [format]="24"></ngx-mat-timepicker>

**Comment by Agranom** [comment]
@payyavularajasekharholcim you should add `[format]` to `input`
<input
class="ct-date-input"
formControlName="start_time"
placeholder="{{ 'SelectTime' | translate }}"
[ngxMatTimepicker]="picker"
[format]="24"
readonly
/>
<ngx-mat-timepicker #picker>

**Comment by payyavularajasekharholcim** [comment]
@Agranom Thank you very much. Its working fine :-)
