### ISSUE TITLE
NgxMaterialTimepickerModule is not compatible with Angular Ivy

### ISSUE THREAD

**Issue by sefatanam** [Agranom/ngx-material-timepicker#452]
**Issue:** Error while running Angular v16 app with ngx-material-timepicker due to Angular Ivy incompatibility.

**Error Message:** The library (ngx-material-timepicker) declaring NgxMaterialTimepickerModule appears to be incompatible with Angular Ivy. This could be resolved by updating to a newer version of the library that supports Ivy. It's advisable to communicate with the library's maintainers about Ivy compatibility.

**Request:** Kindly ensure Angular Ivy compatibility for NgxMaterialTimepickerModule.

**Reproduce:** Use NgxMaterialTimepickerModule with Angular v16

**My Environment:**
```
Angular CLI: 16.1.8
Node: 16.19.1
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 16.1.8
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.6
@angular-devkit/build-angular   16.1.8
@angular-devkit/core            15.2.6
@angular-devkit/schematics      16.1.8 (cli-only)
@angular/cdk                    14.2.7
@angular/material               14.2.7
@nguniversal/builders           15.2.1
@nguniversal/express-engine     15.2.1
@schematics/angular             16.1.8 (cli-only)
rxjs                            7.8.0
typescript                      4.9.5
zone.js                         0.13.1
```

**Comment by Agranom** [comment]
@sefatanam which version of timepicker do you use?

**Comment by sefatanam** [comment]
> @sefatanam which version of timepicker do you use?

    "ngx-material-timepicker": "^5.5.5",

**Comment by Agranom** [comment]
@sefatanam pls update to the latest version

**Comment by sefatanam** [comment]
> @sefatanam pls update to the latest version

one more thing need to know that is the latest version compatible with Angular Server side rendering?

**Comment by Agranom** [comment]
@sefatanam I haven't tried it with SSR. I guess the latest version should work

**Comment by Agranom** [comment]
Let me know if it doesn't

**Comment by sefatanam** [comment]
> Let me know if it doesn't 

yeah, sure
