### ISSUE TITLE
Feature request - editable time inputs

### ISSUE THREAD

**Issue by rainbird17** [Agranom/ngx-material-timepicker#49]
Some of our clients have requested the ability to click on the actual numbers that display the Time and directly edit them via keyboard (so they don't have to move the clock hands).

Would this be possible to add as an optional feature?

Thanks for your consideration.

**Comment by Agranom** [comment]
Hi. I'll think about it right after refactoring )

**Comment by jbthomps** [comment]
For my use case similar to this, it would be helpful to simply be able to edit the underlying input area in a consistent way and have it reflect back in the clock so that users don't necessarily have to go into the clock at all to enter something.

**Comment by Agranom** [comment]
already started implementing this feature. I guess it'll be done till the end of this week

**Comment by Agranom** [comment]
I implemented the feature. Update to 2.7.0 and look at the demo how to use it. Tell me your opinion about it please

**Comment by jbthomps** [comment]
From what I'm seeing, this looks really close.  The only thing that I see that's missing is input restriction (I can type any number of digits into the timepicker), and the ability to tab to AM/PM in the 12 hour clock.

My personal hope would be to have the input field itself that you focus editable when clicking on it, but it is somewhat separate from this original request, and I can raise it as a new issue if it'll make things easier.

**Comment by Agranom** [comment]
Yes, make it as a new issue please

**Comment by rainbird17** [comment]
I have the same thoughts:
- Input restriction to valid chars - I can type letters and other characters, it should only allow numbers
- Input restricted to 2 digits
- Input restricted to valid time (I should not be able to type 61 minutes, for example)
- Focus on click - I would prefer the numbers to be focused when first entering edit mode, it makes changing the value easier
- Add the ability to edit/tab to the AM/PM field so you can use keyboard there too
- Can we have the arrow keys move the values up/down?

Should I add these to a single new issue?  Or append them to jbthomps issue?  (not sure if he created it yet)

**Comment by Agranom** [comment]
You guys can merge your proposals to one issue, so that I can close this one. Thanks

**Comment by rainbird17** [comment]
fyi:  I created issue #56 for my enhancement requests....

Thank you so much for implementing this feature!
