### ISSUE TITLE
24h format doesn't work

### ISSUE THREAD

**Issue by maciejniedzielski** [Agranom/ngx-material-timepicker#5]
When I try to bind [format]="24" there is no change and I still get 12h format with AM/PM.

**Comment by Agranom** [comment]
It should work. Look at demo

**Comment by Agranom** [comment]
It works in another way. It doesn't change appearance of clock face, it changes returning value after you set the time

**Comment by maciejniedzielski** [comment]
Did you plan to add "change clock face to 24h format by input" feature? It would be nice and flexible for users that use 24h format clock's. What do you think about this? Will it be difficult to change your project and add this feature?

**Comment by Agranom** [comment]
I was thinking about it, and I'll try to do it next week.

**Comment by Agranom** [comment]
I decided that I wouldn't do it, because it doesn't look well. Timepicker has 12-hours skin and 24-hours clock face isn't appropriate there

**Comment by PeymanKhodadust** [comment]
@Agranom: C'moon dude... You've done an amazing job so far! Please don't leave it unfinished. You know there are people living outside of the anglosaxic world using the good old metric system... We don't know how to am/pm  ;-)

**Comment by Agranom** [comment]
It is already implemented )
