### ISSUE TITLE
Time editing via input field

### ISSUE THREAD

**Issue by jbthomps** [Agranom/ngx-material-timepicker#55]
My users expect to be able to edit the time within the input control itself to support full keyboard accessibility without having to enter the timepicker itself.  In other components, the timepicker/datepicker either had this functionality natively, usually also only allowing open by provided icon, or was exposed as a service, which allowed for the developer to combine timepicker access with a native component, usually by adding an icon button.

If it's possible, if it needs to be bound to an input, it would help to be able to be combined with input type="time", or to provide a directive that acts as a time mask over a standard input, but neither of these are strictly needed.

**Comment by jbthomps** [comment]
That is exactly what I mean.

**Comment by Agranom** [comment]
I'll do something with it

**Comment by Dona278** [comment]
@Agranom could you estimate the date to get this feature? However, congrats for this awesome work

**Comment by Agranom** [comment]
I have to fix other issues first, so it could be a few weeks, but I'm not sure. However, I'll try to implement it as soon as possible

**Comment by Aidan-Chey** [comment]
This reads like what I have just implemented with this timepicker package.

The Input: Add "disableClick" as an input to prevent it opening the picker
```
<input [ngxTimepicker]="picker" [disableClick]="true">
```
You can't add type="time" to the input however because it doesn't accept the format the picker supplies/expects.

The element to open the picker
```
<ngx-material-timepicker-toggle [for]="picker"></ngx-material-timepicker-toggle>
```

The picker itself
```
<ngx-material-timepicker #picker></ngx-material-timepicker>
```

**Comment by Agranom** [comment]
@Aidan-Chey  Sorry, I didn't get your reply

**Comment by rainbird17** [comment]
@Agranom - Has this feature been implemented yet?  This is of interest to me as well, I would be happy to see this as a feature someday.

**Comment by Agranom** [comment]
@rainbird17 Not yet. But this will be the next feature, right after resolving bug issues

**Comment by ndl7** [comment]
Awesome work. Any update on the feature? Been waiting for half a year for this :) Thanks!

**Comment by Agranom** [comment]
Sorry guys, still cannot start implementing it. I hope this month I'll start

**Comment by Agranom** [comment]
Start thinking about how it should look like. It probably will be a component not a directive. But  what about styling? Should it looks like a material input ?

**Comment by rainbird17** [comment]
We would prefer Material Design styling.  Also make sure it supports 12/24 hour inputs, and restrict inputs to valid chars and such.

**Comment by Agranom** [comment]
Guys, sorry, still can't start implementing component (

**Comment by Agranom** [comment]
Already started implementation. Do you need toggle button near time input to open timepicker ?

**Comment by jbthomps** [comment]
For my use case, I would.

**Comment by Agranom** [comment]
Finally done it ). First version available on v3.2.0 (look at the demo page). If you'd like some improvements/fixes, please create an issue, because I'll close this one.

**Comment by rajaramtt** [comment]
Without **ngxTimepicker** always getting **am** only,   Putting hidden of ngxTimepicker worked for me.

 Code Snippet 

**Template:**
```
<input [ngxTimepicker]="picker" type="hidden" [formControl]="pickerInput" />
 <ngx-material-timepicker #picker (timeSet)="timeSetData($event)"></ngx-material-timepicker>
```

**Comonet**
 ```
  @ViewChild('picker') picker: NgxMaterialTimepickerComponent ;
    pickerInput = new FormControl('');
      -----------------
  
 addTime():  void {
  this.pickerInput.setValue('12:00 am');
  this.picker.open();
  }

 timeSetData(outputData) {
     --------------------
}
```

**Comment by MerySantos** [comment]
Hi, how use timeSet in this feature?

**Comment by Agranom** [comment]
Hi @MerySantos This feature is not available there

**Comment by Diksha2519** [comment]
I want to show a Invalid dateTime error into an mat-error.Can anybody help me out?

**Comment by Agranom** [comment]
@Diksha2519 I guess, it's better to validate timepicker input field within your component by rective forms
