### ISSUE TITLE
Time Editing via Input Field - Enhancement Requests

### ISSUE THREAD

**Issue by rainbird17** [Agranom/ngx-material-timepicker#56]
Now that we have the ability to Edit the time via keyboard, it would be nice to implement these enhancements:

1. Input restriction to valid chars - I can type letters and other characters, it should only allow numbers
2. Input restricted to 2 digits for Hours and Minutes.  (should not be able to enter 0001 for example)
3. Input restricted to valid time (I should not be able to type 61 minutes, or 25 hours for example)
4. Focus on click - I would prefer the numbers to be focused when first entering edit mode, it makes changing the value easier because you click once and then enter your new value to overwrite the existing value.
5. Add the ability to edit/tab to the AM/PM field so you can use keyboard there too
6. Can we have the arrow keys move the hours/minutes/AM-PM values up/down?

Thanks in advance.

**Comment by Agranom** [comment]
does 1-3 need to be restricted? now it works like user can type any chars, but if it's invalid the previous valid time will set

**Comment by rainbird17** [comment]
I think it is better if it is restricted, it eliminates many possible bugs and makes the UI experience better.

If the user accidentally clicks an extra character and does not notice, they might think their change was accepted, but in fact it reverted to the previous value.

**Comment by Agranom** [comment]
Okey, I get your point. Hope this weekend I'll do it

**Comment by Agranom** [comment]
Implemented all features from the list above, exept switching between periods by arrows (I guess tabs are enough). Update to 2.9.0 and check it please

**Comment by Agranom** [comment]
@rainbird17  any updates?
