### ISSUE TITLE
Date format instead of custom string

### ISSUE THREAD

**Issue by altsanz** [Agranom/ngx-material-timepicker#58]
Actually I'm getting a string (9:18) using it with ngModel. It would be great if it could returns a Date object with the time inserted

**Comment by Agranom** [comment]
I will be the breaking changes for other users, I don't know if it costs so

**Comment by lisacopeland** [comment]
I am using a javascript Date object, if the user doesn't touch the control for the timePicker then the form value is still Date. If the user does modify the input then a string is returned - is this expected behavior? Can it always return a string or Date?

**Comment by Agranom** [comment]
Now the time picker always returns string

**Comment by lisacopeland** [comment]
> Now the time picker always returns string

Thank you!
