### ISSUE TITLE
24 Hour format displaying value input with am/pm

### ISSUE THREAD

**Issue by LinaRagauskaiteGSI** [Agranom/ngx-material-timepicker#62]
If input tag does not have value set, it will work just fine and selecting clock time sets input tag value to 24 hour format. However if input tag is associated with value for example 13:00, the value gets displayed as 01:00 pm, and selecting clock value set's input values to am/pm (clock is still 24 hours)

**Comment by Agranom** [comment]
Fixed. Update to 2.8.3
