### ISSUE TITLE
Feature - should be able to set default time without setting value of input element

### ISSUE THREAD

**Issue by Zaheer211** [Agranom/ngx-material-timepicker#64]
We use ngx-mateial-timepicker and want to set default time [06:00 pm] for clock to open at but don't want input element to show that default value.
Following is our form-design, you can see **Add time** makes more sense here, as clicking on it will open up time-picker.

![screenshot from 2018-11-04 18-41-52](https://user-images.githubusercontent.com/26340878/47964863-50644c00-e061-11e8-8cf2-c3cc8d9f5284.png)

Thanks

**Comment by Agranom** [comment]
So  you wanna see default time only when timepicker is opened, am I right?

**Comment by Zaheer211** [comment]
Yes, you got it right!
It would be better if we could provide default value through input to **ngx-material-timepicker**, or maybe some other way you think better to provide default time instead of using value attribute of input element.
Thanks

**Comment by Zaheer211** [comment]
Any update?

**Comment by Agranom** [comment]
Sorry, I feel lack of time. Hope to implement it this weekend

**Comment by Agranom** [comment]
Update to 2.10.0 and check it please.

**Comment by Zaheer211** [comment]
Thanks! I'll check and let you know.

**Comment by Zaheer211** [comment]
It's working as expected. Thanks
