### ISSUE TITLE
ExpressionChangedAfterr...

### ISSUE THREAD

**Issue by ljjolic** [Agranom/ngx-material-timepicker#66]
My timepicker is in a mat-form-field with <input matInput.....

I get this error when the timepicker pops up
ExpressionChangedAfterItHasBeenChcekedError; 

any ideas ?
Thx

**Comment by Agranom** [comment]
Yeah, I know, it will be fixed in the next release. I'll notice you

**Comment by adrianzaorski** [comment]
@Agranom I have similar issue, gonna provide you details so maybe it would be helpful.

I have a mat-dialog with some inputs inside, one of them:
```<mat-form-field>
    <input matInput
           formControlName="from"
           placeholder="Available from"
           [ngxTimepicker]="picker"
           [format]="24"
           required
           readonly>
  </mat-form-field>
  <ngx-material-timepicker [minutesGap]="5" #picker></ngx-material-timepicker>```

Opening a timepicker causes an error: `ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ng-untouched: true'. Current value: 'ng-untouched: false'`, but only once.

**Comment by derSoerrn95** [comment]
yes, nice 🙂

**Comment by adrianzaorski** [comment]
Yeah, just to confirm - after update everything is working fine and there is no error, thanks :)
