### ISSUE TITLE
Styling seems to fail

### ISSUE THREAD

**Issue by Flezria** [Agranom/ngx-material-timepicker#67]
Hello
I'm using the ngx-material-timepicker with semantic-ui, it seems like the styling is failing. Related image:
https://i.imgur.com/HcYqcpn.png
Is there anyway to disable the top? If so how?
If not, is there anyway to see the right selectors?

Thanks a lot.

**Comment by Agranom** [comment]
Hi. You can try to change styles.
Here's a related issue. It might help. https://github.com/Agranom/ngx-material-timepicker/issues/41
