### ISSUE TITLE
Focus on IPhone/IPad

### ISSUE THREAD

**Issue by adrian410** [Agranom/ngx-material-timepicker#68]
Hello,

When the timepicker open, it focus on the minute input directly and the keyboard appears.
The issue is only on iphone/ipad. I test it on https://app.crossbrowsertesting.com(trial version ). for my clients, it's an ipad simulator.

Can you change the focus when the timepicker open please ?

**Comment by adrian410** [comment]
I tried to get the latest version with : 
npm install --save Agranom/ngx-material-timepicker#master
So i have the following in my package.json : 
"ngx-material-timepicker": "github:Agranom/ngx-material-timepicker#master"

But i get this error :

ERROR in ./static/angular/app/app.module.ts
Module not found: Error: Can't resolve 'ngx-material-timepicker' in 'angular/app'
 @ ./static/angular/app/app.module.ts 12:32-66
 @ ./static/angular/app/index.ts
 @ ./static/angular/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./static/angular/main.browser.ts

When i go back to this version : 
"ngx-material-timepicker": "2.8.3"

I doesn't have the issue anymore.

**Comment by adrian410** [comment]
When i get your master branch i have the same exact file downloaded in my node_modules.

But when i get 2.8.3 version, i have this :
https://imgur.com/a/Tv84mkz

As if npm change the files in the way.

Do you know why i have this ?

**Comment by Agranom** [comment]
try just to install 2.8.4 version

**Comment by Agranom** [comment]
what is the status of this issue?

**Comment by adrian410** [comment]
Works well, solved ! Thanks !
