### ISSUE TITLE
value input doesn't appear to work.

### ISSUE THREAD

**Issue by miked49er** [Agranom/ngx-material-timepicker#7]
I have [value]="myTime" on the input element for the timepicker. However that time is not used for the initial value for the picker. Am I doing it wrong or is something broken?

**Comment by Agranom** [comment]
you mean time doesn't appear on the input?

**Comment by Agranom** [comment]
oh, you mean set value to input and then when timepicker opens that time should be set on the clock face?

**Comment by miked49er** [comment]
Yes that is what I was trying to do.

**Comment by Agranom** [comment]
add possibility to set default time https://github.com/Agranom/ngx-material-timepicker/commit/571ccb3785ee2f2cd5d8638a7fe76b949357c798 Update lib to the latest version

**Comment by thari119** [comment]
@Agranom can i use this value to set the time to the timepicker clock face on version 1.1.3? Because I'm on Angular 5 and build the app on that

**Comment by Agranom** [comment]
@thari119 no, sorry. It's been available since v2.2.2
