### ISSUE TITLE
Can I set min and Gap properties at the same time ?

### ISSUE THREAD

**Issue by dpadula** [Agranom/ngx-material-timepicker#74]
Is there a way ?

**Comment by Agranom** [comment]
yes, why not?

**Comment by Agranom** [comment]
like this 
```
<input [min]="time">
<ngx-material-timepicker [minutesGap]="5"></ngx-material-timepicker>
```

**Comment by dpadula** [comment]
compiler.js:215 Uncaught Error: Template parse errors:
Can't bind to 'minutesGap' since it isn't a known property of 'ngx-material-timepicker'.
1. If 'ngx-material-timepicker' is an Angular component and it has 'minutesGap' input, then verify that it is part of this module.
2. If 'ngx-material-timepicker' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("    [cancelBtnTmpl]="cancelBtn" 
                  [confirmBtnTmpl]="confirmBtn" 
                  [ERROR ->][minutesGap]="5"
                  #min>                
              </ngx-material-timepicker>
"): ng:///AppModule/CorteComponent.html@39:18
    at syntaxError (compiler.js:215)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14702)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:22709)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:22696)
    at compiler.js:22639
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:22639)
    at compiler.js:22549
    at Object.then (compiler.js:206)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:22548)

This occurs when:
              <ngx-material-timepicker 
                  #horaCorte 
                  [cancelBtnTmpl]="cancelBtn" 
                  [confirmBtnTmpl]="confirmBtn" 
                  [minutesGap]="5"
                  #min>                
              </ngx-material-timepicker>

              <input matInput placeholder="Hora del corte" 
                [ngxTimepicker]="horaCorte" 
                [format]="24" readonly
                formControlName="horaCorte" 
                [ngClass]="{ 'is-invalid': submitted && f.horaCorte.errors }"
                [ngxTimepicker]="min"
                [min]="minHora">

**Comment by Agranom** [comment]
you call timepicker twice [ngxTimepicker]="min"  [ngxTimepicker]="horaCorte"

**Comment by dpadula** [comment]
I'm Sorry, You're very right! I solved this way, (my mistake sorry again):

              <input matInput placeholder="Hora del corte" 
                [ngxTimepicker]="horaCorte" 
                [format]="24" readonly
                formControlName="horaCorte" 
                [ngClass]="{ 'is-invalid': submitted && f.horaCorte.errors }"
                [ngxTimepicker]="min"
                [min]="minHora"
                [ngxTimepicker]="minGap">

              <ngx-material-timepicker 
                  #horaCorte 
                  [cancelBtnTmpl]="cancelBtn" 
                  [confirmBtnTmpl]="confirmBtn" 
                  #minGap
                  #min>                
              </ngx-material-timepicker>

**Comment by dpadula** [comment]
Well I'm not doing this right

              <input matInput placeholder="Hora del corte" 
                [ngxTimepicker]="horaCorte" 
                [format]="24" readonly
                formControlName="horaCorte" 
                [ngClass]="{ 'is-invalid': submitted && f.horaCorte.errors }"
                [min]="minHora"
               >
             <ngx-material-timepicker 
                  #horaCorte 
                  [cancelBtnTmpl]="cancelBtn" 
                  [confirmBtnTmpl]="confirmBtn" 
                  [minutesGap]="5">                
              </ngx-material-timepicker>

That's not working, but:

              <ngx-material-timepicker 
                  #horaCorte 
                  [cancelBtnTmpl]="cancelBtn" 
                  [confirmBtnTmpl]="confirmBtn">                
              </ngx-material-timepicker>

that works fine, but only without the gap

**Comment by dpadula** [comment]
Exactly, I had version 2.6.0 and in 2.8.4 works fine. Thanks
