### ISSUE TITLE
Add @Input() upperCase: boolean for time value

### ISSUE THREAD

**Issue by dniadzelka** [Agranom/ngx-material-timepicker#76]
Add @Input() upperCase: boolean for time value (false by default)

[upperCase]="false" // 10:35 am
[upperCase]="true" // 10:35 AM

**Comment by Agranom** [comment]
I guess it is not necessary. You can use css for this

**Comment by dniadzelka** [comment]
You are right, I just overworked :)
`text-transform: uppercase;`
