### ISSUE TITLE
Suggestion: Use some other time library?

### ISSUE THREAD

**Issue by jvanallen93** [Agranom/ngx-material-timepicker#78]
Just as a suggestion, Moment is a fairly large library and there has been recent development in the time library area that can do 75-80% of what Moment can do. Might be worth looking into! If I can help in any way, please let me know!

**Comment by Agranom** [comment]
Hi. I've been thinking about working with locales and I guess Moment is good with that

**Comment by jvanallen93** [comment]
From my understanding, date-fns is the closest time library to Moment.
https://github.com/date-fns/date-fns/issues/275#issuecomment-264934189

**Comment by Enngage** [comment]
@jvanallen93 Actually Luxon is closer. Its been developed by one of Moment maintainers and it eventually came under Moment umbrella. Its really, really good. Especially the way it handles locales, its immutability and the fact that its so much smaller than moment itself.

**Comment by jvanallen93** [comment]
@Enngage this is awesome to see and thanks for another date package to investigate!

**Comment by checketts** [comment]
I'm also interested in avoiding moment. We are already using `date-fns` for other calendaring/date features.

As a guess, how difficult would it be to swap out moment? Is it something I could PR?

**Comment by Agranom** [comment]
I'm totally agree with you guys. And I'll change the library once I have time. I hope it will be soon

**Comment by Enngage** [comment]
That would be really awesome, thanks! Maybe you could leverage material's `DateAdapter`  (or create your own) so that one could use `date-fns`, `moment` or `luxon` or anything else should they wish to.

**Comment by Enngage** [comment]
Any news about this? Would like to switch to this lib when possible :-)

**Comment by Agranom** [comment]
Didn't have time for that. Going to start today.

**Comment by xxyuk** [comment]
@Agranom 

Can't personally vouch for it but have read about Day.Js as an alternative

⏰ Day.js 2KB immutable date library alternative to Moment.js with the same modern API

https://github.com/iamkun/dayjs

reference: moment/moment#2373 (comment)

**Comment by Enngage** [comment]
Nice overview of these libraries can be found here -> https://github.com/you-dont-need/You-Dont-Need-Momentjs 

I'm using Luxon as (in my opinion) its the most modern and already quite mature library + I needed timezone support.

**Comment by katan** [comment]
Here another one interested to avoid Moment.js

**Comment by Agranom** [comment]
I've already started with luxon library

**Comment by Agranom** [comment]
Done. Changed momentJs to luxon. But I'm not sure that size of the timepicker package's got smaller.

**Comment by Enngage** [comment]
@Agranom Awesome. I don't think the size of your library matters much - it's still very small. It's the moment dependencies that cause apps to bloat.

**Comment by katan** [comment]
Great work!
The angular's bundle size is reduced in ~250kb _(Parsed)_

Thanks a lot!

**Comment by Agranom** [comment]
Great. Hope those changes will not affect on functionality
