### ISSUE TITLE
ngx material timepicker css not show

### ISSUE THREAD

**Issue by manishksmd** [Agranom/ngx-material-timepicker#80]
Hi 
I used this in my angular project.
but css not show and not add ng classes in time picker. using angular 6

<div class="col-sm-4">
              <input matInput placeholder="End Time" formControlName="endTime" [ngxTimepicker]="endTime">
              <ngx-material-timepicker #endTime></ngx-material-timepicker>
            </div>

![11](https://user-images.githubusercontent.com/17270729/49799084-06f6d300-fd6a-11e8-812d-92e5220ecb1f.png)

**Comment by Agranom** [comment]
Hi. Could you reproduce your issue with https://stackblitz.com/, please?
