### ISSUE TITLE
minutesGap issue with value set

### ISSUE THREAD

**Issue by amourinho** [Agranom/ngx-material-timepicker#81]
If the minutesGap and value are set, the value MUST be a multiple of the minutesGap interval otherwise the component bugs out. 

To test, set a value for minutesGap, and for the value use a new Date object. If you click on the input and the value is not a multiple of the minutesGap you should be greeted with an error in your console and a bugged out time picker component. I resolved this issue with a simple rounding date function.

`
  getRoundedDate = (minutes, d=new Date()) => {
    let ms = 1000 * 60 * minutes;
    return new Date(Math.round(d.getTime() / ms) * ms);
  }
`

Where minutes should equal the minutesGap, and the following parameter is a date. If none is set, it uses the current date.

**Comment by Agranom** [comment]
Error shows because your minute isn't allowed with your minutesap

**Comment by Agranom** [comment]
Added readable error and preventing setting default time if default minute isn't allowed with provided minutesGap
