### ISSUE TITLE
Feature - should be able to limit time selection with multiple time ranges

### ISSUE THREAD

**Issue by Zaheer211** [Agranom/ngx-material-timepicker#82]
Currently **ngx-material-timepicker** allows to limit time selection within one range. We want to limit time selection by providing multiple time ranges. 
**Example:**
It should allow to select time within these ranges.
08:00 am to 11:00 am 
03:00 pm to 07:00 pm
09:30 pm to 11:30 pm

It would be hugely appreciated if we can have quick help in this regard. 
Thanks

**Comment by Agranom** [comment]
Thanks for your suggestion, but I'm not sure with that. I guess it's a little bit overhead for the timepicker

**Comment by Agranom** [comment]
Maybe by using the timepicker for each time range?

**Comment by Zaheer211** [comment]
Well that requires to open time picker for same date again and again, as we have multiple time ranges available on same date. 
We did a workaround by using a snack-bar error message. 
Anyway I'm closing this feature request as you said it's a bit overhead for time-picker.
