### ISSUE TITLE
Using providedIn: 'root' instead of .forRoot() configuration

### ISSUE THREAD

**Issue by IlCallo** [Agranom/ngx-material-timepicker#83]
Correct me if I'm wrong, but isn't it possible to define `NgxMaterialTimepickerService` and `NgxMaterialTimepickerEventService` using

```ts
@Injectable({
  providedIn: 'root'
})
```

instead of requesting to import the library using a `.forRoot()` method?

Just a style thing I guess, but providing services inside a Module is no more a best practice since Angular 6

**Comment by Agranom** [comment]
Yes, you're right, but those are breaking changes. I'll change it in the near future with other breaking changes

**Comment by Agranom** [comment]
I'm thinking about to change date library from momentJs to something else.

**Comment by Agranom** [comment]
Done
