### ISSUE TITLE
NgxMaterialTimepickerTheme not exposed in public api

### ISSUE THREAD

**Issue by IlCallo** [Agranom/ngx-material-timepicker#85]
As written by the title, `NgxMaterialTimepickerTheme` file has not been exposed into public api.
It currently require a deep path (`ngx-material-timepicker/src/app/material-timepicker/models/ngx-material-timepicker-theme.interface`) instead of the short one (`ngx-material-timepicker`).

I think it's just a matter of adding a new export line in [public_api.ts](https://github.com/Agranom/ngx-material-timepicker/blob/master/public_api.ts)

**Comment by Agranom** [comment]
Fixed. Update to the latest version.
