### ISSUE TITLE
Displayed time not centered when using 24h format in vertical layout

### ISSUE THREAD

**Issue by IlCallo** [Agranom/ngx-material-timepicker#86]
Time must be centered, but when AM/PM choice is removed (24h format) it shifts to the right.
This happens only with the vertical disposition.

![image](https://user-images.githubusercontent.com/10036108/50402260-85ee0180-0795-11e9-9f8c-54f5b6bcd5e7.png)

**Comment by Agranom** [comment]
But it shouldn't be centered. Time has alignment by right side.

**Comment by IlCallo** [comment]
Ok, I wrote "shift to the left", while I meant "shift to the right", I edited the first post.
I'm taking as example timepicker in Google Calendar, in which the time is always centered even with 24h format and it seems to me that it's much more pleasant than having it pushed to the right, especially considering that in 12h format it _**is**_ centered and the clock itself is centered as well.

See:
![image](https://user-images.githubusercontent.com/10036108/50449197-ffb4f500-0925-11e9-88ed-53d3f2af9248.png)

Here some other implementations which keep time horizontally centered:
- https://material-ui.com/demos/pickers/#material-ui-pickers
- https://github.com/TeamWertarbyte/material-ui-time-picker

**Comment by Agranom** [comment]
I agree with you. The centered one is better

**Comment by Agranom** [comment]
Fixed. Update to the latest version.
