### ISSUE TITLE
Vertical disposition even on large screens

### ISSUE THREAD

**Issue by IlCallo** [Agranom/ngx-material-timepicker#87]
I assume that vertical layout is for smaller screens, while the horizontal one is for desktop-wide screens.
But there's a width waypoint after which timepicker displays vertical layout even if on wide screens.
Maybe a wrong media query with an upper bound which should not be there?

**Comment by IlCallo** [comment]
What do you mean with "landascape orientation"? Just the ones which declares themselves as landscape, or every display in which viewport width is greater than height?

**Comment by Agranom** [comment]
I'll make horizontal position for mobile devices with landscape orientation

**Comment by Agranom** [comment]
Fixed. Update to the latest version.
