### ISSUE TITLE
ngx-material-timepicker

### ISSUE THREAD

**Issue by shahidsan** [Agranom/ngx-material-timepicker#9]
It seems if one define more than one ngx-material-timepicker, it shows what i set last for both the controls. Below is the HTML i am using, can you help?

  <div style="display:flex" fxLayoutGap="20px">
      <div style="flex: 1">
          <mat-form-field fxFlexFill>
    
        <input matInput  placeholder="Start Time" [ngxTimepicker]="startpicker" value={{startTime}}>
        <ngx-material-timepicker id="myone" #startpicker></ngx-material-timepicker>
        </mat-form-field>
      </div>
    <br>
      <div style="flex: 1">
          <mat-form-field fxFlexFill>
    
        <input matInput placeholder="End Time" [ngxTimepicker]="endpicker" value="{{endTime}}" >
        <ngx-material-timepicker id="mytwo" #endpicker></ngx-material-timepicker>
        </mat-form-field>
      </div>
   
    </div>

**Comment by Agranom** [comment]
closed https://github.com/Agranom/ngx-material-timepicker/commit/409b032c52f030203578709dcf57b2a28ca2cd5d
