### ISSUE TITLE
Issue: Encountered undefined provider for ngx-material-timepicker

### ISSUE THREAD

**Issue by joelduncan1** [Agranom/ngx-material-timepicker#91]
npm: 6.5.0
node: 8.11.4
angular: 6.0.8

[ISSUE]
npm build:prod having an issue detecting ngx-material-timepicker have an undefined providers for version 2.11.1

[ALTERNATIVE]
I reverted my node module for ngx-material-timepicker  to 2.8.4 and it works.

**Comment by IlCallo** [comment]
Confirm too, with this error

```ERROR in : Unexpected value 'undefined' exported by the module 'NgxMaterialTimepickerModule in [...]/node_modules/ngx-material-timepicker/ngx-material-timepicker.d.ts'```

**Comment by IlCallo** [comment]
I confirm error disappear downgrading to 2.11.0

**Comment by ErickXavier** [comment]
I also confirm the issue. Added a console.log('type', type) in the line **18783** of the file **ngx-material-timepicker/src/app/material-timepicker/ngx-material-timepicker.module.ts** and this popped up:

`
type { ngModule:
   StaticSymbol {
     filePath: 'C:/Users/admin/Projects/my-project/node_modules/ngx-material-timepicker/ngx-material-timepicker.d.ts',
     name: 'NgxMaterialTimepickerModule',
     members: [] },
  providers: [ undefined, undefined ] }
`

**Comment by Agranom** [comment]
I'll find out the problem and fix it in the next two days. Sorry for this.

**Comment by IlCallo** [comment]
No problem man, it's still open source stuff you give away for free.
Take your time, and thank you :)

**Comment by Agranom** [comment]
Fixed. Update to 2.11.2
