### ISSUE TITLE
problem with overwrites

### ISSUE THREAD

**Issue by mosilver** [Agranom/ngx-material-timepicker#92]
can you provide any example of:
ngxMaterialTimepickerTheme: NgxMaterialTimepickerTheme 
Custom properties which will override the defaults

I can't find any ngxMaterialTimepickerTheme class, what is the structure of it?
Is this the proper way to overwrite the css styles?

**Comment by Agranom** [comment]
Here is the demo (the last  example) https://agranom.github.io/ngx-material-timepicker/
