### ISSUE TITLE
Optimizing problem

### ISSUE THREAD

**Issue by Floaz** [Agranom/ngx-material-timepicker#94]
Hi,

i have a problem with your great timepicker library when i made a `ng build --prod` with optimizing (which is default in prod).

Then I get this error:

> iN.getHours is not a function

I find out that the uglified `iN` stands for the TimepickerTime namespace. But it is empty after the build.
It works with angular build option optimizing=false and in dev environment.
Very strange behaviour o.O and I do not have an idea of a solution after 6 hours!

Tested with Angular (Core/Material/CLI) version 6.0.0 and 7.1.4.

Yours sincerely,
Philipp

**Comment by Agranom** [comment]
Hi @Floaz ,
Which version do you use?

**Comment by Floaz** [comment]
Hi @Agranom,
it is version 2.11.0 of ngx-material-timepicker, because of Issue #91 (Encountered undefined provider for ngx-material-timepicker) I downgraded.

**Comment by Agranom** [comment]
Any updates?

**Comment by cburchett** [comment]
I have the same problem with 2.13.0.  It works with ng serve (dev enviornment) but not when doing ng build --prod.

**Comment by Agranom** [comment]
I'll check it

**Comment by Agranom** [comment]
I've tested it with  "optimization": true option and it works

**Comment by Moik** [comment]
I have encountered the same issue that appears on production. Timepicker version 3.0.2, Angular version 6.0.0

**Comment by Agranom** [comment]
Guys, maybe you have the same problem as here https://github.com/Agranom/ngx-material-timepicker/issues/65 ?

**Comment by Moik** [comment]
I spent some time and found out 2 possible solutions. The first and the most obvious is updating angular and typescript to the latest versions. Unfortunately, it is not an option for me, at least for now. Second is removing TimepickerTime namespace from [here](https://github.com/Agranom/ngx-material-timepicker/blob/b188554f63c8862d4c56faa9a4017d5a1d98ec22/src/app/material-timepicker/utils/timepicker-time.namespace.ts#L7) and exporting functions from it directly. I don't quite understand what happenning here, but it fixes the issue. @Agranom if you considering reorganizing your namespaces, it could be helpful

**Comment by Agranom** [comment]
@Moik Thank you for your investigation. I'll separate functions and remove TimepickerTime namespace in the next release

**Comment by Agranom** [comment]
Could you please update to v3.0.3 and check?

**Comment by Moik** [comment]
Seems like it's working now, thank you.
