### ISSUE TITLE
minute gap of 1 doesn't reset component

### ISSUE THREAD

**Issue by ArnoMyOnlinePresence** [Agranom/ngx-material-timepicker#98]
Hey guys

we have a big site so i created 1 datetime picker with this time picker which takes in a minutegap as paramater.
The problem is some places I need it to be intervals of 15 and some places i need it to be intervals of 5 and in other places i need the default where it shows minute gap of 5 but you can still select in between (like the default).
Making the minutesGap = 1 is not working as expected.
[image](https://imgur.com/a/8HLkdHw)

**Comment by Agranom** [comment]
I see, I'll set  default behavior if minutesGap = 1

**Comment by Agranom** [comment]
On the last version I added condition to minutesGap, and if you set `null` or `undefined` - minutesGap will be default
